### PR TITLE
Using the CLI commands is not producing errors anymore

### LINKED ISSUE #5558: GiveWP CLI commands should not produce a fatal error
## User Story

As a developer, I want that GIveWP CLI commands are working correctly without producing errors. 

## Details

Currently, when trying to use the GiveWP CLI commands will produce a fatal error.

`[15-Jan-2021 09:48:15 UTC] PHP Fatal error:  Uncaught ReflectionException: Class Faker\Generator does not exist in /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php:744
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(744): ReflectionParameter->getClass()
#1 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(707): Give\Container\Container->resolveDependencies()
#2 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(595): Give\Container\Container->build()
#3 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(538): Give\Container\Container->resolve()
#4 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(821): Give\Container\Container->make()
#5 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(746): Give\Container\Container->resolveClass()
#6 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(707): Give\Container\Container->resolveDependenc in /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php on line 744`

## Expected Behavior

Using the GiveWP CLI command should not produce fatal errors. 

## Steps to Reproduce

1. Download and install GiveWP from the WordPress.org site
2. Open the terminal and run the `wp give` command

## Acceptance Criteria

-   [ ] Using GiveWP CLI commands should work correctly and without producing errors

### PR DESCRIPTION
**Pull request by alaca**
Resolves #5558

## Description

In the last release of the GiveWP, a fatal error will occur if the users are trying to use the CLI commands. The reason for that is that we integrated new Test Data CLI commands which are using the Faker lib to generate seeding data. The problem was that the Faker library was installed as a dev dependency meaning that will be used only in the development process.  The problem is resolved by simply including the Faker library as a dependency.  

## Affects

GiveWP CLI commands

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

1. Install dependencies using `composer i --no-dev`
2. Try to run `wp give` CLI command

### CODE REVIEW

**Review by kjohnson — COMMENTED** [review]
@alaca Exactly what I was thinking.

@JasonTheAdams can we get this PR packaged to test when bundled?

**Comment by JasonTheAdams** [comment]
I just made a pre-release which made a build: https://github.com/impress-org/givewp/releases/tag/2.9.7

After testing, please let me know so I can delete the release and tag.

**Comment by kjohnson** [comment]
@JasonTheAdams it looks like the `vendor` folder is missing from that build.

**Comment by kjohnson** [comment]
@alaca looks like faker didn't make it into the build, which is why I wanted to test on a builder before pushing this through.

**Comment by kjohnson** [comment]
@alaca looks like we need to update the `composer.lock` file.

image

**Comment by alaca** [comment]
@kjohnson I have no idea how I didn't commit that change. Done!

**Comment by kjohnson** [comment]
@alaca thanks! I didn't catch it either.

@JasonTheAdams uno más, por favor.

**Comment by JasonTheAdams** [comment]
@alaca @kjohnson What's the status of this? Is this ready to merge?

**Comment by alaca** [comment]
@JasonTheAdams I have updated the `composer.lock` file. Can you make another pre-release so that we can test it?

**Comment by JasonTheAdams** [comment]
@alaca Sure! You can find the new release here: https://github.com/impress-org/givewp/releases/tag/cli-fix

**Comment by alaca** [comment]
@JasonTheAdams the `Faker` lib is still missing from the `vendor` directory, but it is added as a dependency. Looks like the `composer install` command didn't run for this build. 

image

**Comment by kjohnson** [comment]
@alaca looks like the lock file still wasn't up to date - not sure why because I see your change.

image

**Comment by kjohnson** [comment]
I'm getting the same results locally - same lock warning.

image

**Comment by kjohnson** [comment]
Running `composer update --lock` seem to resolve the dependency update.

image

**Comment by kjohnson** [comment]
@JasonTheAdams ok - one more time - I promise (fingers crossed).

**Comment by alaca** [comment]
@kjohnson I'm not sure what happened. I did run `composer update `before pushing the last commit.

**Comment by kjohnson** [comment]
@alaca yeah, I saw the lock update. Not sure why that didn't work.

This isn't something that we do often, changing production composer dependencies. So I'll count this as a fluke - no problem.

**Comment by JasonTheAdams** [comment]
Let's hope third time's the charm! https://github.com/impress-org/givewp/releases/tag/cli-fix 😉

**Comment by JasonTheAdams** [comment]
@kjohnson I thinks something in `develop` broke the tests: https://github.com/impress-org/givewp/runs/1780740526?check_suite_focus=true

**Comment by kjohnson** [comment]
Yeah, I think I have that fixed in a local branch. I'll cherry pick it into a separate PR. Un momento, por favor.

**Comment by JasonTheAdams** [comment]
Still failing, I'm afraid: https://github.com/impress-org/givewp/runs/1788151618?check_suite_focus=true

**Comment by kjohnson** [comment]
Ah, that is in the GitHub workflow - just pushed a fix.

**Comment by kjohnson** [comment]
Ok - got my pipeline change to take effect.

**Pull request merged**
