### PR TITLE
Feature: form migration design updates

### PR DESCRIPTION
**Pull request by alaca**
## Description

This PR implements form migration design updates.

## Affects

Form Builder
Donation forms list table

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205585333330832

### CODE REVIEW

**Comment by kjohnson** [comment]
### All Forms list page
- [ ] Add hover state to "Try the new form builder button"
- [ ] Trash option should be red
- [ ] Add confirmation modal to Trash option, similar to when you delete a Donor from the Donors page
- [ ] Ensure tool tip for Upgraded status appears upon visiting page after the first completed form migration

### Edit Form page
- [ ] Add hover state to "Upgrade this form" button
- [ ] Feature Notice modal
- [ ] Make "Proceed with upgrade" button on smaller
- [ ] Make sure "Proceed with upgrade" button has background color Blue 50
- [ ] Check line height of text, both paragraph and list
- [ ] Check spacing between paragraph and "Supported add-ons" heading

### Visual Builder
- [ ] Form Upgraded modal
- [ ] Check modal padding
- [ ] "Your form has been upgraded" heading in the modal should be larger font size
- [ ] Check line height of description text.
- [ ] Check "Got it" button size and color. It's a little bigger than in the design: should be 3rem
- [ ] Transfer Data banner
- [ ] Check height; It should be 3.5rem or 56px
- [ ] Unbold font on "Transfer data" button

### Transfer existing donation data modal
- [ ] Check spacing between description and button should be reduced.
- [ ] Space between the title and description should be reduced.
- [ ] Confirmation has the same spacing issues
- [ ] Transfer completed successfully has the same style issues

**Comment by kjohnson** [comment]
Minor overflow issue when the "upgraded" tool tip is show with only one form in the table.

image

**Comment by kjohnson** [comment]
The "Proceed with upgrade" button should have a background color of `var(--wp-blue-blue-50)` instead of `var(--givewp-blue-500)`.

image

**Comment by kjohnson** [comment]
The feature notice modal paragraph text defaults to a line height of `1.5` (per WordPress admin styles), but should be `1.375` according the the design in Zeplin.

| 1.5 | 1.375 |
| --- | --- |
|image|image|

**Comment by kjohnson** [comment]
> ]Visual Builder] Check "Got it" button size and color. It's a little bigger than in the design: should be 3rem

The size of the button is a product of the font and the padding, which is correct according to the design. However, the difference in font results in a _slightly_ larger button that `3rem`.

| Expected | Actual |
| --- | --- |
|image|image|

**Comment by kjohnson** [comment]
> [Transfer existing donation data modal] Space between the title and description should be reduced.

The title should have a bottom margin of `var(--givewp-spacing-2)` but currently has `var(--givewp-spacing-3)`.

Alternatively, we could using CSS grid (in a column) to specify the spacing between elements instead of relying on bottom margins.

**Review by kjohnson — CHANGES_REQUESTED** [review]
That is a lot of changes! Just a couple of small things and then I think we can get this past @jdghinson 🔍 .

**Comment by alaca** [comment]
Regarding this:

> The "Proceed with upgrade" button should have a background color of var(--wp-blue-blue-50) instead of var(--givewp-blue-500).

The WP colors are not loaded inside our form builder, so I suggested @jdghinson to use Give foundation colors in designs. He updated the  design of the "Upgrade" button here https://app.zeplin.io/project/63ff61fbfff004400bc0f048/styleguide/components. Since we are using the same button component for all onboarding dialogs, it might be a good idea to have consistent button colors everywhere.

**Comment by alaca** [comment]
> The size of the button is a product of the font and the padding, which is correct according to the design. However, the difference in font results in a slightly larger button that 3rem.

Yeah, I have tried to c/p the styles from Zeplin for all elements, but it doesn't work. I always had to tweak something.

**Comment by jdghinson** [comment]
@alaca The reason for using wp-blue-blue-50 was intentional because Devin agreed to us using that color as our primary color instead of blue/500. That is why you see that color in most our primary buttons. The color of the button changes based on it's application. A prime example is the migration card with the "upgrade this form" button. Ideally the default state should be wp-blue-blue-50 and the hover state being wp-blue-blue-60. Can we add the wp-blue pallet to our foundation to avoid these conflicts.

Cc: @kjohnson

**Comment by alaca** [comment]
@jdghinson I can add those colors in button styles.

**Review by kjohnson — APPROVED** [review]
Alright - looks good to me!
Next, to QA.

**Pull request merged**
