### PR TITLE
Custom amount level is correctly set after a payment error

### LINKED ISSUE #5912: Payment errors should not revert to default donation amount
## Description

> If I select a custom amount for my donation and have my card declined by an incorrect card number, the donation amount should stay on the original custom amount entered and NOT revert to the default amount set for the form.

## Acceptance Criteria

- [x] Payment errors restore selected donation level.
- [x] Payment errors restore custom donation amounts.

### PR DESCRIPTION
**Pull request by kjohnson**
Revisits #5912, after changes included by #5913, in response to https://github.com/impress-org/givewp/pull/5913#issuecomment-897352881 and https://github.com/impress-org/givewp/issues/5912#issuecomment-898553249.

## Description

We can not figure out custom amount after redirection. For this reason we add `custom-amount` to redirect url. This helps us to reset `custom` level id and donor custom amount after redirection. `autoSetMultiLevel ` does good job and set donation amount correctly. For this reason instead of manual set focus on amount field and exit early from function, we only setup correct donation amount when level id set to `custom` and rest will be handle by function.

## Testing Instructions

- Set a custom donation amount
- Submit payment with payment error
- Re-submit with successful card - no errors
- Form should submit correctly with the custom amount.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by ravinderk — APPROVED** [review]
@kbjohnson90 I tested this pull request and it is working fine for me.

I made changes to pull request because i think there are not any reason to exit function in middle if price id set to `custom`. All statements after set custom amount `if` condition looks reasonable, so i remove early exit from code.


@JasonTheAdams Can you also test this pull request

**Comment by kjohnson** [comment]
@ravinderk this is a different approach than what I describe in the PR description. Would you mind posting an updated description that reflects your simplification/refactor of the proposed change?

**Comment by ravinderk** [comment]
> @ravinderk this is a different approach than what I describe in the PR description. Would you mind posting an updated description that reflects your simplification/refactor of the proposed change?

Issue description updated.

**Comment by JasonTheAdams** [comment]
I'm still getting an error if I try to immediately process a payment with a good card:
Screen Recording 2021-08-20 at 11 27 28 AM

**Comment by kjohnson** [comment]
Ugh. I did test that and it is working on my machine...

@JasonTheAdams did you run `npm run dev` locally after pulling down the changes?

**Comment by JasonTheAdams** [comment]
Hmm, I may have been running into... you guessed it... caching issues. Triple-checking now.

**Review by JasonTheAdams — APPROVED** [review]
Was having caching issues. 🤦‍♂️

Works great!

**Pull request merged**
