### PR TITLE
Refactor: default multi-step form layouts will have header detached from form

### PR DESCRIPTION
**Pull request by jonwaldstein**
Resolves [GIVE-201]

## Description

This updates the default multi-step enabled form layouts to have the header _detached_ from the form. To include the header as the first step, form layouts will now have an opt-in property on their class called: `$includeHeaderInMultiStep`.  

This approach will allow more flexibility for form layouts to display and style both the header and multi-step forms.

## Affects

- Currently this affects the existing multi-step form design (_under-the-hood_) however everything should work as expected.

## Visuals

Screenshot 2024-01-05 at 10 34 52 AM

### With `$includeHeaderInMultiStep` as false

Screenshot 2024-01-04 at 2 41 29 PM

## Testing Instructions

- Pull branch and build assets
- Test the existing multi-step form - especially with the "show header" setting
- If you want to get fancy - programatically update the `$includeHeaderInMultiStep` to false in `MultiStepFormDesign` and see the default header positioning.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-201]: https://stellarwp.atlassian.net/browse/GIVE-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@pauloiankoski this is ready for review.

**Review by pauloiankoski — COMMENTED** [review]
Hey @jonwaldstein, what do you think about keeping props/functions/variables that share the same purpose named equally everywhere to keep consistency? Otherwise, this is good to move forward.

For instance:

```diff
- 'includeHeaderInMultiStep' => $formDesign->shouldIncludeHeaderInMultiStep(),
+ 'includeHeaderInMultiStep' => $formDesign->includeHeaderInMultiStep(),
```

```diff
- const shouldIncludeHeaderInSteps = form.design?.includeHeaderInMultiStep && form.settings?.showHeader;
+ const includeHeaderInMultiStep = form.design?.includeHeaderInMultiStep && form.settings?.showHeader;
```

**Comment by pauloiankoski** [comment]
@jonwaldstein Found another thing we may need to mod once the header is not attached to the multi-steps form:

CleanShot 2024-01-05 at 17 52 57
_StepsWrapper.tsx_

That causes the first step to never have its title:
CleanShot 2024-01-05 at 17 54 24

**Comment by jonwaldstein** [comment]
> Hey @jonwaldstein, what do you think about keeping props/functions/variables that share the same purpose named equally everywhere to keep consistency? Otherwise, this is good to move forward.

I'm going with the fields api approach where finding the value of a boolean uses the declarative naming convention using the `should` prefix so `$design->shouldIncludeHeaderInMultiStep` - where as the method name that matches the property name would be a setter like `$design->includeHeaderInMultiStep(true)` (not currently but gives that flexible consistency)

**Comment by jonwaldstein** [comment]
> @jonwaldstein Found another thing we may need to mod once the header is not attached to the multi-steps form

@pauloiankoski looks like you discovered a bug with multistep forms in general, i'll work on fixing that in another PR.

**Comment by jonwaldstein** [comment]
> > @jonwaldstein Found another thing we may need to mod once the header is not attached to the multi-steps form
> 
> @pauloiankoski looks like you discovered a bug with multistep forms in general, i'll work on fixing that in another PR. When choosing to hide header the title does not show up on the first step.

FYI: PR was opened to resolve this issue #7174

**Review by pauloiankoski — APPROVED** [review]
👍🏻

**Pull request merged**
