### PR TITLE
Apply Stripe fee when applicable

### LINKED ISSUE #5555: Stripe fees should be applied when applicable
## User Story

As a paying customer, I want to be sure I'm using Stripe without fees so that I get the full revenue from my donations.

## Details

There is some recurring confusion which customers have in _how_ to remove the 2% stripe fee applied when only using GiveWP core. Presently, the fee is removed if the Give Stripe add-on is installed. This has led to issues wherein customers didn't understand how important it is to install Give Stripe, as perhaps they thought they don't need any of the extra features it offers.

The fact is, there are other ways to determine whether a person using GiveWP core is a paid customer or someone using the free plugin only. The solution is most likely within the account licensing system, wherein a user enters a license key and our system verifies it. Perhaps we could check to see if there any active licenses.

The goal of this issue is to audit how the fee is applied and removed, and determine any ways we can help honest users and remove the fee when safely applicable.

## Acceptance Criteria

-   [x] The 2% Stripe Fee is removed when a premium add-on or bundle license is active
-   [x] The 2% Stripe Fee remains when only GiveWP core is installed and no licenses are active

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves #5555

## Description

Added logic to add Stripe application fee when applicable. I applied the rule written in [this comment](https://github.com/impress-org/givewp/issues/5555#issuecomment-759596226).

## Testing Instructions

Stripe application fee should not apply to one time donations when
- Stripe pro addon active.
- Stripe pro addon install.
- Stripe single license active.
- All access pass license active (includes Stripe addons)

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by kjohnson — COMMENTED** [review]
I might suggest extracting the different logical checks - I see three (3) distinct checks that could each be encapsulated.

I also have some ideas on how we can make this testable, which I'll put together here shortly.

**Comment by ravinderk** [comment]
> I might suggest extracting the different logical checks - I see three (3) distinct checks that could each be encapsulated.
> I also have some ideas on how we can make this testable, which I'll put together here shortly.

@kjohnson looking forward to this.

**Comment by kjohnson** [comment]
@JasonTheAdams since I am now a contributor to this PR would you mind to review it as well?

**Review by JasonTheAdams — APPROVED** [review]
Great work @ravinderk and @kjohnson! Hopefully this will help our customers avoid unnecessary fees. 🙌

**Pull request merged**
