### PR TITLE
feat: make embed form compatible with give_form shortcode

### LINKED ISSUE #4544: feat:  make embed form compatible with give_form shortcode
# Feature Request

## Developer Story

As a developer, I want to make embed form compatible with `give_form` shortcode so that admin can use it.

## Acceptance criteria
- [ ] <s>Gutenberg block and widget have to set a form as embed and custom form template.</s>: We will resolve it in a separate issue.
- [x] Make embed form compatible with `display_style` and form will open in a modal when it set to `button`.

### PR DESCRIPTION
**Pull request by ravinderk**
## Description
This PR will resolve #4544.

Note: I did not integrate embed form with form grid in this PR that needs a discussion before implementation.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@ravinderk @DevinWalker Since this indirectly has to do with the Gutenberg block settings, should I hold off on review this until you've had a chance to determine how we want forms to be loaded in relation to the template?

**Comment by ravinderk** [comment]
@JasonTheAdams I think we can review it because @DevinWalker will suggest only template options related changes which will not make bigger difference in this pr.

**Comment by JasonTheAdams** [comment]
Not necessarily. I believe @DevinWalker was saying that we don't want folks to be able to select a specific template at runtime; a template must be selected within the form settings, and can't be change otherwise. If that's the case, then the ability to select a template within the shortcode should be removed.

**Comment by ravinderk** [comment]
Video from @DevinWalker https://www.loom.com/share/d59f696b322547cba9d8e81c9d0dcfbf

issues spotted in the video:

- [ ] Do not use extra shortcode param ( like `embed` ) to detect to render form template other than `legacy` or not.
- [ ] Render form template on single form page if other then `legacy` template
- [ ] Remove extra setting from widget and Gutenberg block and use form setting to detect form template.
- [ ] Admin must able to see form template in preview.

**Comment by ravinderk** [comment]
@JasonTheAdams I will do that.

**Pull request merged**
