### PR TITLE
Donor Profile receipt content should match receipt displayed during donation

### LINKED ISSUE #5639: Donor Profile receipt content should match receipt displayed during donation
## User Story

As a donor, I want receipt content displayed in the Donor Profile to exactly match what I was shown in the donation process so that I can review all relevant details of my transaction consistently.

## Details

Currently, receipt content displayed in the Donor Profile displays the same fields for all donations. This is good for displaying the minimum needed information about a donation, but fails to handle dynamic receipts created by Fee Recovery, FFM or other addons. The receipt content in Donor Profiles should be identical to the receipt shown to a donor when they complete the donation process.

## Additional Context

This issue was first raised as it relates specifically to Fee Recovery, in this comment: https://github.com/impress-org/givewp/issues/5628#issuecomment-783974582

## Acceptance Criteria

-   [x] Receipt content in donor profile (found in both recurring donations, and donation history tab) should match receipt displayed to donor at the end of donation process

### PR DESCRIPTION
**Pull request by henryholtgeerts**
Resolves #5639 

## Description

This PR introduces logic to ensure that the Donation receipt presented inside Donor Profiles matches the donation receipt shown to donors during the donation process. This includes dynamic donation-specific line items like processing fees, subscription information, and custom field information.

## Affects

This PR affects the Donation Receipt view of Donor Profiles, and the Donations repository logic used to retrieve and describe a donor's donation history.

## Visuals

Screen Shot 2021-03-03 at 5 44 54 PM

## Testing Instructions

1. Make a donation with dynamic receipt line items (custom fields, subscription, fee recovery, etc).
2. Note the line items shown in your donation receipt during the donation process.
2. From the Donor Profile, view the receipt for that donation.
3. Check that the receipt line items shown inside Donor Profiles match the receipt you were shown during the donation process.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by kjohnson** [comment]
@henryholtgeerts lets be sure to implement the same hooks here so that custom code (ie Fields API) can add fields to the receipt.

**Comment by henryholtgeerts** [comment]
@kjohnson Great point, and the changes proposed here cover that as well. 👍 I'm using the same `do_action( 'give_new_receipt', $receipt )` approach that is used to render the receipt template, so everything works identically.

**Comment by kjohnson** [comment]
@henryholtgeerts 🙌🏻 Wonderful.

**Comment by kjohnson** [comment]
@henryholtgeerts super cool to see this work with the Fields API! I did a local merge of the two epic branches - "how you say, no sweat."

| Donation Meta | Donor Meta |
| --- | --- |
| Screenshot_2021-03-04 Donor Profile – WordPress(1) | Screenshot_2021-03-04 Donor Profile – WordPress |

**Review by kjohnson — APPROVED** [review]
I came across two things, but I don't think they are related to this PR, so I'm approving this change and passing along my feedback:

- The app doesn't seem to handle 500-status requests. I had a bug in my custom code and the error prevented the app from rendering properly, which looked like the app wasn't working. We'll need to consider how we handle API requests that do not return as expected.
- I'm seeing a `0` (zero) in the bottom right of the receipt - not sure what that is.

**Pull request merged**
