### PR TITLE
Recurring Donations tab UI now connects to addon

### LINKED ISSUE #5582: Recurring Donations tab UI should connect to addon
## User Story

As a donor, I want the Recurring Donations tab in the donor profile to connect to the addon so that I can view dynamic data, and make changes to my recurring donation subscriptions via the Donor Profile application.

## Details
All logic for modifying recurring donations, and querying recurring donations lives in the Recurring Donation addon, and is being introduced in these issues:

https://github.com/impress-org/give-recurring/issues/1025

This issue exists in GiveWP core to contain all rendering logic needed to present donors with the desired Recurring Donations tab UI.

## Additional Context
Figma Designs:
https://www.figma.com/file/BKr2K0XdDyRRoccJbJKRD7/Epic%3A-Donor-Profile?node-id=397%3A1743

## Acceptance Criteria

-   [x] Recurring Donations history is dynamically sourced from endpoints registered in Recurring Donations addon
-   [x] Recurring Donations can be managed via endpoints registered in Recurring Donations addon
-   [x] Recurring Donations can be cancelled via endpoints registered in Recurring Donations addon

### PR DESCRIPTION
**Pull request by henryholtgeerts**
**NOTE: This PR is dependent on Give Recurring endpoints introduced in this PR: https://github.com/impress-org/give-recurring/pull/1029**

Resolves #5582 

## Description
This PR introduces logic to connect Recurring Donations donor profile tab UI to endpoints introduced in the Recurring Donations addon. Specifically, the PR provides UI for viewing Recurring Donation history, updating recurring donation amounts and payment methods, and cancelling a recurring donation.

## Affects
This PR affects frontend rendering logic of the Recurring Donaitons tab in the Donor Profile app.

## Visuals

Screen Shot 2021-02-11 at 12 54 53 PM

Screen Shot 2021-02-11 at 12 59 18 PM

Screen Shot 2021-02-11 at 12 59 33 PM

Screen Shot 2021-02-11 at 2 54 13 PM

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by JasonTheAdams — CHANGES_REQUESTED** [review]
Everything worked great! I was able to update a subscription's card and amount on Stripe, and then cancel the subscription.

The only thing that didn't work properly was that the "Recurring Donations" tab didn't go away when I deactivated the plugin and threw a JS error.

**Comment by henryholtgeerts** [comment]
@JasonTheAdams Thanks for the review here -- I'll get that functionality sorted out and merge conflicts resolved this morning. 👍

**Comment by henryholtgeerts** [comment]
@JasonTheAdams I've added functionality to ensure that addon tabs are only registered on the frontend when they have also been registered on the backend, as well as cleared up merge conflicts. Take another quick look, and it should be good to goooo 👍 

Commits: https://github.com/impress-org/givewp/pull/5584/commits/c9161d7e6f6147a50153bfc14dc02c51e90ee591, https://github.com/impress-org/givewp/pull/5584/commits/7d1019565f05c1cb73991471d374aedb8f564b10

**Review by JasonTheAdams — APPROVED** [review]
Excellent work, @henryholtgeerts! I just tested again and the tabs are now appearing and disappearing appropriately based on the add-on activation. 👍

**Pull request merged**
