### PR TITLE
Refactor: remove input border on focus

### PR DESCRIPTION
**Pull request by JoshuaHungDinh**
Resolves [GIVE-637]

## Description
This PR removes the default border on all inputs for all templates while the input is selected. While selected we have another style that outlines these inputs with the primary color chosen on the form, if the original border is not removed it can still visible resulting in two colored borders. As seen below.
image

Reference: https://lw.slack.com/archives/C04SLRDD9CK/p1712671026808389

## Affects
styling of the VFB input fields on all templates

## Visuals

https://github.com/impress-org/givewp/assets/75056371/949d8eaa-2add-4894-9a48-a290b3936f66

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [x] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-637]: https://stellarwp.atlassian.net/browse/GIVE-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JoshuaHungDinh** [comment]
@pauloiankoski Nice catch, it looked it little to different to me while changing the border-color. Are you good with me making it transparent instead of removing it? It will solve the blinking issue. 7baec5c35e06cad831524dd8015976d30480c191

**Comment by pauloiankoski** [comment]
Well, that's not a technical question. @jdghinson would you mind to give your input here? In short, the question is: should we turn the current border "green" or transparent on focus. Additionally to it, the traditional box-shadow will also be displayed. Whatever **"The Boss"** answers, I'm cool with!

| Transparent | Colored |
| --- | --- |
| CleanShot 2024-04-15 at 17 38 34 | CleanShot 2024-04-15 at 17 40 06 |

**Comment by jdghinson** [comment]
@pauloiankoski The transparent looks cleaner

Cc: @JoshuaHungDinh

**Review by pauloiankoski — APPROVED** [review]

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
