### PR TITLE
Logs list tables legacy code is now removed

### LINKED ISSUE #5599: Legacy list tables used for displaying logs should be removed
## User Story

As a developer, I want the legacy list tables used for displaying the logs to be removed so that we keep the GiveWP core clean and tidy.

## Details
Since we are moving to the new and improved Logging system, there is no need for the legacy list table classes to be in the core anymore. 

## Acceptance Criteria

-   [x] Legacy list table classes removed from GiveWP core

### PR DESCRIPTION
**Pull request by alaca**
Resolves #5599

## Description
Since we are moving to the new and improved Logging system, there is no need for the legacy list table classes to be in the core anymore. This PR removes the legacy list table classes used for displaying logs.

## Affects

Legacy logs list tables. 

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions
The only way how we can test this is to check manually if all related logs list table files are removed, and the work done here in this PR is not producing any errors.

### CODE REVIEW

**Review by ravinderk — CHANGES_REQUESTED** [review]
@alaca This pull request is blocked but I found that a few points will be useful to improve this pull request:

1. I see a PHP notice in `debug.log`
```
[16-Feb-2021 18:02:28 UTC] PHP Notice:  wpdb::prepare was called <strong>incorrectly</strong>. Unsupported value type (array). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 4.8.2.) in /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/functions.php on line 5311
[16-Feb-2021 18:02:28 UTC] PHP Stack trace:
[16-Feb-2021 18:02:28 UTC] PHP   1. {main}() /Users/ravinderkumar/Local-Sites/give/app/public/wp-admin/admin-ajax.php:0
[16-Feb-2021 18:02:28 UTC] PHP   2. do_action() /Users/ravinderkumar/Local-Sites/give/app/public/wp-admin/admin-ajax.php:45
[16-Feb-2021 18:02:28 UTC] PHP   3. WP_Hook->do_action() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/plugin.php:484
[16-Feb-2021 18:02:28 UTC] PHP   4. WP_Hook->apply_filters() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp-hook.php:311
[16-Feb-2021 18:02:28 UTC] PHP   5. Give\Helpers\Hooks::Give\Helpers\{closure:/Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Helpers/Hooks.php:29-38}() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/class-wp-hook.php:287
[16-Feb-2021 18:02:28 UTC] PHP   6. call_user_func_array:{/Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Helpers/Hooks.php:37}() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Helpers/Hooks.php:37
[16-Feb-2021 18:02:28 UTC] PHP   7. Give\Framework\Migrations\MigrationsRunner->run() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Helpers/Hooks.php:37
[16-Feb-2021 18:02:28 UTC] PHP   8. Give\Log\Migrations\MigrateExistingLogs->run() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Framework/Migrations/MigrationsRunner.php:86
[16-Feb-2021 18:02:28 UTC] PHP   9. Give\Log\LogModel->save() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Log/Migrations/MigrateExistingLogs.php:100
[16-Feb-2021 18:02:28 UTC] PHP  10. Give\Log\LogRepository->updateLog() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Log/LogModel.php:210
[16-Feb-2021 18:02:28 UTC] PHP  11. Give\Framework\Database\DB::update() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Log/LogRepository.php:67
[16-Feb-2021 18:02:28 UTC] PHP  12. Give\Framework\Database\DB::__callStatic() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Log/LogRepository.php:67
[16-Feb-2021 18:02:28 UTC] PHP  13. Give\Framework\Database\DB::runQueryWithErrorChecking() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Framework/Database/DB.php:81
[16-Feb-2021 18:02:28 UTC] PHP  14. Give\Framework\Database\DB::Give\Framework\Database\{closure:/Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Framework/Database/DB.php:77-81}() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Framework/Database/DB.php:113
[16-Feb-2021 18:02:28 UTC] PHP  15. call_user_func_array:{/Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Framework/Database/DB.php:80}() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Framework/Database/DB.php:80
[16-Feb-2021 18:02:28 UTC] PHP  16. QM_DB->update() /Users/ravinderkumar/Local-Sites/give/app/public/wp-content/plugins/give/src/Framework/Database/DB.php:80
[16-Feb-2021 18:02:28 UTC] PHP  17. QM_DB->prepare() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/wp-db.php:2361
[16-Feb-2021 18:02:28 UTC] PHP  18. _doing_it_wrong() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/wp-db.php:1338
[16-Feb-2021 18:02:28 UTC] PHP  19. trigger_error() /Users/ravinderkumar/Local-Sites/give/app/public/wp-includes/functions.php:5311
```

2.  I can see that only tables listed on the system info page
image

3. I did not see the give_migrations table in the database
image

4. Did you remove this page in any other pull request

image

5. Can you confirm that you delete the log table after migrating data? because migration performs before the manual upgrade that means there will be not any log data for migration after the plugin update.

**Comment by alaca** [comment]
@ravinderk I'm wrapping up a PR that will resolve that issue. The scope of this PR is to remove legacy list tables.

**Comment by ravinderk** [comment]
> @ravinderk I'm wrapping up a PR that will resolve that issue. The scope of this PR is to remove legacy list tables.
Other commits in this pull request were confusing me. I will wait till the blocker clear then we can discuss it.

**Comment by alaca** [comment]
@ravinderk hmm... I see why you are confused. The second commit is not part of this PR, but it went through anyway. I'll revert that commit. Thanks for pointing this out.

**Review by ravinderk — APPROVED** [review]

**Pull request merged**
