### PR TITLE
fix: multi-step forms should support RTL styles

### LINKED ISSUE #5193: Multi-step forms should support right-to-left styles
## User Story

As a donor, I want that the multi-step template displays correctly when using RTL site language. 

## Details

The multi-step template does not display correctly with RTL styles.

image

## Steps to Reproduce

1. Change the site language to العربية المغربية in the settings at Settings > General
2. View a multistep form on the front end.
3. Click through to the payment gateway options.

## Acceptance Criteria

-   [ ] Multi-step template displays correctly when using RTL site language.

### PR DESCRIPTION
**Pull request by alaca**
Resolves #5193

## Description

This PR adds RTL support to the Multi-step template.

## Affects

 Multi-step form template.

## Visuals

| Before  | After |
| ------------- | ------------- |
| image  | image|

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

1. Change the site language to العربية المغربية in the settings at Settings > General
2. View a multistep form on the front end.
3. Click through to the payment gateway options.

### CODE REVIEW

**Comment by alaca** [comment]
@DevinWalker I have checked with my friend from Israel, everything is looking good to him, even the slide animations are OK.

**Comment by DevinWalker** [comment]
Hey @alaca I reviewed it again and am seeing some issues still. Please check out this video: https://www.loom.com/share/bf5ddbbb617342df947322ee702dcab0

**Comment by alaca** [comment]
@DevinWalker I think I fixed all now.

**Comment by DevinWalker** [comment]
This looks good now! Nice work 👏🏻

**Pull request merged**
