### PR TITLE
refactor: use PSR-4 autoloading for Reports

### LINKED ISSUE #4389: refactor: use PSR-4 autoloading for Reports
# Bug Report

## Developer Story
As a developer, I want to take leverage for PSR-4 to autoload to reduce unwanted calls for `require/include` functions.

discussion: https://givewp.slack.com/archives/C0FAGC83C/p1576611472090300

### PR DESCRIPTION
**Pull request by ravinderk**
## Description
This PR will resolve #4389 

directory structure
```
src/
+---Reports
¦      +---Report
¦           ¦    Campaigns.php
¦           ¦    Donors.php  
¦           ¦    Payments.php  
¦           ¦    Report.php  
¦      +---Views
¦           ¦    template.php
¦           ¦    widget-template.php  
¦      AdminView.php
¦      API.php
¦      Reports.php
```

## How Has This Been Tested?
Tested locally.
Note: run `composer dump-autoload` before testing.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@ravinderk I've been thinking about this. We really have two strategies for using autoloading, and I'd like to weigh both:

## 1. Custom autoloader
For this we would create a custom autoloader that uses the current file naming and directory structure. We would register the function with the `spl_autoload_register` PHP function.

**Pros:**
- We would not be splitting up the code.
- Shouldn't break existing code as classes would only be autoloaded if they're not explicitly included.

**Cons:**
- Namespaces aren't used in `includes`, so to start could be very confusing.
- It would not be at all clear which classes are autoloaded and which ones aren't.

## 2. PSR-4
In this method we would do what this PR is currently doing — make a separate `src/` directory that follows PSR-4 standards and progressively migrate existing classes over.

**Pros:**
- We can use composer to provide the autoloading
- Fresh start so classes can be structured as we please
- Opportunity to make refactors during the migration process (which doesn't have to be fast).

**Cons:**
- Code is effectively being split into legacy and new code, so two codebases emerge.
- 3rd party code that explicitly calls a Class would break once migrated as namespaces would be involved and there's a good chance classes may be broken apart and renamed.

-----

The former is more immediately practical, while the PSR-4 method is better long term. Fortunately, neither requires any sort of mass migration. I think I'm leaning towards PSR-4, but I wanted to explicitly call out both options and consider them carefully.

I would like your thoughts @ravinderk and @henryholtgeerts.

**Comment by henryholtgeerts** [comment]
@JasonTheAdams Thanks for writing this up, I agree that it's good we take a look at both options. While the safety of a custom autoloader is appealing, and I imagine we'll run into fewer headaches with that approach, I have to say I'm leaning toward the PSR-4 (second) option. As WordPress continues evolving as a platform, we need to be making sure that our code can track with it. This means making difficult choices (breaking some things) in order to get ourselves in the best possible place to add the features users will want. I personally feel that these kind of decisions will _only_ become harder to make the longer we put them off.

**Comment by kevinwhoffman** [comment]
I'll add my two cents based on my experience writing a custom autoloader in WPBR so that it would work with WordPress Coding Standards. I would not do it again. I'd go with PSR-4 and leverage Composer autloading.

**Comment by henryholtgeerts** [comment]
If folks are on board for the approach put forward in this PR I'm gonna suggest we go ahead and merge. Currently, it's blocking my progress implementing the new Reports API. @ravinderk @JasonTheAdams

**Pull request merged**
