### PR TITLE
Refactor: change the global settings link for the terms and conditions block and add it for name title prefixes on the name block 

### PR DESCRIPTION
**Pull request by glaubersilva**
## Description

The Title Prefixes options for the name block and the Label and Text options for the Terms and Conditions block have global settings that should be considered.

This PR implements a global settings link for the Name block and adds a few improvements for the Terms and Conditions block that already had it implemented.

This PR also implements a few minor changes in the settings page to display these content options all the time, this way we can ensure that they will not be hidden when the user accesses the settings page through the links from the visual form builder.

## Affects

The name block and the terms and conditions block.

## Visuals

**Name block:**

image

image

image

**Terms and Conditions block:** 

image

image

## Testing Instructions

1. Created a form with the visual form builder;
2. Add the Terms and Conditions Block and select the global options, the link below the select input now should inform which options can be edited in the global settings, and when acces it, the options should be visible;
3. In the name block enable the Show Name Title Prefix and notice that now you'll see a select input with the `"Global"` and `"Customize"` options, play around with these ones.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205920479946985
  - https://app.asana.com/0/0/1205076251265794

### CODE REVIEW

**Review by JoshuaHungDinh — CHANGES_REQUESTED** [review]
Nice! Only one small thing I noticed is that if you don't have a global setting set for the prefix on the name block - the input fields change size. 
Screen Shot 2023-11-08 at 8 11 20 AM

**Comment by glaubersilva** [comment]
@JoshuaHungDinh Thanks for the review. I realized that this bug already existed before and was happening when deleting all local options, like in the attached screenshot. It was fixed here: 6d8737adc23358f556eddc1c674137261a653c2f

image

**Review by JoshuaHungDinh — APPROVED** [review]
Oh nice! it's a funny quirk, thanks for fixing it!

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
