### PR TITLE
Fix: add translation to all gateways, form builder scripts, and fix text domain typo

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

Related: https://github.com/impress-org/givewp/issues/7035#issuecomment-1771434420

This sets all core gateways and form builder script handles for translation.

This also fixes a typo in the textdomain for various string from `'givewp'` to `'give'`

## Affects

Sets translation for following scripts:
- Form Builder Registrars (blocks)
- Form Builder App
- PayPal standard
- PayPal commerce
- Stripe Payment Element
- Test Offsite gateway

## Visuals

In Italiano

Screenshot 2023-10-19 at 4 17 29 PM

Screenshot 2023-10-19 at 4 24 55 PM

## Testing Instructions

**Form Builder**

Using a different language than english (ex: italiano has a lot of give support) view the form builder:

You should notice the form builder settings / labels are translated

**Gateways**

The easiest one to test would be PayPal Standard as there are no fields, just text.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205797235059704
  - https://app.asana.com/0/0/1205762247353628

### CODE REVIEW

**Review by glaubersilva — COMMENTED** [review]
@jonwaldstein All form builder is loading in the proper language, excellent! 

The only thing I noticed is that we don't have unreleased tags for these changes, maybe adding them only for the places where the `Language::setScriptTranslations($handle);` line was added would be enough as the other changes are just related to changing the wrong text-domain.

**Comment by glaubersilva** [comment]
@jonwaldstein Another interesting thing that I noticed here on this branch is that when you search in the codebase for `'givewp'` you still will find strings with the wrong text domain that are included in the `give.pot` file even so.

Let's use as a sample the following string: `'GiveWP 3.0 introduces an enhanced forms experience powered by the new Visual Donations Form Builder.'`

You can check here that it uses the `'givewp'` text domain: https://github.com/impress-org/givewp/blob/refactor/new-form-creation/src/Promotions/WelcomeBanner/resources/js/app/components/Sections/LeftContentSection.tsx#L50

However, this string is already included in the translation file from wp.org as you can check on the attached screenshot.

image

**Comment by jonwaldstein** [comment]
> @jonwaldstein Another interesting thing that I noticed here on this branch is that when you search in the codebase for `'givewp'` you still will find strings with the wrong text domain that are included in the `give.pot` file even so.

@glaubersilva Looks like I missed a few `givewp` text domains.  Resolved 90f87636

As far as the translations already being there - it's a bit confusing. I noticed one of those strings is coming from php using the `give` text domain and the other is coming from the welcome banner js file using the `givewp` text domain.  I'm not sure how that's possible 😕 

Screenshot 2023-10-23 at 2 53 03 PM


Screenshot 2023-10-23 at 2 58 06 PM


Screenshot 2023-10-23 at 2 50 08 PM

Screenshot 2023-10-23 at 2 58 52 PM

**Comment by jonwaldstein** [comment]
> Not sure, but maybe our GitHub action that generates the `give.pot` file is using the repository root folder ( `givewp` ) as the fallback in these cases where the text domain is different from the one present in the header of the plugin.

@glaubersilva I think you're on to something, it must be defaulting to the repo slug or root folder in some cases.  Although, it's still strange that we were only getting some `givewp` translatable strings but not all and that it still includes all `give` text domains.

**Comment by glaubersilva** [comment]
@jonwaldstein When we run the `wp i18n make-pot . languages/give.pot` locally, the string that I mentioned in one of my last replies (from the _assets/dist/js/welcome-banner.js_ file) is included only when the text domain is `'give'` and it isn't included when is `'givewp'` or any other text domain.

If you download [the zip file from the last release](https://github.com/impress-org/givewp/releases/tag/3.0.3) and check the `give.pot` file will notice that this string is not there as well. 

So, seems that these strings with the wrong text domain are being included in the `give.pot` file only when we deploy the plugin to the wp.org servers specifically.

**Comment by glaubersilva** [comment]
@jonwaldstein Just to complement my last comment, I downloaded the plugin zip directly from wp.org and checked the `give.pot` file and could see it is exactly the same as the GitHub releases page - without the string from the _assets/dist/js/welcome-banner.js_ file, so I have no idea how it can be displayed on [the translation site](https://translate.wordpress.org/projects/wp-plugins/give/stable/it/default/?filters%5Bterm%5D=GiveWP+3.0+introduces+an+enhanced+forms+experience+powered+by+the+new+Visual+Donations+Form+Builder.&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc).

**Comment by jonwaldstein** [comment]
@glaubersilva very interesting, I think we can conclude that we should be using the `give` text domain throughout our plugin. Technically, that is the correct text domain as defined in the [docs](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains):

>The text domain must match the slug of the plugin. If your plugin is a single file called my-plugin.php or it is contained in a folder called my-plugin the domain name must be my-plugin. If your plugin is hosted on wordpress.org it must be the slug portion of your plugin URL (wordpress.org/plugins/<slug>).

>Since WordPress 4.6 the Text Domain header is optional because it must be the same as the plugin slug. There is no harm in including it, but it is not required.

What you discovered is there is a slight discrepancy between the pot file generation and what's on the translation site. There are some instances where some strings are being added from the `givewp` domain - yet only _some_.

The `i18n make-pot` command _has_ options to include other/default text domains and our implementation is probably the culprit the discrepancy.  If we decide this is actually worth fixing - we should open a new issue for it - otherwise I think by simply using the correct text domain is sufficient for now.

For context - here is our pot file command for deployment to `wp.org` which refers to the `givewp` github repository.

Screenshot 2023-10-24 at 9 45 12 AM

**Comment by jonwaldstein** [comment]
> The only thing I noticed is that we don't have unreleased tags for these changes, maybe adding them only for the places where the `Language::setScriptTranslations($handle);` line was added would be enough as the other changes are just related to changing the wrong text-domain.

@glaubersilva resolved 3a631b28

**Comment by glaubersilva** [comment]
@jonwaldstein I agree that simply using the correct text domain is sufficient. 

I also believe that there is a problem on the wp.org side when they generate the `*.po` files for each language - based on our `give.pot` file. 

From my perspective, if a string doesn't exist in the source file, it couldn't be available for translation. But maybe they think differently and have something that scans the files directly to get strings that aren't included in the `*.pot` files of the plugins.

**Review by glaubersilva — APPROVED** [review]
@jonwaldstein Thanks for the update! It's ready for QA.

**Review by rickalday — APPROVED** [review]
Passed manual QA tests

**Pull request merged**
