### PR TITLE
feature: Tributes fields are now styled in the Sequoia form template

### LINKED ISSUE #4731: feature: Tributes addon fields should be styled in Sequoia form template
# Feature Request

## User Story
As an admin, I want the Sequoia form template to support styling for the Tributes addon fields so that donors have a cohesive donation experience, even when the Tributes addon is enabled.

## Details
The Tributes addon introduces specific fields which, when active, are styled incorrectly. These fields should be styled conistent with the rest of the Sequoia form template inputs. 

## Visuals
See Figma: https://www.figma.com/file/jaVXDA4wjQD9OqTi0l9KQe/Form-Themes?node-id=1882%3A44&viewport=-259%2C1586%2C0.5

## Related
https://github.com/impress-org/givewp/issues/4724

## Acceptance Criteria
- [x] Tributes addon fields are styled consitent with other Sequoia form template inputs
- [x] Rules for styling Tributes addon fields do not interfere with other fields appearance

### PR DESCRIPTION
**Pull request by henryholtgeerts**
## Description
Resolves #4731 
This PR introduces styling for fields associated with the Tributes addon, as they appear in the Sequoia form template.

Previously, the fields would appear using native browser styles. This PR ensures that fields associated with the Tributes addon are styled consistently with other inputs in the Sequoia form template.

## Affects
This PR only impacts Sequoia form template assets.

## What to test
Enable the Tributes addon. Do Tribute fields appear and operate as expected? Add Tribute types. Do they work as anticipated?

## Screenshots:
PRDemo

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
@henryholtgeerts I reviewed this PR and think it's a good first pass at the styles. Please review this video, list out the changes requested, and tackle them when you can! https://www.loom.com/share/095dad205251456f8dd365e2b45d5673

**Comment by henryholtgeerts** [comment]
Changes requested in @DevinWalker's video review:
- [ ] Match radio label font size/color to other labels
- [ ] Reposition tooltip notification tooltip
- [ ] Increase spacing around character count
- [ ] Resolve province/state label placement issue

**Comment by DevinWalker** [comment]
@henryholtgeerts I'm still seeing the tooltip being cut off:

**Comment by henryholtgeerts** [comment]
> @henryholtgeerts I'm still seeing the tooltip being cut off:
> 
> 

This has been addressed, by shifting the add/remove buttons so that they appear next to the label. Ref: https://github.com/impress-org/givewp/pull/4740/commits/d6fdcecd17e3ebf329578fba94b7476b9d513515

Screen Shot 2020-05-19 at 4 19 43 PM

**Pull request merged**
