### PR TITLE
Fix https://feedback.givewp.com/bug-reports/p/renewal-reminder-emails…

### PR DESCRIPTION
**Pull request by Genevieve-K**
…-do-not-trigger

Correct the SQL query to get the subscriptions for which we send a reminder email.

Resolves #

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by ravinderk** [comment]
@Genevieve-K I discussed dynamic SQL query with the team, which fetches the upcoming renewal subscription list, and there is the scope of simplifying SQL query.

We can exclude `bill_times` from SQL query because business logic keeps `expiration` date updated when a new renewal generates.

Let me know what you think.

**Current SQL query**
```sql
SELECT
	*
FROM
	givewp_give_subscriptions
WHERE
	1 = 1
	AND `status` = 'active'
	AND `expiration` >= '2022-07-28 00:00:00'
	AND `expiration` <= '2022-07-28 23:59:59'
	AND `bill_times` != 0
	AND(
		SELECT
			COUNT(ID)
		FROM
			givewp_posts
		WHERE
			`post_parent` = givewp_give_subscriptions. `parent_payment_id`
			OR `ID` = givewp_give_subscriptions. `parent_payment_id`) + 1 < `bill_times`
	ORDER BY
		id DESC
	LIMIT 0,
	99999;
```

Suggested SQL
```sql
SELECT
	*
FROM
	givewp_give_subscriptions As sub
WHERE
	sub.status = 'active'
	AND sub.expiration >= '2022-07-28 00:00:00'
	AND sub.expiration <= '2022-07-28 23:59:59'
ORDER BY
	sub.ID DESC;
```

**Comment by Genevieve-K** [comment]
I think this simple SQL query works. When bill_times is not zero, and when this number is reached, the subscription status becomes 'completed', and it's not necesseary to test if this number is not reached.

**Comment by ravinderk** [comment]
> I think this simple SQL query works. When bill_times is not zero, and when this number is reached, the subscription status becomes 'completed', and it's not necessary to test if this number is not reached.

@Genevieve-K Will you be able to make changes to this pull request?

**Comment by JasonTheAdams** [comment]
@ravinderk Looks like she updated it. Can you please review this again?

**Review by ravinderk — APPROVED** [review]
@Genevieve-K Look Good 💐

**Pull request merged**
