### PR TITLE
Fix: event tickets permission callback check

### PR DESCRIPTION
**Pull request by alaca**
Resolves [GIVE-982]

## Description

This PR updates the event ticket endpoint permission callback. 

## Affects

Event ticket endpoints

## Pre-review Checklist

-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-982]: https://stellarwp.atlassian.net/browse/GIVE-982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by alaca** [comment]
Closing in favor of https://github.com/impress-org/givewp/pull/7321

**Review by jonwaldstein — APPROVED** [review]
👍

**Comment by jonwaldstein** [comment]
Build for QA: https://github.com/impress-org/givewp/actions/runs/9943476320

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
