### PR TITLE
Fix: display errors on Multi-Step Forms

### LINKED ISSUE #6670: The Multi-step form template should display errors
## User Story

In some cases, the Multi-step form template experiences an error and scrolls to the top of the form but doesn't display or log the error code.

## Expected Behavior

Is expected that the error be displayed and the user get some feedback about what is happening. 

## Steps to Reproduce

1. Create a donation with a new user/email - after the donation, you'll get logged in with the new user automatically.
2. Now open a private tab in your browser and try to do a new donation with the same user/email create previously.
3. You'll notice that the form scrolls to the top, but no error is displayed. But if you check on the "Network" tab from the DevTools from the browser you'll be able to see the following error returning by the admin-ajax.php call: `The email address provided is already in use by a registered account on this site. Please log in and try again.`

## Visuals

image

## Acceptance Criteria

-   [x] Errors display on the multi-step template form
-   [x] Errors continue to display on other templates

### PR DESCRIPTION
**Pull request by glaubersilva**
Resolves #6670

## Description

The errors thrown by the backend weren't getting displayed on forms that use the Multi-step form template because the frontend function that handles the server errors was using elements that only exist on the classic and legacy form templates.

This PR changes it and makes the function also checks for an element that exists only on the Multi-step form template and appends the errors in the proper place when the backend sends them.

## Affects

Multi-Step Forms.

## Visuals

image

## Testing Instructions

1. Create a donation with a new user/email - after the donation, you'll get logged in with the new user automatically.
2. Now open a private tab in your browser and try to do a new donation with the same user/email create previously.
3. The form scrolls to the top and the following error is displayed: `The email address provided is already in use by a registered account on this site. Please log in and try again.`

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203767103828497

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@glaubersilva Can you please elaborate in the description as to what the problem was?

**Comment by glaubersilva** [comment]
@JasonTheAdams I copied and paste the issue description that this PR resolves into the description.

**Comment by JasonTheAdams** [comment]
@glaubersilva That wasn't what I meant. My bad. Hahah! I wasn't saying to restate what the problem was on a high level, but what it took to resolve the issue. Something like:

Issue: "When the user does X, Y happens instead of Z"
PR: "The reason Y was happening was because of this. By addressing this, Y will no longer happen and Z is correctly occurring."

Make sense?

**Comment by glaubersilva** [comment]
@JasonTheAdams Ok, I got it! Make sense. I already updated it with a better description. I'll remember that the next time. ;-)

**Review by JasonTheAdams — APPROVED** [review]
This is working for me. I'll pass this along to QA.

**Review by Benunc — APPROVED** [review]
Passes manual testing going to leave automated tests for the final release for this one.

**Pull request merged**
