### PR TITLE
New: Scaffold Donors admin page and endpoints - backend

### PR DESCRIPTION
**Pull request by alaca**
## Description

This PR scaffolds the new Donors page, and new endpoints for listing donors and deleting donors.

## Visuals

| GET admin/donors | GET admin/donors?search=387 | DELETE admin/donors/delete|
|---|---|---|
| image | image | image |

## Testing Instructions

Since there is no UI yet, I was testing this in Postman - see the screenshots above

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by LMNTL — CHANGES_REQUESTED** [review]
@alaca This looks great! I only have one small ask, which is that we send the donor creation date formatted to display on the front end. We do that here on the Donation Forms admin API:
https://github.com/impress-org/givewp/blob/feature/admin-ui-updates-donors-endpoints/src/DonationForms/Endpoints/ListForms.php#L142-L175

**Comment by alaca** [comment]
Yeah, looks like we are duplicating code for no good reason. Maybe we can add this function into some `date` helper class? @JasonTheAdams I know you like helper classes, any thoughts about this one?

**Comment by alaca** [comment]
As we continue to add more and more stuff into the src directory, we might consider grouping similar domains. For example, Admin UI domains like DonationForms, Donors, Donations, etc. might go into the Admin domain.

**Comment by alaca** [comment]
Resolved here 83b3dbb0. We can always refactor later.

**Comment by alaca** [comment]
@LMNTL let's wait for Jon to merge this [PR](https://github.com/impress-org/givewp/pull/6176#discussion_r828246660) and then we can merge this one. He is working on donor repositories, and some things will be different than what we have here.

**Comment by alaca** [comment]
@LMNTL this is ready for review.

**Review by LMNTL — APPROVED** [review]

**Pull request merged**
