### PR TITLE
Refactor: update gateway api `$gatewayData` param

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

Since our `PaymentGateway` is an abstract class, assigning the `$gatewayData` param to null in createSubscription() is forcing gateways to assign the param to null by default in order to be compatible. Gateways extending the PaymentGateway class can still assign the `$gatewayData` param as null for backwards compatibility but should not be forced to. This PR removes the assignment from the abstract class.

## Affects

Any gateways overloading the createSubscription class directly in their gateway class.  

## Visuals

N/A

## Testing Instructions

We will need to test recurring gateways using the gateway api.  In this PR I have updated the test gateways which can be uncommented in `RegisterPaymentGateways` and tested manually using a recurring form.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204449389516441

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@JasonTheAdams please review this one.
cc: @ravinderk

**Comment by JasonTheAdams** [comment]
@jonwaldstein So what's the benefit of preventing this from being null? Is the idea that it's reliably an array, albeit an empty one if no data is passed?

**Comment by jonwaldstein** [comment]
@JasonTheAdams that's the idea but also I don't want gateways to be forced to set the `$gatewayData` property as null.  If they don't set it to null right now, it will cause a fatal error because this is an abstract class:

Screenshot 2023-02-17 at 9 09 12 AM


Since we introduced the `$gatewayData` param _after_ some gateways were built, @ravinderk had to set that param to null for backwards compatibility, but as far as I can tell this would not be breaking change anymore.

**Comment by JasonTheAdams** [comment]
@jonwaldstein Ah, I see. The reason it doesn't throw an error is because the parameter itself isn't typed as an array and is therefore `mixed`. We would only need the optional null assignment if we had it cast as an array: `array $gatewayData = null`.

**Comment by jonwaldstein** [comment]
@JasonTheAdams we decided on continuing with this update right?

**Review by Benunc — APPROVED** [review]
This passes automated tests.

**Pull request merged**
