### PR TITLE
Fix: bulk actions not working in list table

### PR DESCRIPTION
**Pull request by pauloiankoski**
## Description

This pull request resolves an issue with bulk actions on list tables. Previously, the bulk actions were not functioning when the items on the page were changed. Upon investigation, it was found that the function responsible for updating references for the checkboxes was being cached using useCallback. However, this caching was unnecessary as none of the attributes were related to the nodes being added to the references. As a result, the new list of items was not being included in the references.

We are also refactoring the state for the selected action dropdown. Previously, we used a global variable to store the state between renders. To address this, we are lifting the state up to its parent component, ensuring that the state remains unchanged during renders.

## Affects

- List Tables

## Testing Instructions

- Access the list table for donation forms.
-  Delete a form by moving it to the trash.
-  Navigate to the trashed filter.
-  Attempt to perform a bulk delete operation.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205426266295650

### CODE REVIEW

**Review by alaca — APPROVED** [review]
Looks good :+1:

**Comment by JasonTheAdams** [comment]
@pauloiankoski Looks like this just need to go to QA?

**Comment by pauloiankoski** [comment]
> @pauloiankoski Looks like this just need to go to QA?

Exactly.

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
