### PR TITLE
Feature: add `$nodeNameCollision` property on `NameCollisionException`

### PR DESCRIPTION
**Pull request by jonwaldstein**
Related: https://github.com/impress-org/givewp-next-gen/pull/243

## Description

This adds a `$nodeNameCollision` property on `NameCollisionException` for flexibility in throwing exception messages.

## Affects

- The `NameCollisionException` exception

## Visuals

```
try {
            $form->schema();
        } catch (NameCollisionException $e) {
            return rest_ensure_response(
                new WP_Error(
                    400,
                    sprintf(
                        __("A field name with meta key '%s' already exists. Please try a new one.", 'give'),
                        $e->getNodeNameCollision()
                    )
                )
            );
        }
```

## Testing Instructions

This would have to be done programatically.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by JasonTheAdams — COMMENTED** [review]
@jonwaldstein Yeah! I was thinking this would be helpful! What do you think about also adding the two Nodes in question causing the collision? I'm not 100% sure we'd actually have that, but it would be nice.

**Comment by jonwaldstein** [comment]
> NameCollisionException

What do you mean like their indexes in the collection?  I don't think that would be possible without updating the collection.

**Comment by jonwaldstein** [comment]
> @jonwaldstein I mean the node objects — the one being collided with, and the one causing the collision. If it it's not possible it's really not a big deal.

Got it, I was able to add those 0dd368cb

**Review by JasonTheAdams — APPROVED** [review]
Very nice! 👍

**Pull request merged**
