### PR TITLE
Donor Dashboard no longer freezes up when attempting to manage Stripe ACH subscriptions

### PR DESCRIPTION
**Pull request by henryholtgeerts**
## Description

This PR provides a hotfix solution to an issue which caused the Donor Dashboard to freeze up, when attempting to enter new card information for subscriptions created using the Stripe + Plaid gateway. The PR includes some minor additional improvements to CardControl styling and addresses a React warning about a missing key prop on the SubscriptionRow component.

## Affects

This PR affects frontend rendering logic related to the Subscription Manager view of the Donor Dashboard.

## Visuals

N/A

## Testing Instructions
Test this pull request with: https://github.com/impress-org/give-recurring/pull/1071

1. Setup a Recurring donation using Stripe + Plaid
2. Click "Manage Subscription"
3. Check that you can update the amount, but not the payment method
4. Test subscriptions created using other supported gateways to ensure that everything still works as expected

- [ ] Donor able to update credit card  and donation amount of authorize.net and other stripe payment methods
- [ ] Donor able to update donation amount of GoCardless payment gateway.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@henryholtgeerts I tested this but it still seemed to not be working. There's a distinct possibility I may have not done something quite right in testing, so let's hop on a call tomorrow and test this together. 😃

**Comment by JasonTheAdams** [comment]
@ravinderk At some point I'd like to revive this leftover from Henry. This does fix the problem of the Donor Dashboard freezing for Plaid subscriptions, but updating the amount doesn't actually update the amount in Stripe. 🙁

**Comment by ravinderk** [comment]
@JasonTheAdams I notice this javascript error in the console tab when updating the subscription amount.

Image 2021-06-09 at 6 31 49 PM

I test this pull request for Authorize.net, GoCardless, and Stripe Plaid. It only works for the Authorize.net payment gateway.

**Comment by JasonTheAdams** [comment]
Got it. The Fee Recovery issues take precedence, but I'd like to get this wrapped up soon, as this is our last urgent item. I'd rather not release this knowing that it would cause serious problems with folks _thinking_ subscriptions are being updated when they're not.

**Comment by ravinderk** [comment]
@JasonTheAdams this pull request is working fine for Stripe, GoCardless,  Stirpe Plaid, and Authorize.net.

I was not able to test with PayPal pro. 
You can review this pull request.

**Review by JasonTheAdams — CHANGES_REQUESTED** [review]
@ravinderk Not sure if it's related to this PR or what, but I ran into a couple issues. One major and one minor:

**Major Issue:**
I made a Subscription using Plaid and it is not right in Stripe:
- The Payment Method (PM) was created and attached to the Customer (which shouldn't happen).
- The Subscription was created, but the PM was not attached to the Subscription. Instead the Subscription is set to use the Customer's default PM.

Here's how it should work:
- Payment Method is created and attached as the default PM for the Subscription
- PM is not attached to the Customer

**Minor Issue:**
Image 2021-07-20 at 4 20 48 PM

The Product generated has an invalid name and it doesn't change. Here's what I did:
1. Create a Subscription for $100/mo
2. Update the Subscription to $250/mo

Notice that the resulting Product name says $10.00 (instead of $100), and it's not updated to $250

**Comment by ravinderk** [comment]
@JasonTheAdams 

**Major Issue:** I added a fix in `give-recurring` got a plaid issue: https://github.com/impress-org/give-recurring/pull/1073
**Minor Issue:** This is work like that currently, only plan changes, product name remain same. we can open new issue for this.

**Review by JasonTheAdams — APPROVED** [review]
Thanks, @ravinderk! I confirmed this is working with Stripe (Card & Plaid), GoCardless, and Authorize.net. 👍

**Pull request merged**
