### PR TITLE
The current state of the Donation Form fields are now preserved when the payment method changes

### LINKED ISSUE #5490: Already filled out Donation form fields, First Name and the Last Name, should not clear on payment method change
## User Story

As a donor, I don't want to see the First Name, Last Name fields erased after I change the payment method. In most cases, the payment method is selected after I already filled in my data.

## Details

Donation form fields First Name and the Last Name among other PG fields, are loaded via ajax every time the payment method changes which is causing the "clearing" of already filled in fields. 

**This only happens with Legacy Form Template.** 

## Expected Behavior

Already filled out Donation form fields, First Name and the Last Name, should not clear on payment method change

## Steps to Reproduce

1. Create a Donation form which uses the Legacy Form Template
2. Enable multiple PG
3. Navigate to the Donation Form page and fill in all the Donation Form fields
4. Change the payment method
5. First Name and the Last Name fields are cleared

## Visuals

deepin-screen-recorder_Select area_20201208171808

## Acceptance Criteria

-   [ ] First Name and the Last Name Donation Form fields are not cleared on payment gateway change.

### PR DESCRIPTION
**Pull request by alaca**
Resolves #5490 

## Description

This PR solves the issue where the Donation form fields First Name, Last Name and the Email were cleared after the payment method is changed. The issue is solved by storing the state for each field in the browser's memory and restoring the state when the payment method is changed. 

**Note:** this issue only happens when the Legacy Form template is used. 

## Affects

Donation Form fields:
- First Name
- Last Name
- Email

## Visuals

deepin-screen-recorder_Select area_20201209100917

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions
1. Create a Donation form which uses the Legacy Form Template
2. Enable multiple PG
3. Navigate to the Donation Form page and fill in all the Donation Form fields
4. Change the payment method
5. First Name, Last Name and the Email field should have preserved values when the payment method changes

### CODE REVIEW

**Review by ravinderk — CHANGES_REQUESTED** [review]
@alaca Can you confirm that this logic works fine when two donation forms with legacy form template exist on the same page.

**Comment by alaca** [comment]
@ravinderk no, it doesn't work with multiple Donation forms on the same page. I'll update the code. Thanks for bringing that up!

**Review by ravinderk — APPROVED** [review]
@alaca This PR is working fine for me.

@JasonTheAdams  We need you feedback on state management code  placement. Code placement for basic state look good to me. Do you have suggestion?

**Review by JasonTheAdams — APPROVED** [review]
It's simple enough and gets the job done! 👍

**Comment by izanamiah** [comment]
Hi the problem occurs again in multi step donation form. I'm using the givewp 2.13.4

**Pull request merged**
