### PR TITLE
Refactor: Collapse panel bodies by default

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves [GIVE-808]

## Description

This PR collapses by default the multiple panel bodies of the Billing Address inspector controls, with the exception of the first.

## Affects

This change is isolated to the Billing Address inspector settings.

## Testing Instructions

Add a Billing Address block to the donation form and view the inspector settings.

## Visuals

image

[GIVE-808]: https://stellarwp.atlassian.net/browse/GIVE-808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@kjohnson please fill out the rest of the PR description with affects and testing instructions, as well as adding brackets to the Jira ticket.

**Comment by kjohnson** [comment]
Build for QA: https://github.com/impress-org/givewp/actions/runs/10182210536

**Comment by kjohnson** [comment]
Build failed, re-try: https://github.com/impress-org/givewp/actions/runs/10182210536

**Comment by kjohnson** [comment]
Build failed on re-try. I'll circle back after investigation.

**Review by rickalday — COMMENTED** [review]
Passed manual QA tests

**Pull request merged**
