### PR TITLE
Fix: Check for mod_rewrite on Form init

### LINKED ISSUE #6738: The Form class should check for mod_rewrite before attempting to use it
## User Story

As a WordPress site, I want to be sure I can use mod_rewrite before I invoke functions for it.

## Details
When a WordPress site runs on a server that doesn't support mod_rewrite, calling functions that expect mod_rewrite can result in errors.

An example of this is the init() function of the Form class, which adds and saves rewrite rules without checking for mod_rewrite support.

Ex: A WordPress site using a non-default configuration such as Bedrock, which has WordPress core in a separate directory than the site root `index.php`, and which has `open_basedir` restrictions enabled, will produce an `open_basedir` error when WP core function [save_mod_rewrite_rules()](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/misc.php#L249-L289) attempts to check whether a `file_exists()` and `is_writable()` if [get_home_path()](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/file.php#L100-L121) fails to assemble a full server path to an `.htaccess` file due to the absence of the non-standard WP core directory in the path to site root `index.php`.

## Expected Behavior

The Form class should have checked for mod_rewrite.

## Steps to Reproduce

1. For a WordPress site running on nginx with a [Bedrock](https://roots.io/bedrock/) configuration and open_basedir restrictions above the site root directory, enable the following three plugins:
- Give
- Give Form Field Manager
- Give PDF Receipts
2. Load a page
3. Check the logs for open_basedir errors
4. To confirm, place a breakpoint at line 1875 of wp-includes/class-wp-rewrite.php (at function `save_mod_rewrite_rules()`) and debug

## System Information

<details><summary>Details</summary>

</details>

## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

### PR DESCRIPTION
**Pull request by houblon**
For when mod_rewrite isn’t supported.

Resolves #6738

## Description

This PR adds logic to check for mod_rewrite to the Form class init() function.

## Affects

This shouldn’t affect any functionality, except to prevent possible errors.

## Testing Instructions

Test using the steps in #6738 and confirm there are open_basedir errors.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by JoshuaHungDinh** [comment]
Hey @houblon, thank you for taking the time to submit a PR and write a corresponding issue. We should have this reviewed and tested soon. Cheers!

**Comment by jonwaldstein** [comment]
@ravinderk can you review this please.

**Comment by ravinderk** [comment]
@houblon Thank you for your contribution 🌷 

As I can see, WordPress checks for `mod_rewrite` before saving new permalink rules. We do not need to handle this separately in our plugin. The WordPress core handles it.

https://github.com/WordPress/WordPress/blob/8a1849216046d1e7dda1d05bd29ac5819ac99ee4/wp-admin/includes/misc.php#L281

https://github.com/WordPress/WordPress/blob/8a1849216046d1e7dda1d05bd29ac5819ac99ee4/wp-admin/includes/misc.php#L17

If you disagree, then I have a few questions which help me to understand the problem:

1. Are you facing this issue on the Live website?
2. Are WordPress pretty permalinks working on your setup?
3. Did you see any error or suggestion on the `Site Health (/wp-admin/site-health.php)` page related to setup/permalink?
4. Who suggested you this fix? Host service provider or others?

**Comment by houblon** [comment]
Hi, @ravinderk , and thanks very much for looking at this.

To answer your questions:
- I’m facing this issue on the Live website.
- Pretty permalinks are working on my setup.
- I don’t see any error or suggestion on the `Site Health (/wp-admin/site-health.php)` page related to setup/permalink.
- Nobody suggested this fix to me. I discovered by debugging that the changes in the pull request fixed my issue.

The issue is very specific, perhaps an edge case, but one which nonetheless affects my site, and any other site that might use Bedrock and Give.

You are absolutely correct that WordPress checks for `mod_rewrite`, and in fact I found the fix by debugging the very `misc.php` file to which you refer.

The problem is as described in [issue #6738](https://github.com/impress-org/givewp/issues/6738):

“A WordPress site using a non-default configuration such as Bedrock, which has WordPress core in a separate directory than the site root `index.php`, and which has `open_basedir` restrictions enabled, will produce an `open_basedir` error when WP core function [save_mod_rewrite_rules()](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/misc.php#L249-L289) attempts to check whether a file_exists() and is_writable() if [get_home_path()](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/file.php#L100-L121) fails to assemble a full server path to an `.htaccess` file due to the absence of the non-standard WP core directory in the path to site root `index.php`.”

My site uses a Bedrock setup. It’s hosted on Kinsta, which has `open_basedir` restrictions enabled. This combination results in the following error when pages are loaded:

`PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/.htaccess) is not within the allowed path(s)`

You’ll need a similar setup to reproduce this.

My reasoning in submitting this pull request was that by adding `got_mod_rewrite()` to the plugin, it avoids the error that occurs in WordPress core since core gets an inaccurate value for `get_home_path()` with Bedrock config.

However, it’s also been four months since the last time I debugged this, and something has changed (I’m not sure what) so that my pull request no longer solves the issue. It is now the case that an update to the plugin “Give - PDF Receipts” does solve it. In that plugin’s file `give-pdf-receipts.php` there's a function `give_pdf_register_post_type()` which calls `flush_rewrite_rules()` without first checking whether that’s possible. This function call leads to the aforementioned `save_mod_rewrite_rules()` where the problem occurs. Wrapping `flush_rewrite_rules()` with `got_mod_rewrite()` solves the problem.

Since Give - PDF Receipts isn’t a public repo, I’ll reach out to Give support through my account, unless you suggest a different way.

Thanks again for look over this pull request.

**Pull request closed without merging**
