### PR TITLE
feature: develop new reports screen ui

### LINKED ISSUE #4330: Develop New Reports Screen UI
# Epic User Story

As an admin, I want to view reports that are more informative, filterable, and flexible so that my fundraising efforts can be better optimized and actionable. As well, when I log in to WordPress I want a better dashboard widget that shows me the most relevant data and is filterable based on dates but won't slow down my wp-admin main dashboard load times.

## Appetite

1 month

## Solution

A new screen is built in react to replace our current reports screen that displays data based on the data that can be easily queried from our current data structure.

## Rabbit Holes

- This is the MVP approach so spending too much time trying to optimize how data is pulled from the database or creating an API may not be necessary. As long as data can be pulled and queried and data is flowing into the reports within an acceptable load time, that'll suffice.
- Creating charts and graphs that can be reused by other add-ons or third-party developers or an entire API for creating them. Just create base line data graphs.
- Spending too much time on backwards compatibility. Ensure that "legacy" reports can be viewed in a simply and efficient fashion.

## No-gos
- Do not develop front-end embeds (but keep in mind that's what we'll want to do eventually.)
- Data doesn't have to be exportable right now, although you'll see an option in the concepts.
- Don't build all the tabs in the concepts right now, just focus on the dashboard widget and main reports screen (containing all the most valuable reports that are possible given our current db structure.)

## Designs

See figma here: https://www.figma.com/file/w38WexhmfOkcXRvFOTNgcO/GiveWP-Updated-Admin-Screens?node-id=0%3A10592

Note that all these screens are not in the MVP scope. Only the dashboard widget and basic reports screen.

The most valuable and easiest reports to query should be in the MVP.

### PR DESCRIPTION
**Pull request by henryholtgeerts**
## Description
Resolves #4330 
Build new React-based Reports UI for GiveWP admin. 

## How Has This Been Tested?
Tested locally and throws no errors in browser console. Passed PHPUnit tests.

## Screenshots (jpeg or gifs if applicable):
screencapture-give-local-wp-admin-edit-php-2020-03-02-14_39_22

## Types of changes
Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by henryholtgeerts** [comment]
Reports UI Progress as of 12/16/19 (Screencast)
[https://www.loom.com/share/aa689ef9eb19463e9d948465fb726510](https://www.loom.com/share/aa689ef9eb19463e9d948465fb726510)

**Comment by JasonTheAdams** [comment]
Great overview, @henryholtgeerts! Progress is looking good!

**Comment by henryholtgeerts** [comment]
Reports Update 12/20/19 (screencast)
[https://www.loom.com/share/76c870d6e66e4444a211250bdc73c9fa](https://www.loom.com/share/76c870d6e66e4444a211250bdc73c9fa)

**Comment by henryholtgeerts** [comment]
**Call Summary 12/23/19**
Henry, Devin, Ravinder discussed progress on reports page MVP. Determined next steps include:

- Mocking up dashboard widget
- Building mini-card component 
- Evaluating current Stats API to determine what data we can already access easily
- Implementing period selector (see airbnb calendar and other plugin report pages for reference)

**Comment by henryholtgeerts** [comment]
**Stats API/Reports Evaluation**
Supported:

Payments (by gateway):
- Completed payments
- Pending/failed payments
- Total payments
- Total donated (in $)

Forms (by form, can be queried by period or all time):
- Total number of donations
- Total income (in $)
- avg number of donations
- avg donations (in $)

Totals (by period or all time)
- Income (in $)
- Number of donations
- Estimated income (in $)
- Estimated number of donations

**Comment by henryholtgeerts** [comment]
### Charts/Lists to include in MVP Overview Page:

**Doughnut Chart: Form Performance**
Total amounts for top 5 charts during period

**Bar Chart: Payment Statuses**
Total number of completed, abandoned, pending, and failed payments

**Pie Chart: Payment Methods**
Total number of payments per payment gateway

**List: Recent Donations**
List of recent donations, and donation status

**List: Top Donors**
List of top donors for period

### Charts/Lists to include in Admin Dashboard Widget

**Line: Total donations over time**
Total donation amounts over period

**Mini Chart: Amount Raised**
Site-wide total amount raised for period

**Mini Chart: Number of Donors**
Site-wide total number of donors for period

**Comment by henryholtgeerts** [comment]
**Call Summary: 12/30/19**
_On call: Devin, Jason, and Henry_
- Reviewed frontend progress
- Reiterated need for switching between legacy reports and new reports screen
- Decided to use existing Give route in the WP REST APi
- Decided to build HOC to handle REST API logic and feed data into Charts
- Discussed options for implementing new Reports API on the backend
- Discussed need for hour-long cache on data queries
- Decided to require authentication to access REST Endpoints for now
- Discussed changes to Legend component to prevent directly manipulating DOM
- Discussed future plans for exporting data and embedding charts with the block editor

**Comment by henryholtgeerts** [comment]
**Call Summary: 1/17/20**
_On Call: Henry, Jason_
- Discussed issues with/alternatives for Donations vs Income chart
- Jason suggested use of ChartJS built-in 'cartesian time' axis: https://www.chartjs.org/docs/latest/axes/cartesian/time.html
- Discussed implementation of 'All Time' button for period selection
- Considered need for getting Form Performance for a given period (vs all time, as it is currently)
- Reviewed code, noted classes that could be cleaned up
- Confirmed plans to use Give_Cache to cache queries by their date and endpoint for up to an hour

**Comment by henryholtgeerts** [comment]
**Call Summary: 1/21/20**
_On call: Henry, Devin_
- Discussed replacing Donations vs vs Income with line chart depicting income over time, which each datapoint displaying # of donations when hovered (on the tooltip)
- Finalized metrics to visualize (list will be commented on the Reports epic)
- Agreed to wait on developing Top Locations logic until other endpoints / MVP is built
- Discussed opening UI/UX tweaks umbrella issue
- Discussed changes to Form Performance endpoing (queryable by date and returns income instead of number of donations)
- Made plans for next call to be end of day Thursday, to check-in ahead of testing Reports with larger data sets

**Pull request merged**
