### PR TITLE
Feat: display Paypal payment method type as per admin setting

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

@JasonTheAdams As we discussed, debit and credit card smart buttons will not display if hosted fields are available, and vice versa.

## Testing
Setting
image

Paypal smart buttons
image

Paypal smart buttons with hosted fields
image

- `Debit or Credit Card` smart button should not display if hosted fields are available.
- `Debit or Credit Card` smart button should display if hosted fields are unavailable.

## Affects

This pull request affects Paypal payment options in the donation form.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204621958568591
  - https://app.asana.com/0/0/1205168401819752

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
Hey @ravinderk!

I feel like we may have gotten our wires crossed. Yes, the card field should only show up when hosted fields are not present. But we still need the "Smart Buttons", "Hosted Fields", and "Both" (with Both as the default) buttons in the admin. PayPal wants users to be able to select one Smart Buttons or Hosted Fields if they want.

The trick, of course, will be that Smart Buttons should display if Hosted Fields are not supported — either the account doesn't support them, or the donation is recurring.

Make sense?

**Comment by JasonTheAdams** [comment]
@ravinderk I just made a recording an ran into some strangeness.

First, I realized that we're defining the SDK parameters in two places:
1. PayPalCommerceGateway class
2. ScriptLoader class

The `PaypalCommerceGateway::formSettings()` method was added for Next Gen and is used to pass data from the gateway to the front-end when loading. Let's use that method in `ScriptLoader` so we're not doing this in two places.

Next, I had to add `enable-funding` for venmo, as it was not showing up. In fact, it doesn't even look like the Venmo setting in the PayPal Donation settings is even doing anything.

Finally, I could not get the credit card smart button to show up at all. I even removed it from the `disable-funding` and added it to `enabled-funding`, but nothing I did got it to show up. I tested with both a sandbox and live account.

Please let me know if you have any questions. I admit this was a bit discouraging to discover as I was working, as it seems like some pretty glaring issues.

**Comment by ravinderk** [comment]
@JasonTheAdams I implemented settings for the payment field type.

image


> I feel like we may have gotten our wires crossed. Yes, the card field should only show up when hosted fields are not present. But we still need the "Smart Buttons", "Hosted Fields", and "Both" (with Both as the default) buttons in the admin. PayPal wants users to be able to select one Smart Buttons or Hosted Fields if they want.

> The trick, of course, will be that Smart Buttons should display if Hosted Fields are not supported — either the account doesn't support them, or the donation is recurring.

> Make sense?

I added setting and It applies as you suggested.

> The PaypalCommerceGateway::formSettings() method was added for Next Gen and is used to pass data from the gateway to the front-end when loading. Let's use that method in ScriptLoader so we're not doing this in two places.

How do you want me to use it? Should it be compatible with the next-gen plugin, meaning it should work with or without it?

> Next, I had to add enable-funding for venmo, as it was not showing up. In fact, it doesn't even look like the Venmo setting in the PayPal Donation settings is even doing anything.

The Venmo button displays under a few conditions. [Read More](https://developer.paypal.com/docs/checkout/pay-with-venmo/)
I can not test this because it is US based feature. We should contact the PayPal Commerce team if it needs to be displayed with the sandbox and live account. I am sure that we implement it correctly, and Paypal controls the rest.

> Finally, I could not get the credit card smart button to show up at all. I even removed it from the disable-funding and added it to enabled-funding, but nothing I did got it to show up. I tested with both a sandbox and live account. It looks like paypal.HostedFields.isEligible() is always true, even when recurring is enabled. I'm guessing this removed the button. But when recurring is enabled, the hosted fields only work for US and AU — the other PPCP countries will need the smart buttons to display. To keep it simple, we can display the credit card button when recurring is enabled.

I found that PayPal also disables hosted fields if we disable the `card` payment field, which means we can display hosted fields and the card smart button or hide both. I display smart buttons when hosted fields are unavailable regardless of setting.

> Please let me know if you have any questions. I admit this was a bit discouraging to discover as I was working, as it seems like some pretty glaring issues.

I agree with this, but because of the varying nature of the smart buttons, it isn't easy to test, and a few times, I assume that it works fine because of straightforward implementation.
Pardon me, and Let's make it to core together 💪

**Comment by ravinderk** [comment]
@JasonTheAdams I updated the payment field type options:

image

I am planning to option issue to implement account type when onboarding.

Can you review this pull request?

**Comment by JasonTheAdams** [comment]
@ravinderk I'm getting an error in the donation form. I tried reconnecting my account, saving the PayPal settings, and I'm still getting this error:
image

**Comment by ravinderk** [comment]
@JasonTheAdams I can see that the first error is coming from the currency switcher add-on. Did you test after disabling the currency switcher add-on?

**Review by JasonTheAdams — APPROVED** [review]
Good work, @ravinderk! I'm _pretty sure_ this is working fine. I ran into [a strange issue](https://lw.slack.com/archives/C04UT6UPERW/p1690588856181489) when trying to test recurring donations using the smart buttons, but it doesn't seem related to this PR. It seems like it's not even a bug on our end at all.

Also, I realized that it's the Next Gen plugin that was breaking this for me. I tested it with Recurring and Currency Switcher and it worked just fine. We're definitely going to need to update the PayPal Donations integration in Next Gen after this, also to support the new features we're adding now.

**Review by rickalday — APPROVED** [review]
Passed manual QA tests

**Pull request merged**
