### PR TITLE
Add PayPal Donations Payment Gateway

### LINKED ISSUE #4886: Epic: PayPal Commerce
# Pitch

This pitch has been defined in a [Google Doc](https://docs.google.com/document/d/1wD-Cyy4X6fDRe-tW4Ey3wSglcbYRAZQyDvjIEqVarRE/edit#heading=h.9g67mdj3rh9m).

The scope of this Epic is the integration of the new PayPal Commerce Platform payment gateway within GiveWP core.

## Note

This is the integration of the PayPal Commerce Platform API, but it will be called the **PayPal Checkout** gateway in GiveWP.

## Appetite

6 weeks, though we should finish as close to July 31 as possible

### PR DESCRIPTION
**Pull request by JasonTheAdams**
Resolves #4886 

## Description

This PR merges the entire PayPal Commerce epic and is intended to be **the last** thing merged when all epic issues have been closed. No funny business. I'm watching you.

Threats aside, the intention is to be able to test the Epic and provide feedback. Please see the testing instructions below.

### Terminology

There are a few terms helpful to know.

**PPCP & Express Accounts**
PPCP accounts are accounts that have been authorized by PayPal to have people supply credit cards directly from their website. This requires extra authorization and is limited to 28 countries (mostly Americas and Europe). All other countries must use Express accounts. These accounts are authorized to accept payments, but not accept credit cards directly. In short, PPCP accounts can use Advanced Fields (see below) and Smart Buttons, while Express accounts can only use Smart Buttons.

**Smart Buttons**
When viewing the form, you'll see some large, bold colored buttons. These are [Smart Buttons](https://developer.paypal.com/docs/checkout/#try-the-buttons). Smart Buttons are clever buttons that PayPal provides for processing payments, and are tightly regulated by PayPal. Most buttons take the donor off-site, briefly, except the "Debit or Credit Card" button, but is a special (but hand-cuffed) button that only shows up when Advanced Fields aren't present.

**Advanced Fields**
When using a PPCP account, the fields below "or pay with card" line are Advanced Fields. These are fields that feel like perfectly normal form fields. They do special things on the Seller's account, and provide the simplest donor experience. They can only be used on PPCP accounts, however.

## Pre-review Checklist

-   [ ] All epic issues are resolved and closed
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

In general:
- After pulling the branch, run `composer install && npm i && npm run dev` on your CLI
- Make sure, when connecting accounts and making donations, you are in test mode.
- Use `4242 4242 4242 4242` as your test credit card number with a future date expiration and any 3-digit CVC number

### Express account donation
1. Go to the GiveWP General settings and set the country to Columbia (note: Do not change the currency to Colombian Peso as it's not supported by PayPal, just use USD or Euro)
2. Go to the PayPal Donations connection screen
3. Connect using the following credentials:
    - Email: sb-siizv2863201@business.example.com
    - Pass: &;9jU+Y5
4. Make a donation and subscription using Smart Buttons

### PPCP US account donation
1. Go to the GiveWP General settings and set the country to United States
2. Go to the PayPal Donations connection screen
3. Connect using the following credentials:
    - Email: sb-kttpp2709027@business.example.com
    - Pass: 3lU<#qG.
4. Make a donation and subscription using the Smart Buttons
5. Make a donation and subscription using the CC fields

### PPCP French account donation
1. Go to the GiveWP General settings and set the country to France
2. Go to the PayPal Donations connection screen
3. Connect using the following credentials:
    - Email: sb-i8fua2524394@business.example.com
    - Pass: Qf>a^9CM
4. Make a donation and subscription using the Smart Buttons
5. Make a donation using the CC fields
6. The CC fields should not show up when recurring is enabled (only US and AU are supported at this time)

### Refunding
1. Go to a donation made with with this gateway in the admin
2. Change the status to Refunded
3. Save the donation
4. Click on the transaction id and see if the payment has been refunded
image

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@DevinWalker @kevinwhoffman This is ready for testing. Please refer to the instructions on here and use the following checklist: https://docs.google.com/spreadsheets/d/1Og4TA-uFwJVSX5lI2FSQ7mFmLfgJt09k2VaeiWafWf0/edit?usp=sharing

**Comment by kevinwhoffman** [comment]
@JasonTheAdams I'm happy to start testing PayPal. To clarify, I should also have the latest from `impress-org/give-recurring/epic/paypal-commerce/integration` installed while testing this PR, correct?

**Comment by JasonTheAdams** [comment]
@kevinwhoffman That is correct! You'll want to have this branch checked out on GiveWP, and that epic branch checked out for give-recurring.

**Comment by kevinwhoffman** [comment]
@ravinderk @JasonTheAdams I began the testing process and successfully connected to PayPal using the `PPCP US account ` credentials provided above. However, I'm seeing console errors when the form first loads and more errors when I get to the payment step. I'm providing a screencast of these errors below:

[📼 Screencast of PayPal Donations Console Errors](https://cln.sh/XKXr4F)

@ravinderk Can you please complete a self review by following the testing instructions with your console open and let me know if you see the same errors? If so, take the steps to correct the errors and I will pick up testing again tomorrow.

**Comment by kevinwhoffman** [comment]
@DevinWalker with the JS errors addressed in https://github.com/impress-org/givewp/pull/5254, we can continue testing today.

**Comment by DevinWalker** [comment]
@JasonTheAdams @ravinderk I'm getting an error on PHP 5.6: https://www.loom.com/share/f55b9280925747f0af91a7dee295d4d5

**Comment by JasonTheAdams** [comment]
@DevinWalker Oops, there was a trailing comma on a function parameter, probably just a typo (but is ignored in PHP 7.x). This is fixed. Please pull and keep on rocking. 🎸

**Comment by DevinWalker** [comment]
I just tested again and was able to connect after a strange user experience getting connected but then ran into issues with testing the donation: https://www.loom.com/share/a3bff04b42234645b9666bc161b6d643

**Comment by JasonTheAdams** [comment]
@DevinWalker To have all the PayPal settings under one roof you'll need to have this PR checkout out on PayPal Pro: https://github.com/impress-org/give-paypal-pro/pull/84

**Comment by JasonTheAdams** [comment]
@DevinWalker The whole having to save to get the country is what's described in this issue we need to come to a conclusion on: https://github.com/impress-org/givewp/issues/5140 — I'm happy to hop on a call.

**Comment by JasonTheAdams** [comment]
@DevinWalker I have never seen that currency error before, and I've never had to set a currency when using the Colombian account. What add-ons do you have activated?

**Comment by ravinderk** [comment]
@DevinWalker This payment gateway is not compatible with the currency switcher, so please disable that if active. You are seeing currency notice because maybe you did not configure payment gateway for that currency, so I think this notice coming from currency switcher.

cc: @JasonTheAdams

**Comment by JasonTheAdams** [comment]
@ravinderk I got a SQL dump of @DevinWalker's local and there seem to be a couple of oddities.

### Currency Switcher

Something is wrong with the Currency Switcher, which I believe you mentioned in Slack. When I disable the plugin the GOP error goes away. If I disable it for just the form, the error goes away as well. If there's incompatibility we need to figure out how we want to handle it. Please see if you can figure out where the issue lies and document your findings here.

### Order generation issue

Even when I turn off Currency Switcher I'm unable to process a donation via Smart Buttons. When I click on the Smart Button it looks like it's loading PayPal, but then goes back to the form with no errors. In the console there are multiple errors regarding an order id not being provided:

image

Thank you! I will send you the SQL dump on Slack.

**Comment by JasonTheAdams** [comment]
After further digging, I found that the issue was that the currency was set to COP which is unsupported by PayPal:
image

PayPal was responding with the following when attempting to create an order:
```
Array
(
    [name] => UNPROCESSABLE_ENTITY
    [details] => Array
        (
            [0] => Array
                (
                    [location] => body
                    [issue] => CURRENCY_NOT_SUPPORTED
                    [description] => Currency code is not currently supported. Please refer https://developer.paypal.com/docs/integration/direct/rest/currency-codes/ for list of supported currency codes.
                )

        )

    [message] => The requested action could not be performed, semantically incorrect, or failed business validation.
    [debug_id] => 8758649ba287e
    [links] => Array
        (
            [0] => Array
                (
                    [href] => https://developer.paypal.com/docs/api/orders/v2/#error-CURRENCY_NOT_SUPPORTED
                    [rel] => information_link
                    [method] => GET
                )

        )

)
```

I'm wondering if we should check for the `UNPROCESSABLE_ENTITY` name and then pass back the `$error['details'][0]['description']`? I'm just afraid of something sensitive being in there since this is the the error for any time PayPal has an issue with a request. Otherwise, the only way for someone to know why the error failed is to check the log.

I'm open to any thoughts on this @kevinwhoffman and @DevinWalker for a good error UX.

**Comment by DevinWalker** [comment]
## ALPHA TESTING FINDINGS

This is nice work and good progress here. I got through the testing process much better now. I do have a number of improvement suggestions and questions. Please review the videos (apologies as they are rather long) and compile the items for discussion. A few things I found I commented on within the Testing spreadsheet to raise the points further.

### Video 1: US PPCP

https://www.loom.com/share/e75d944e07844e38abb29c555324a704

## Video 2: FR PPCP

https://www.loom.com/share/54319cb7777a4923915cb1a5a5e4742b

### Video 3: Express Columbian Account

https://www.loom.com/share/9e4fc3416fa74485a8b3c5bec72ab6d3

Please let me know if you have any questions along the way! Good work, we're almost there! 👍

**Comment by JasonTheAdams** [comment]
Excellent notes, @DevinWalker! Thanks so much for that! I'm going through the videos now and taking notes on everything.

**Comment by JasonTheAdams** [comment]
@kevinwhoffman I've finished processing through @DevinWalker's notes and have everything in [Canny](https://givewp.canny.io/qa-paypal-donations). Once you finish your review, if you believe this is in a state where we're confident PayPal Donations will make it in to the release — as Devin signed off on — then we can merge this into `develop`. Note that we don't have to clear Canny before doing so. We only need to delay this if you find something that puts into question whether this is clear for the upcoming release or any specific items that should be resolved before opening it for testing.

Last note, I merged the branch and kept the changelog items form this in Unreleased, as I assumed you'd want to include them in alpha.2. Please let me know if this is incorrect.

**Review by kevinwhoffman — APPROVED** [review]
@JasonTheAdams I completed the following which is reflected in my testing spreadsheet:

- US PCPP one-time donation via smart button
- US PCPP one-time donation via hosted fields
- Viewed US PCPP donation in PayPal
- Refunded US PCPP donation in GiveWP and confirmed in PayPal

Note that I have not tested Recurring Donations.

Given our timeline and the fact that Devin has done a more thorough review, I think we should merge this into `develop` and begin alpha testing to get more eyes on this experience.

> Last note, I merged the branch and kept the changelog items form this in Unreleased, as I assumed you'd want to include them in alpha.2. Please let me know if this is incorrect.

This is correct.

**Comment by kevinwhoffman** [comment]
@DevinWalker This is just waiting on your testing of currency switcher, and then it can be merged and packaged as an alpha release.

**Comment by JasonTheAdams** [comment]
@ravinderk Great job! This is merged! We can now start merging other PayPal changes into `develop` for the rest of the QA process.

**Pull request merged**
