### PR TITLE
Update cs setup

### PR DESCRIPTION
**Pull request by jrfnl**
## Description

Improve the setup to ensure code consistency and PHP cross-version compatibility.

####  Composer: fix CS setup

This commit does three things:
1. Remove the `phpcompatibility/php-compatibility` dependency.
    This is not *your* dependency, but a dependency of the `phpcompatibility/phpcompatibility-wp` package, so it will be pulled in automatically.
    Not including it here prevents issues with conflicting version constraints.
2. Update the `dealerdirect/phpcodesniffer-composer-installer` package.
    The new `0.7` version is compatible with the upcoming release of Composer 2.0.
    As Composer treats minors below `1.0` as majors, this version is not used automatically, the version constraint needs to be adjusted to benefit from this.
3. Remove the `post-install-cmd`, `post-update-cmd` and `install-codestandards` scripts.
    None of these are necessary. The DealerDirect Composer PHPCS plugin will automatically run after each install/update and set the `installed_paths` for PHPCS correctly.

**Note:** it can even be argued that the `squizlabs/php_codesniffer` dependency should be removed as, again, that is not strictly _your_ dependency, but a dependency of WordPressCS and PHPCompatibilityWP, but as it doesn't have a version constraint which could conflict, I've left that for now.

#### PHPCS: rename the configuration file

PHPCS will automatically pick up on configuration files using one of the following names: `.phpcs.xml`, `phpcs.xml`, `.phpcs.xml.dist`, `phpcs.xml.dist`, in that order.

Using a `dist` file extension allows for devs to locally overrule the config file with a non-dist version of the file, for instance to test some new rules.

Includes:
* Removing references to the file name in scripts. PHPCS will pick up on the config file automatically, so no need to pass the `--standard=...` argument.
* Adjusting the `.gitignore` file to ignore the local overload files.
* Adjusting the `.gitattributes` file to exclude the `phpcs.xml.dist` file from distribution packages.

#### PHPCS: update the ruleset

* While the `PHPCompatibilityWP` package was defined as a dependency, it wasn't used so far as it wasn't included in the ruleset.
    Fixed now. Includes setting the target PHP versions for the code to be compatibility with as "PHP 5.6 and higher", as per the `Required PHP` header for the plugin.
* Move the command-line arguments found in various places to the configuration file to make all PHPCS runs consistent.
    - Add `/includes/libraries/` and `/tests/` as exclude patterns as per the `travis.sh` script.
    - Only scan PHP files. There is other tooling in place for non-PHP files, like eslint.
    - Use colourized output as per the script in `package.json`.
* Add some more configuration:
    - Run in parallel for faster results.
    - Set a `basepath` for cleaner output.
* Clean up the scripts in the `package.json` and `travis.sh` files.

Note: I realize that the script in `travis.sh` is commented out, but at least it's correct now for when it will be uncommented/turned back on.

## Testing Instructions

* Run `composer install`
* Run `vendor/bin/phpcs --report=full,summary,source` and get a drink of whatever is your preferred drink when you've had a shock.
* The current output should be similar to `A TOTAL OF 3840 ERRORS AND 2991 WARNINGS WERE FOUND IN 447 FILES`, though my counts will probably be a bit higher than when it is run via the Composer installed dependencies (I run on the dev installs of these tools)
* Test the commands in `package.json`- `lint:php` and `lint:php:fix` - in whatever way you'd run them normally.

Notes:
1. While the ruleset is (and was) setup to enforce short arrays, 100% of arrays are in long form, which accounts for ~ 1/3 of all issues reported.
2. While a lot of these issues should be fixed, a number of them should be handled by better ruleset configuration instead.
3. While not (yet) reported by the last release of PHPCompatibility, the next version will start reporting on PHP 8.0 related issues. The following issues will start to pop up and should be addressed:
---
<details>
  <summary>Issue details</summary>

```
FILE: includes\admin\payments\payments-history.php
------------------------------------------------------------------------------------------------------------------------------------------------------------
 135 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $post_id is optional, while parameter $context
     |         | is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: includes\class-give-donor.php
------------------------------------------------------------------------------------------------------------------------------------------------------------
 1089 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $meta_key is optional, while parameter
      |         | $meta_value is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
 1105 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $meta_key is optional, while parameter
      |         | $meta_value is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: includes\deprecated\deprecated-functions.php
------------------------------------------------------------------------------------------------------------------------------------------------------------
 488 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $form_id is optional, while parameter
     |         | $payment_id is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
 549 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $give_form_id is optional, while parameter
     |         | $payment_id is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
 780 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $form_id is optional, while parameter $amount
     |         | is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: includes\formatting.php
------------------------------------------------------------------------------------------------------------------------------------------------------------
 794 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $nonce is optional, while parameter $form_id
     |         | is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: includes\forms\functions.php
------------------------------------------------------------------------------------------------------------------------------------------------------------
 378 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $give_form_id is optional, while parameter
     |         | $payment_id is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
 471 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $give_form_id is optional, while parameter
     |         | $amount is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
 493 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $form_id is optional, while parameter $amount
     |         | is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: includes\payments\functions.php
------------------------------------------------------------------------------------------------------------------------------------------------------------
 585 | WARNING | Declaring a required parameter after an optional one is deprecated since PHP 8.0. Parameter $day is optional, while parameter $month_num
     |         | is required. (PHPCompatibility.FunctionDeclarations.RemovedOptionalBeforeRequiredParam.Deprecated)
------------------------------------------------------------------------------------------------------------------------------------------------------------
```
</details>

---

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@ravinderk Please review this when you have a free moment. If there are changes that should be applied to the Boilerplate or any other add-ons, please make a note.

**Review by ravinderk — APPROVED** [review]

**Comment by ravinderk** [comment]
@jrfnl thank you for your contribution.

**Comment by jrfnl** [comment]
Glad to help get this fixed.

Just checking - you did notice the fold-out section at the bottom of the issue description with details on PHP 8 related issues ?

**Comment by ravinderk** [comment]
@jrfnl I noticed them and I will create a separate issue to fix them.

**Comment by ravinderk** [comment]
@jrfnl I created an issue to handle it: https://github.com/impress-org/givewp/issues/5372

**Pull request merged**
