### PR TITLE
Donor Profile UI is polished

### LINKED ISSUE #5628: Donor Profile UI should be polished
## User Story

As a donor, I want the donor profile UI to be polished so that I have a consistent, clean donation service experience.

## Details

While functionality for Donor Profiles has been introduced, and styles are largely consistent, some minor polish needs to be added to ensure that the entire donor profile experience is professional and user ready.

## Additional Context

Figma designs: https://www.figma.com/file/BKr2K0XdDyRRoccJbJKRD7/Epic%3A-Donor-Profile?node-id=397%3A1743

## Acceptance Criteria

-   [x] All buttons use accent color
-   [x] All links should use accent color
-   [x] Cancel subscription window copy and styles are clean
-   [x] iframe loaded state is improved
-   [x] Text controls shoud use consistent padding
-   [x] Inner circle of radio controls should be centered
-   [x] Payment method controls should use accent color for focus state
-   [x] Currency Control should use accent color for focus state
-   [x] Users should see notice when attempting to view a donor profile via a WP acct with no associated donor
-   [x] Donation tables should respect "Sequential Numbering" option
-   [x] Save profile button should indicate "saving" state (similar to subscription management)
-   [x] "Enter" key should work to submit login form
-   [x] "Logout" menu item should be positioned at bottom of menu
-   [x] Logout action should require user confirmation
-   [x] Giving Stats should include decimal seperators (correct currency formatting)
-   [x] Pagination should work correctly/consistently
-   [x] "Dashboard" menu item should be highlighted on load
-   [x] Highlighted menu items should have white background
-   [x] Margins/spacing should be made consistent with Figma designs, see video review for more: https://www.loom.com/share/5cc7809395fd45b9827a37d994259aea

### PR DESCRIPTION
**Pull request by henryholtgeerts**
Resolves #5628 

## Description

This PR introduces various minor improvements to the Donor Profile UI. In addition to making colors and margins and various components more consistent with the original Figma designs, the PR introduces some functionality to improve UX (improved loading states, notice when logged in without a Donor account, etc).

## Affects

This PR primarily affects the frontend rendering logic related to Donor Profiles.

## Visuals

Screen Shot 2021-02-25 at 11 33 33 AM

## Pre-review Checklist
-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

For a complete list of which items to test for and check, see the acceptance criteria in the linked issue.

### CODE REVIEW

**Comment by kjohnson** [comment]
@henryholtgeerts I'm getting a console error: `Uncaught Error: Cannot find module 'axios'`. Along those lines, I'm not seeing a dependency for axios in `package.json`.

**Comment by henryholtgeerts** [comment]
@kjohnson Strange, not sure how some packages got removed from package.json on the epic branch, but I've added them back here: https://github.com/impress-org/givewp/pull/5648/commits/c38d0e2303e4d9f265d761ef8b7fccaff7e8008e

**Comment by kjohnson** [comment]
I'm seeing new behavior where the container loads at the left side of the viewport, then moves into place.

My screenshot caught an in-between:

Screenshot_2021-02-25 Donor Profile – WordPress

**Comment by henryholtgeerts** [comment]
@kjohnson Thanks for taking a look at this -- great catch. The positioning was working fine for me, because the theme was already ensuring that blocks were positioned relative. I've resolved the issue here: https://github.com/impress-org/givewp/pull/5648/commits/64839c56ea96cb531ff046d3c3c4606929ce126d

**Comment by JasonTheAdams** [comment]
@henryholtgeerts Wrapping it in the relative div had an affect I'm sure you didn't expect. It seems like the Twenty Twenty-One theme does a bunch of styling to unsuspecting divs.
### Without div wrapper:
image

### With div wrapper:
image

**Comment by JasonTheAdams** [comment]
I fixed the issue by applying `max-width: 100%` to the wrapping div. That did the trick, but I suggest you take a look as well in case there's a better solution. I'm doing this because I don't want to hold up this whole PR on that.

**Review by JasonTheAdams — APPROVED** [review]
Great work, @henryholtgeerts! Lots of excellent polish, here. Looking sharp! ✨

**Pull request merged**
