### PR TITLE
Refactor: Update step 3 of the Setup Guide

### PR DESCRIPTION
**Pull request by pauloiankoski**
Resolves [GIVE-972]
Depends on https://github.com/impress-org/givewp/pull/7457

## Description
This pull request updates the Step 3 of the Setup Guide. There are two states for it:
1. When no add-ons have been selected in the wizard, a generic row is shown pointing to all add-ons page.
2. When some add-ons have been selected in the wizard, only those will be shown.

Additionally, the step 3 now have a direct access to the _Active License_ form.

## Affects
Step 3: Setup Guide

## Visuals
dev givewp local_wp-admin_edit php_post_type=give_forms page=give-setup (8)
_When no add-ons were selected_

dev givewp local_wp-admin_edit php_post_type=give_forms page=give-setup (7)
_When add-ons were selected_

https://github.com/user-attachments/assets/fda1b010-e3c0-4db0-9b3e-25d30fb42afb
_Activating License_

## Testing Instructions
1. In a new install, complete the wizard without selecting any add-ons in the last step. At the end, you’ll be redirected to the Setup Guide, and state 1 should be presented.
2. Navigate back to the wizard or access `?page=give-onboarding-wizard`, then in the last step select some add-ons. Once in the Setup Guide page, they must now be presented.
3. Click on the _Activate your license_ link to open the dialog modal with the activation form. Add the license key and hit the submit button. The license must be activated. You can visit the _Licenses_ page at `Donations > Settings > Licenses` and confirm that your license has been correctly activated.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-972]: https://stellarwp.atlassian.net/browse/GIVE-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
Looks amazing! I think @jdghinson and I at one point agreed that the "GiveWP Add-ons" card should just always be visible. If they have other add-ons selected, then it's at the bottom. No reason to not make it easy for folks to find all of our add-ons.

**Review by glaubersilva — APPROVED** [review]
@pauloiankoski Great work! Ready to QA.

**Comment by pauloiankoski** [comment]
@JasonTheAdams Let's just confirm that then. I had asked @jdghinson about that and the answer I got was to only show that item when having no add-ons selected.

**Comment by jdghinson** [comment]
@JasonTheAdams I forgot to include that in the final handoff so I missed it.

@pauloiankoski You can have the add-ons in both screens

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
