### PR TITLE
Donor Profile Verify Email now supports reCAPTCHA

### LINKED ISSUE #5637: Donor Profiles should support recaptcha
## User Story

As an admin, I want Donor Profiles to support recaptcha verification when enabled so that I can prevent spam attacks via the Donor Profiles interface.

## Details

Currently, enabling recaptcha for GiveWP does not affect the Donor Profile login experience. The Donor Profile login should respect the admin's setting and behave in parity with existing donation management page login forms.

## Additional Context

This issue was originall surfaced in this comment: https://github.com/impress-org/givewp/issues/5628#issuecomment-783974582

## Acceptance Criteria

-   [x] Donor Profile supports recaptcha verification on the Verify Email form.
-   [x] Recaptcha verification is enabled/disabled according to GiveWP setting

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #5637

## Description

Validates a Google reCAPTCHA token on the VerifyEmail route, if reCAPTCHA is enabled for Access Control.

## Affects

- Adds `react-google-recaptcha` as a dependency.
- Fixes event handling in the Verify Email form.
- Passes a reCAPTCHA token to the `verifyEmailWithAPI` utility.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

In Settings -> General -> Access Control

- Enable Access Control
- Enable reCAPTCHA 
- Set reCAPTCHA Site Key
- Set reCAPTCHA Secret Key

With an unauthenticated session...
With the Donor Profile block on the page...

- Input an email address belonging to a WP User.
- Click the "Verify Email" button

### CODE REVIEW

**Review by henryholtgeerts — CHANGES_REQUESTED** [review]
Tested out locally, works really well -- with one change requested: if Recaptcha is enabled (Ie recaptchaKey is defined on the window) ensure that the recaptcha challenge has been completed before allowing the request to be made. Currently, users can submit a verify email request without completing the recaptcha challenge, which causes the request to fail and the UI to get stuck on the loading state.

Otherwise, great work! This all looks good to me. 👍

**Comment by kjohnson** [comment]
@henryholtgeerts it should be returning a validation error from the route if the reCAPTCHA isn't completed, which should show an error message on the form. I'm leaning on the route validation to keep the client slim, since we have to verify on the server anyway.

I'll look to see if there is an issue with the error message.

**Comment by kjohnson** [comment]
@henryholtgeerts this brings up a good point - the app doesn't handle validation errors thrown by the REST API. Looking at the code, we are returning error messages under `response.data.message`, while the REST API validation is returning error messages under `response.message`.

**Comment by kjohnson** [comment]
Looks like Axios is throwing an exception that isn't being caught.

**Comment by kjohnson** [comment]
@henryholtgeerts since refactoring the donor profile routes to match the REST API response shape would be excessive here, I updated the reCAPTCHA validation to match the donor profile routes.

Now a failed reCAPTCHA validation will return a generic message, so as not to tip off potential abusers.

**Review by henryholtgeerts — APPROVED** [review]
Tested locally, this looks good to me! Nice work.

**Pull request merged**
