### PR TITLE
Refactor: replace the Editor component (react-quill) with WP ClassicEditor component ( TinyMCE) 

### PR DESCRIPTION
**Pull request by glaubersilva**
Resolves https://stellarwp.atlassian.net/jira/software/c/projects/GIVE/boards/382?selectedIssue=GIVE-55 

## Description

This PR adds a new `ClassicEditor` component (extracted from the Custom PDF Builder modal for v3 forms from the PDF Receipts addon) that uses the TinyMCE editor shipped with WordPress under the hood and uses it in all places where the Editor component (that uses the react-quill package under the hood) was being used.

This PR also mounts this new component in the global window object to allow the addons also use this same component preventing code duplication.

## Affects

- Email message content in the email settings of V3 forms.
- The Agreement Text content in the Terms & Consent block of V3 forms.
- The Donation Instructions in the Offline Donations Gateway.

## Visuals

image

image

image

## Testing Instructions

1. Create or edit a v3 form;
2. Go to the email settings and play around with the email message content of the email notifications.
3. Add a Terms & Consent block, go to the Agreement Text content, and play around with the editor options. 
4. Go to the Offline Donations gateway settings and play around with the donation instructions content of the gateway.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205606769216041

### CODE REVIEW

**Review by pauloiankoski — APPROVED** [review]
Hey @glaubersilva! Nice work here. 👏🏻 

Important note: we also need to replace the editor on the Terms & Consent block and on the Consent block in FFM. Besides that, please evaluate if we can safely remove the old editor and all the Quill dependencies so we standardize this editor as our default one.

**Comment by glaubersilva** [comment]
@pauloiankoski Thanks! I did implement your suggestions and now this is ready for re-review.

**Review by pauloiankoski — APPROVED** [review]
Great addition! 👏🏻

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
