### PR TITLE
Fix: conditionally set gateway id default value

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

This conditionally checks sets the donation form's default value for `gatewayId` - making sure it's only set if not empty. 

## Affects

The donation form

## Visuals

Screenshot 2023-10-12 at 1 34 57 PM

## Testing Instructions

- Step through a multi step form without a default gateway
- You should be able to get to the end but not actually submit.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@jonwaldstein Mind generating a zip from this, putting it on the environment @mathetos was having the issue with, and seeing if it fixes it?

**Comment by jonwaldstein** [comment]
> @jonwaldstein Mind generating a zip from this, putting it on the environment @mathetos was having the issue with, and seeing if it fixes it?

Confirmed it fixes the issue on staging site:

Screenshot 2023-10-12 at 1 57 44 PM

I think this situation will be rare but still good to avoid.

**Comment by JasonTheAdams** [comment]
Nice! Any theories as to _why_ it's happening in the first place? I wonder if what's happening is that the default gateway is set to some gateway that's not active anymore. 🤔

**Comment by jonwaldstein** [comment]
This is the gateway configuration on that install.  Not sure why, but there are no v3 gateways enabled.  It's possible the migration didn't go through for this instance or the gateway config was setup statically like this.

Screenshot 2023-10-12 at 2 09 01 PM

Screenshot 2023-10-12 at 2 09 06 PM

**Comment by JasonTheAdams** [comment]
Interesting. So this fix sets the default as null, which the form takes to mean that it should just set enable whatever the first gateway is?

**Comment by jonwaldstein** [comment]
> Interesting. So this fix sets the default as null, which the form takes to mean that it should just set enable whatever the first gateway is?

Yes, just making sure we're only setting the default gateway when it's defined (or else the empty string gets put through default values and validation route).  The default gateway would only be _undefined_ if _no_ v3 gateways were enabled.

**Review by JasonTheAdams — APPROVED** [review]
Strange situation, but at least this fails more gracefully, allowing the donor to proceed.

**Pull request merged**
