### PR TITLE
Fix: Handle boolean values from `get_theme_support` in MultiFormGoal/ProgressBar

### LINKED ISSUE #6851: Error message: Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, bool given
## Summary

Unable to edit pages through Wordpress dashboard due to plugin error

## Details

```
An error of type E_ERROR was caused in line 106 of the file /var/www/html/oursite.com/app/public/content/plugins/give/src/MultiFormGoals/ProgressBar/Block.php. Error message: Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, bool given in /var/www/html/oursite.com/app/public/content/plugins/give/src/MultiFormGoals/ProgressBar/Block.php:106
Stack trace:
#0 /var/www/html/oursite.com/app/public/content/plugins/give/src/MultiFormGoals/ProgressBar/Block.php(106): array_shift()
#1 [internal function]: Give\MultiFormGoals\ProgressBar\Block->localizeAssets()
#2 /var/www/html/oursite.com/app/public/content/plugins/give/src/Helpers/Hooks.php(43): call_user_func_array()
#3 /var/www/html/oursite.com/app/public/wordpress/wp-includes/class-wp-hook.php(308): Give\Helpers\Hooks::Give\Helpers\{closure}()
#4 /var/www/html/oursite.com/app/public/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /var/www/html/oursite.com/app/public/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/html/oursite.com/app/public/wordpress/wp-admin/edit-form-blocks.php(272): do_action()
#7 /var/www/html/oursite.com/app/public/wordpress/wp-admin/post.php(187): require('...')
#8 {main}
  thrown
```

## System Information

WordPress version 6.2.2
Active theme: Team Hope (version 0.1)
Current plugin: Give - Donation Plugin (version 2.29.2)
PHP version 8.2.7

## Temporary fix

.. plugins/give/src/MultiFormGoals/ProgressBar/Blocks.php::106
CHANGED LINE 106 FROM
    'editorColorPalette' => $editorColorPalette ? array_shift($editorColorPalette) : $defaultColorPalette,
CHANGE LINE 106 TO
    'editorColorPalette' => is_array($editorColorPalette) ? array_shift($editorColorPalette) : $defaultColorPalette,

### PR DESCRIPTION
**Pull request by JoshuaHungDinh**
Resolves #6851

## Description
It is possible that 'get_theme_support' returns a false value if explicitly defined in a theme. 

If $editorColorPalette is a boolean (either true or false), attempting to use array_shift() on it will result in a type error.

## Affects

Multi Form Goal Progress Bar

## Testing Instructions

- Switch to PHP 8+
- Use a theme that defines add_theme_support('editor-color-palette', false);
- Add the MultiFormGoal block

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205176602055571

### CODE REVIEW

**Review by jonwaldstein — APPROVED** [review]
@JoshuaHungDinh thanks for adding this, please send to QA

**Comment by kjohnson** [comment]
Following up - has this change been through QA?

**Comment by JoshuaHungDinh** [comment]
@kjohnson, Yes but another cooldown item regarding a different issue with the multiformgoal block is keeping QA from being able to manually test it. I checked it out and believe its in regards to react-select in the block editor. We can add react and react-dom to the webpack externals which will fix it. I was hesitant though as I was not sure if it would introduce any breaking changes and so the item is sitting in a deferred status at the moment. Here a link to the additional issue :  https://feedback.givewp.com/bug-reports/p/forms-cannot-be-selected-in-multi-form-goal-block

**Comment by kjohnson** [comment]
@JoshuaHungDinh that works for me! And of course now I see the Asana link in the PR description - whoops!

Adding a link to the QA comment for cross-reference: https://app.asana.com/0/0/1205176602055571/1205204829262848/f

**Comment by joeczucha** [comment]
Just checking whether this was ever merged, as were holding off updating the plugin until there is a fix in place. Thanks

**Comment by JoshuaHungDinh** [comment]
@joeczucha, thanks for checking in. We have another developer integrating some changes to id filtering for this particular block in order for it to properly work. We expect to have those updates soon & once merged this PR can follow

I will be sure to reach out once this issue has been resolved.

**Review by rickalday — APPROVED** [review]
Passed manual QA tests

**Pull request merged**
