### PR TITLE
Hotfix: sync donation status with stripe payment

### LINKED ISSUE #6329: Stripe donations using 3D Secure Authentication remain in "Pending" status in GiveWP, but are complete in Stripe
## Details
When a donation is made via Stripe using 3D Secure Authentication, the donation remains in "pending" status, while showing completely on Stripe's side.

## Step to reproduce
Steps to reproduce: https://somup.com/c3e00PTMJ7
- Make a one-time donation using a test card number that requires authentication (for example, 4000002760003184) to force this flow.
- Complete the authentication on the Stripe confirmation page
- Check donation status on the website and Stripe payment

## Acceptance Criteria
- [ ] Donation set to complete when showing completed on Stripe side.

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves #6329 

## Description

I find out that we were not setting donation transaction IDs for this reason donation is not discoverable when processing webhook.

**Updates**:
After discussion with @JasonTheAdams I add a migration who adds transaction id to donation.
This migration will add transaction id to donations who pass the following conditions:
- Donation status is other than "publish".
- Donation created after 20 March 2020. We released GiveWP 2.19.0 on 25th March 2022,
   So donations created after or on the following date may not have transaction id.
   release information https://github.com/impress-org/givewp/releases/tag/2.19.0
- Donation process with Stripe payment method.
- Donation has a note with "Stripe Charge/Payment Intent ID" prefix.
- Donation does not have transaction id.

In my result single donation was processed in approximately 8.5ms.
image

## Testing Instructions

You should not able to reproduce issue when following steps given in the issue description.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by kjohnson — APPROVED** [review]
Ok, that makes sense. Good find.

**Comment by JasonTheAdams** [comment]
So does this mean, even with this patch, there are existing donations that don't have the transaction ID set which can have issues?

**Comment by ravinderk** [comment]
> So does this mean, even with this patch, there are existing donations that don't have the transaction ID set which can have issues?

@JasonTheAdams yes. it will fix issue only for upcoming donations.

**Comment by JasonTheAdams** [comment]
Is there anything we can do for donations that are in the gap?

**Comment by ravinderk** [comment]
> Is there anything we can do for donations that are in the gap?

Yes. Luckily we are storing Stripe payment intent id in donation notes.
We can add a migration to save payment intent id from note to donation meta.

**Review by Benunc — APPROVED** [review]
1. The transaction ID for 3dS (as well as the fact that they were being marked as pending) has been resolved
1. One Time donations work.
1. Recurring donations work.
1. Things tangentially related to all the translations fixes have been tested (visual inspection of the JS-generated elements, local translation with Loco Translate)
1. Issues related to logging of credit card data in the event of PayPal errors have been resolved. (note that I can’t replicate the error, so I can’t confirm that the card number is not logged. I just looked for regressions around that issue, and found none)

**Comment by JasonTheAdams** [comment]
@kjohnson @ravinderk @Benunc  This PR introduced a regression that all three of us missed, which is bad. It broke Stripe Checkout.

So how did it break? Well, as part of the PR the `handlePaymentIntentStatus` method signature changed — significantly. When it was changed it wasn't checked all the places the method is used. This broke places (i.e. Checkout) that attempted to use the method the old way. We have a few important takeaways from this:

1. When changing a method signature carefully check all usages.
2. We should incorporate [PHPStan](https://phpstan.org/) into our CI/CD to catch obvious bugs like this.
3. Stripe is our most important gateway. We should do everything we can to get automated testing into our QA processes (i.e. Ghost Inspector).
4. In line with 3, we need to test carefully whenever we touch Stripe.

**Comment by Benunc** [comment]
> 3\. We should do everything we can to get automated testing into our QA processes (i.e. Ghost Inspector).

I am all for that @JasonTheAdams. Let's talk through the best ways to automate Stripe-connected test payments on a call soon.

**Pull request merged**
