### PR TITLE
Renewal payments are now included in reports.

### LINKED ISSUE #5398: Renewals should appear in the donation report
## User Story

As a [type of user], I want [some goal] so that [some reason].

## Steps to Reproduce

1. Go to...
2. Select...
3. Scroll down to...
4. View error

## System Information

<details><summary>Details</summary>

</details>

## Acceptance Criteria

-   [ ] Renewal donations are included in reports data.
-   [ ] Renewal donations are filtered by `mode` (live or test).

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #5398

## Description

Renewal payments weren't being included in the results of the `Give_Payments_Query` because they do not include a value for the `_give_payment_mode` meta.

Ideally, the renewal system would be updated to include this meta key/value, but that would require a database update to correct historical data.

Instead, I opted to add an additional query for renewal payments and combine the results.

## Affects

Updates the shared `Endpoint::getPayments()` to combine one-time and renewal payments.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changelog updated
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

1. Create a new donation form
1. Create a donation
1. Manually create a renewal
1. See Donations > Reports

Note: Due to #5399, you may need to manually adjust the start date to include first day's payments (for a fresh install).

The renewal payment is now listed in the reports.

### CODE REVIEW

**Comment by kevinwhoffman** [comment]
> Ideally, the renewal system would be updated to include this meta key/value, but that would require a database update to correct historical data. Instead, I opted to add an additional query for renewal payments and combine the results.

@kjohnson @JasonTheAdams  I understand the rationale behind the solution in this PR, but I want to check on a couple of things before merge...

Given that:

- We are migrating revenue from all donations (including renewals) to the revenue table in 2.9.0
- AND We bet on a pitch that will update the reporting screen to be powered by the revenue table in the next cycle.

I have the following questions:

- Would renewal payments be automatically included once reporting is powered by the revenue table, thus solving the problem in which renewal payments are currently excluded?
- Should we be distinguishing whether revenue is one-time ore recurring in the revenue table to make aggregate reporting more performant? I failed to ask about this in the reporting pitch but it's worth thinking about now.

**Comment by kjohnson** [comment]
To support renewals from the revenue table we will either need to back fill payment mode for renewal payments or introduce another layer of joins (to include the payment mode from the parent payment).

That is something to consider and would like to discuss with @JasonTheAdams.

**Comment by JasonTheAdams** [comment]
Are renewals a unique post type? Do they also store their amounts and such in the donationmeta table using the same keys?

Also, what's the "payment mode"? Is that the payment gateway?

**Comment by kjohnson** [comment]
@JasonTheAdams renewals use the same `give_payment` post type, but leverage the post status (`give_subscription` instead of `publish`) to differentiate.

Also, `payment mode` is `live` or `test`, which is marked as meta on the `give_payment`, but renewals don't seem to have that meta set. Presumably because the mode is inherited from the parent, but `WP_Query::meta_query` doesn't support meta lookups on the parent post.

**Comment by kevinwhoffman** [comment]
@JasonTheAdams Can you bring this to a resolution based on Kyle's answer?

**Comment by kjohnson** [comment]
Closing in favor of #5409

**Pull request closed without merging**
