### PR TITLE
Fix: Donor Wall API requests are now verified with a nonce

### LINKED ISSUE #6374: The Donor Wall API endpoint should only be accessible from authenticated requests.
Currently, the donor wall is available via a public API endpoint. It should not be.
Ideally, only authenticated requests from the front end of WordPress should ahve access to that endpoint. 
Though this is not a security issue since none of the data on the endpoint would be qualified as [sensitive information](https://www.gtlaw-dataprivacydish.com/2021/05/what-is-considered-sensitive-personal-information/), but can be [Personally Identifiable Information (PII)](https://www.imperva.com/learn/data-security/personally-identifiable-information-pii/).
Donors who select to be anonymous are not displayed on the Donor wall. 
All of that to say, it still would make sense to resritct access to that endpoint, because some organizations may not use the Donor Wall at all, and currently that endpoint is publicly available regardless.

https://givewp.canny.io/admin/board/bug-reports/p/the-donor-wall-api-endpoint-should-only-be-accessible-from-authenticated-request

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #6374

## Description

This PR adds a nonce check when loading "more" items on the Donor Wall. The original request is rendered via page load, but subsequent requests are over admin-ajax. 

## Testing Instructions

- [ ] Requests to the Donor Wall API return a 403 error when a valid nonce is not provided.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by ravinderk — APPROVED** [review]

**Comment by JasonTheAdams** [comment]
@kjohnson @ravinderk This happened a long time ago, but we received an email from Beaver Builder that the `wp_doing_ajax()` check in the shortcode function is breaking it in Beaver Builder. I would guess elsewhere, too.

Thinking about this, it seems odd that we'd put an AJAX check in a shortcode... why wouldn't we just stop using the shortcode in an AJAX context? Is this used somewhere I'm not understanding?

**Comment by kjohnson** [comment]
If I recall correctly, the shortcode is being parsed the first time on page load (no AJAX), and then again to update the content (with AJAX). So it is doing two different, but related things.

@ravinderk can probably better answer the question as to why.

**Comment by ravinderk** [comment]
> @kjohnson @ravinderk This happened a long time ago, but we received an email from Beaver Builder that the `wp_doing_ajax()` check in the shortcode function is breaking it in Beaver Builder. I would guess elsewhere, too.
> 
> Thinking about this, it seems odd that we'd put an AJAX check in a shortcode... why wouldn't we just stop using the shortcode in an AJAX context? Is this used somewhere I'm not understanding?

@kjohnson I suggest adding a nonce check in the Ajax request controller instead of a shortcode renderer.
https://github.com/impress-org/givewp/blob/1bd12b307e44729616e26a31ec58808b12fc0228/includes/donors/class-give-donor-wall.php#L314

@JasonTheAdams does the above suggestion resolve your concern?

**Comment by JasonTheAdams** [comment]
Thanks for the input, @ravinderk!

Yeah, moving the check out of the shortcode and into wherever its being used would resolve the issue. Could you please make a PR for this?

**Comment by ravinderk** [comment]
> Thanks for the input, @ravinderk!
> 
> Yeah, moving the check out of the shortcode and into wherever its being used would resolve the issue. Could you please make a PR for this?

@JasonTheAdams I will take care of this

**Pull request merged**
