### PR TITLE
Refactor: Update step 2 of the Setup Guide

### PR DESCRIPTION
**Pull request by pauloiankoski**
Resolves [GIVE-971]
Depends on #7457

## Description
This pull request updates the Step 2 of the Setup Guide. There are two states for it:

1. When neither Stripe or PayPal are configured, it's marked as _Not Completed_.
2. When either Stripe or PayPal are configured, it's marked as _Completed_ and the configured gateway is marked with the green icon.

## Affects
Step 2: Setup Guide

## Visuals
dev givewp local_wp-admin_edit php_post_type=give_forms page=give-setup (3)
dev givewp local_wp-admin_edit php_post_type=give_forms page=give-setup (4)

## Testing Instructions
1. In a new install, complete the wizard. At the end, you’ll be redirected to the Setup Guide, and state 1 should be presented. 
2. Configure Stripe or PayPal, then visit the Setup Guide page. State 2 should be presented.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [x] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-971]: https://stellarwp.atlassian.net/browse/GIVE-971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by glaubersilva — COMMENTED** [review]
@pauloiankoski It looks good to me, but I would like to know how feasible would be to add a way to automatically redirect users back to the setup page after connecting a gateway so they can continue with step 3 if they wish.

**Comment by pauloiankoski** [comment]
@glaubersilva that sounds like a good enhancement for the user experience but it's definitely out of the current scope for this task. Also important to have in mind that all this stuff is just being improved to work with v3 forms but that may be entirely reworked in a modernization process alongside other admin pages pretty soon.

**Comment by glaubersilva** [comment]
@pauloiankoski I agree about the scope! So would be good to create a task on Jira for this improvement so we will not forget it in the future, if you don't mind.

**Review by glaubersilva — APPROVED** [review]
@pauloiankoski Looks goog to QA.

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
