### PR TITLE
DI Container auto wiring now works correctly when using PHP8

### LINKED ISSUE #5987: DI Container auto wiring should work correctly when using PHP8
## Details

Currently, when running a website using PHP8, add-ons like Give MailChimp will throw a fatal error on add-on activation. The `Give\Container` somehow, and I'm not entirely sure why, is not able to correctly handle the optional constructor parameters. 

Example code from the Give MailChimp add-on that is causing this behavior

```
class ApiKey {
	public function __construct( $apiKey = null ) {
```

Related https://github.com/impress-org/give-mailchimp/issues/82

## Expected Behavior

DI Container should work using PHP8

## Steps to Reproduce

1. Make sure your site is running using PHP8
2. Download and install the MailChimp add-on
3. Activate it

## Acceptance Criteria

-   [ ] DI Container auto wiring works correctly when using PHP8 and Give MailChimp add-on

### PR DESCRIPTION
**Pull request by alaca**
Resolves #5987

## Description

On some rare occasions, [$dependency->getClass() ](https://github.com/impress-org/givewp/blob/123d168ce0966409e96dcf0ad6cb2dc7da215085/src/Container/Container.php#L745) and [$dependency->getType()](https://github.com/impress-org/givewp/blob/123d168ce0966409e96dcf0ad6cb2dc7da215085/src/Container/Container.php#L746) can return `null`. In my understanding, this happens when the dependency class has optional parameters in constructor, like [ApiKey](https://github.com/impress-org/give-mailchimp/blob/bdbaed4a760addf95f1ef1ac91dba8152b136e5b/src/MailChimp/Repositories/ApiKey.php#L23) class has from MailChimp add-on. 

This PR resolves the issue by adding additional `is_null` checks to `Give\Conatiner::resolveDependencies()` and `Give\Container::resolveClass()` methods.

## Affects

Give\Container

## Testing Instructions

1. Make sure your site is running using PHP8
2. Download and install the MailChimp add-on
3. Activate it

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by alaca** [comment]
@JasonTheAdams I'm not entirely sure what is happening here, and why the Container is doing what is doing, and is this a good way to resolve that issue.

**Review by JasonTheAdams — APPROVED** [review]
Interesting catch, @alaca! I pulled this down and thought about it a bit. I consolidated retrieving the class by PHP version into its own method and cleaned it up a bit (nested ternary operators are confusing, in my opinion).

Please test this a bit as well, since I made significant changes, and merge if it's working for you.

**Comment by JasonTheAdams** [comment]
As a note, I looked at the Laravel Container code this comes from and it's changed quite a bit. At some point I'd like to update the code to what it's like these days, but at this time it requires a lot of fidgeting to make it PHP 5.6 compatible. We're missing out on some of the finer features of the Container due to this. It may have to wait until GiveWP 3.0 to update the code, as I'm _hoping_ to bump to PHP 7.2 at that time.

**Comment by alaca** [comment]
@JasonTheAdams looks good, much better than before. Tested and it is working correctly :+1:

**Pull request merged**
