### PR TITLE
Custom field values now show in Donation Receipt and Donation Confirmation

### LINKED ISSUE #5624: Fields API should support managing fields in receipts
Let's add an Issue as well to give an option for showing the field in the receipt, like happens in the Form Field Manager. I'm thinking:
```php
Fields::text('website')
  ->label('Website')
  ->showInReceipt();
```
_Originally posted by @JasonTheAdams in https://github.com/impress-org/givewp/issues/5620#issuecomment-782431885_

## Acceptance Criteria

- [x] Custom field values show in Donation Receipt (Sequoia).
- [x] Custom field values show in Donation Confirmation (legacy).

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #5624

Depends on #5652

## Description

Custom field values now show in the Donation Receipt for the Sequoia form template.

NOTE: Custom fields must be stored as donor and/or donation meta in order to be added to the receipt.

## Visuals

Donation Receipt
Screenshot_2021-02-25 Donation Form – WordPress(1)

Donation Confirmation
Screenshot_2021-02-25 Donation Confirmation – WordPress

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

```php
add_action( 'give_fields_after_donation_levels', function( $fieldCollection, $formID ) {
	$fieldCollection->append(
		give_field( 'text', 'my-custom-field' )
			->label( 'My Custom Field' )
			->required()
			->storeAsDonorMeta()
			->storeAsDonationMeta()
	);
}, 10, 2 );
```

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
I merged #5652 but I'm still seeing the previous form of storing in this PR. Can you please correct that and let me know when this is ready?

**Review by JasonTheAdams — CHANGES_REQUESTED** [review]
I haven't tested this yet (waiting for the dependency to be resolved), but I did notice that that the field always shows up in the receipt. I would prefer this to be settable:
```php
add_action( 'give_fields_after_donation_levels', function ( $fieldCollection, $formID ) {
	$fieldCollection->append(
		give_field( 'text', 'my-custom-field' )
			->label( 'My Custom Field' )
			->required()
			->showInReceipt()
	);
}, 10, 2 );
```
I'm on the fence whether it should be displayed by default or not. I'm inclined to say no and have them apply that method. If it does show by default, then we ought to have a method to hide it.

**Comment by kjohnson** [comment]
@JasonTheAdams I can't believe I didn't add the `showInReceipt()` method! Ugh.

Added, see https://github.com/impress-org/givewp/pull/5654/commits/5c219e43732364f0e48a9e0e5d0e8344f6fef7b8.

I also updated the storage by merging back in the epic branch, see https://github.com/impress-org/givewp/pull/5654/commits/cd9608e78ac5514334841b6646ed3e43774b39bc.

**Review by JasonTheAdams — APPROVED** [review]
Works like a charm! 🧾✅

**Pull request merged**
