### PR TITLE
Custom Fields on the Sequoia template now match alignment

### LINKED ISSUE #5668: Custom Fields on the Sequoia template should match alignment
Currently, there are some sections where the inputs are the full width of the form and do not align left/right with the other inputs.

| Choose Amount | Payment |
| --- | --- |
| Screenshot_2021-03-04 Donation Form(4) | Screenshot_2021-03-04 Donation Form(5) |

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #5668

## Description

Updates the alignment of custom fields to match the default fields in the Sequoia template.

## Affects

- Adds new CSS to the Sequoia template styles.

## Testing Instructions

Here is a snippet for adding custom fields to each template hook:

```php
add_action( 'init', function() {
	give( \Give\Form\LegacyConsumer\TemplateHooks::class )->walk( function( $hook ) {
		add_action( "give_fields_$hook", function( $fieldCollection, $formID ) use ( $hook ) {
			$fieldCollection->append(
				give_field( 'text', 'my-custom-field-' . uniqid() )
					->label( "$hook" )
			);
			$fieldCollection->append(
				give_field( 'textarea', 'my-custom-field-' . uniqid() )
					->label( "$hook" )
			);
			$fieldCollection->append(
				give_field( 'select', 'my-custom-field-' . uniqid() )
					->label( "$hook" )
					->options([
						'' => "$hook",
					])
			);
			$fieldCollection->append(
				give_field( 'checkbox', 'my-custom-field-' . uniqid() )
					->label( "$hook" )
			);
		}, 10, 2 );
	});
});
```

## Visuals

| Choose Amount | Payment |
| --- | --- |
| Screenshot_2021-03-04 Donation Form(2) | Screenshot_2021-03-04 Donation Form(3) |

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by DevinWalker — APPROVED** [review]
Looks good to me 👍

**Comment by DevinWalker** [comment]
@kjohnson I notice the labels are not there for FFM fields in the multi-step form. We taking care of that in a separate PR, right?

**Review by JasonTheAdams — APPROVED** [review]
Great work! This makes me so happy! 😁

**Comment by kjohnson** [comment]
@DevinWalker the field labels are hidden by the Sequoia template.

**Pull request merged**
