### PR TITLE
feature: add node types to field api

### PR DESCRIPTION
**Pull request by JasonTheAdams**
## Description

❗️This is necessary for the NextGen PR: https://github.com/impress-org/givewp-next-gen/pull/18 ❗️

This adds the concept of `nodeType` to all the nodes to break things into Elements, Fields, and Groups, which is required for the Template API.

It also adds a Section type and enforces that only Sections can be appended to Forms.

## Affects

Shouldn't affect any existing GiveWP code adversely as the `nodeType` is automatic and no GiveWP code is using the `Form` class.

## Testing Instructions

Test with the NextGen PR.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [x] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
This was a good theory to try out, but I don't think it's quite what we want in practice and is compensating for what PHP will natively offer. Let's close for now and revive later if we feel the need.

**Comment by jonwaldstein** [comment]
> This was a good theory to try out, but I don't think it's quite what we want in practice and is compensating for what PHP will natively offer. Let's close for now and revive later if we feel the need.

@JasonTheAdams This PR is a dependent of the template api[ PR](https://github.com/impress-org/givewp-next-gen/pull/18) in next-gen

**Comment by JasonTheAdams** [comment]
Bah! I thought this was a different PR! Yikes! Glad I didn't delete the branch! 😅

Good catch, @jonwaldstein!

**Comment by jonwaldstein** [comment]
@kjohnson can you look this over?  I had to update some of the Fields API tests to accommodate the new `Section` direction.

cc: @JasonTheAdams

**Comment by JasonTheAdams** [comment]
Looks good to me, @jonwaldstein! Thanks for the tests!

**Pull request merged**
