### PR TITLE
Feature: add matching v2 form lifecycle hooks

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

Continuing with the [addition of v3 donation form lifecycle hooks](https://github.com/impress-org/givewp/pull/7151), this PR adds matching hooks for donation, donor, and subscription created events to the v2 form adapter flow.

### `give_donation_form_processing_start` (v2 specific)

```
 /**
 * Fires at the start of donation form processing, before any data is processed.
 *
 * @unreleased
 *
 * @param  FormData  $formData
 * @param  string  $gatewayId
 */
do_action('give_donation_form_processing_start', $formData, $formData->paymentGateway);
```

### `givewp_donation_form_processing_donation_created`

```
/**
 * Fires after a donation is created during donation form processing.
 *
 * @unreleased
 *
 * @param  Donation  $donation
 * @param  Subscription|null  $subscription
 */
do_action('givewp_donation_form_processing_donation_created', $donation, $subscription);
```

### `givewp_donation_form_processing_subscription_created`

```
/**
 * Fires after a subscription is created during donation form processing.
 *
 * @unreleased
 *
 * @param  Subscription  $subscription
 * @param  Donation  $donation
 */
do_action('givewp_donation_form_processing_subscription_created', $subscription, $donation);
```

### `givewp_donation_form_processing_donor_created`

```
/**
 * Fires after a donor is created during donation form processing.
 *
 * @unreleased
 *
 * @param  Donor  $donor
 * @param  int  $formId
 */
do_action('givewp_donation_form_processing_donor_created', $donor, $formId);
```

## Affects

- Adds additional action hooks to the v2 form adapter flow including when a new donor is created.

## Visuals

N/A

## Testing Instructions

Zip: https://github.com/impress-org/givewp/actions/runs/7759560298

- can test out any of the new actions programatically

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@JasonTheAdams this is the matching v2 lifecycle hooks PR from #7151

**Review by JasonTheAdams — CHANGES_REQUESTED** [review]
This looks good to me, @jonwaldstein! Can we get some tests for these?

**Comment by jonwaldstein** [comment]
@JasonTheAdams yup, good call

**Comment by jonwaldstein** [comment]
@JasonTheAdams turns out writing tests for these is very complicated since they are inside the legacy payment gateway adapter.  I got started in another branch but kept hitting roadblocks that may require updating the production code for testing purposes.  I'll have to circle back to that attempt.

**Review by JasonTheAdams — APPROVED** [review]
Understood, @jonwaldstein. I'd rather get these out then hold it up from tests. Thanks for trying!

**Pull request merged**
