### PR TITLE
Condition operators are now decoded in case of values stored encoded

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves https://github.com/impress-org/give-form-field-manager/issues/376

## Description

This PR adds a line to decode the operator before validation, in case the operator value is coming from the database and encoded as an HTML entity.

## Testing Instructions

- Using GiveWP 2.17.1
- Using FFM 2.0.1
- Set an FFM field's visibility to Less Than or Less Than Or Equals
- Form **should** load and **should not** throw the following error:
`Fatal error: Uncaught Give\Framework\Exceptions\Primitives\InvalidArgumentException: Invalid operator: &lt;=. Must be one of: =, !=, >, >=, <, <= in give/src/Framework/FieldsAPI/Conditions/BasicCondition.php on line 45`

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [x] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by JasonTheAdams — CHANGES_REQUESTED** [review]
@kjohnson Right solution but wrong place. Yes, we should be encoding it when placing it in the HTML attribute, but no it should not be encoded in the Field API. It only needs to be encoded at the exact point that we're applying it to the HTML.

**Comment by kjohnson** [comment]
@JasonTheAdams I would agree, but there is also the case that these values are already stored encoded in the database, so this is a defensive positioning for that reason.

**Comment by JasonTheAdams** [comment]
If we need to encode/decode in multiple places, that's fine. But I don't want the experience within the Field API to be comparing against HTML entities. That's a completely different context.

**Comment by kjohnson** [comment]
Closing in favor of https://github.com/impress-org/give-form-field-manager/pull/377.

**Pull request closed without merging**
