### PR TITLE
Setup strauss installar script to auto download and use latest release

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves [GIVE-2056]

## Description

This pull request sets a bash script to automatically use the latest release of `strauss` package.

## Testing Instructions

- [ ] You should be able to successfully run `composer install`
- [ ] `strauss.phar` should install when
     - [ ] `bin/strauss.phar` does not exist
     - [ ] `bin/strauss-version.txt` does not exist
     - [ ] `staruss` version in `bin/strauss-version.txt` does not match latest release.
- [ ] `composer install` should always install latest release of `strauss`

Note: you can run `bin/strauss-install.sh` for testing.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-2056]: https://stellarwp.atlassian.net/browse/GIVE-2056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@ravinderk i'm hesitant to _always_ install the latest release of strauss without testing incremental versions in our workflow. 
 Is there any reason you would be confident enough to let that automation happen to receive the latest version or do we think there are possibilities of side effects that could go unnoticed without proper testing of each version?

**Comment by ravinderk** [comment]
> @ravinderk i'm hesitant to _always_ install the latest release of strauss without testing incremental versions in our workflow. Is there any reason you would be confident enough to let that automation happen to receive the latest version or do we think there are possibilities of side effects that could go unnoticed without proper testing of each version?

@jonwaldstein I locked release version to `0.16.0`:https://github.com/impress-org/givewp/pull/7311/commits/7ad261c044b8af9fd79a382f303504ad51e73e14, that means bash script will only install specific version and clear cached version from bash automatically.

**Comment by jonwaldstein** [comment]
@JasonTheAdams I would appreciate your eyes on this as well - since you were the one who setup strauss 🧙.

**Comment by JasonTheAdams** [comment]
It seems like this is taking what's currently a single line of inline bash and breaking it out into a bash script. Is the current line not doing something? Why not just change the inline script to be https://github.com/BrianHenryIE/strauss/releases/download/0.16.0/strauss.phar?

**Comment by ravinderk** [comment]
> It seems like this is taking what's currently a single line of inline bash and breaking it out into a bash script. Is the current line not doing something? Why not just change the inline script to be https://github.com/BrianHenryIE/strauss/releases/download/0.16.0/strauss.phar?

@JasonTheAdams I added an extra feature in the bash script. The cached `bin/strauss.phar` will be replaced in `bin/` if the current version does not match. That means we will have the same version across team.

**Comment by JasonTheAdams** [comment]
Got it, @ravinderk! I see the value and I like it!

Rather than storing the version in a file, I suggest using `php strauss.phar --version`, which will output something like:
```
strauss 0.14.0
```

You can use a little regex to easily parse the version from that line. As a note, I put in a [request for a plain version flag](https://github.com/BrianHenryIE/strauss/issues/92).

**Comment by ravinderk** [comment]
> Got it, @ravinderk! I see the value and I like it!
> 
> Rather than storing the version in a file, I suggest using `php strauss.phar --version`, which will output something like:
> 
> ```
> strauss 0.14.0
> ```
> 
> You can use a little regex to easily parse the version from that line. As a note, I put in a [request for a plain version flag](https://github.com/BrianHenryIE/strauss/issues/92).

@JasonTheAdams version command output is not reliable at this moment and I created an issue on their repository https://github.com/BrianHenryIE/strauss/issues/90. For this reason, I am using a txt file to store the version.

**Comment by ravinderk** [comment]
> @ravinderk According to that Issue this is working in the PHAR. I just tested it in 0.14.0 and it worked fine, too.

@JasonTheAdams I refactored logic to use version to get `strauss` library version- https://github.com/impress-org/givewp/pull/7311/commits/c942413a70d68d2e2c84697b16a49b3f590e1a4d

**Review by JasonTheAdams — APPROVED** [review]
Thanks! I like it! I can definitely see this avoiding some strange issues in the future. 👍

**Comment by jonwaldstein** [comment]
Build for QA: https://github.com/impress-org/givewp/actions/runs/8508557651

**Comment by jonwaldstein** [comment]
The github action for generating a zip is failing on this PR due to some permission issue with the `vendor-prefixed` directory https://github.com/impress-org/givewp/actions/runs/8524271225/job/23348497486

Anyone have an idea what's going on?

**Comment by jonwaldstein** [comment]
> The github action for generating a zip is failing on this PR due to some permission issue with the `vendor-prefixed` directory https://github.com/impress-org/givewp/actions/runs/8524271225/job/23348497486
> 
> Anyone have an idea what's going on?

@JasonTheAdams @ravinderk we have a permission issue with the `vendor-prefixed` folder ☝️

**Comment by ravinderk** [comment]
@jonwaldstein I am not sure what is an issue with the rsync command and directory permission. We need to debug the GitHub action, or we can update the workflow to set the correct permission to the `vendor-prefixed` directory.

Can you take of this?

cc @JasonTheAdams

**Comment by jonwaldstein** [comment]
@ravinderk yeah, i'm confused why it's only failing from permissions issues in this PR though

**Review by jonwaldstein — CHANGES_REQUESTED** [review]
The plugin zip is still failing for this which should be resolved before merging.

https://github.com/impress-org/givewp/actions/runs/9682069602/job/26714974478

Screenshot 2024-06-26 at 11 22 59 AM

**Comment by jonwaldstein** [comment]
Apparently Strauss 0.16.0 introduced some permission issue https://github.com/BrianHenryIE/strauss/issues/104 and was released in 0.19.2.  We can try updating to the latest at time of writing this which would be [0.20.0](https://github.com/BrianHenryIE/strauss/releases/tag/0.20.0)

**Comment by jonwaldstein** [comment]
I attempted to update to 0.20.0 but now we have another permission issue:

Screenshot 2024-12-10 at 4 35 59 PM

**Review by jonwaldstein — APPROVED** [review]
Updated to 0.20.1 with the permissions fix from @defunctl and we're back in business! 

https://github.com/impress-org/givewp/actions/runs/12304079021

**Review by rickalday — COMMENTED** [review]
Passed automated QA tests

**Pull request merged**
