### PR TITLE
"donation_id" and "form_id" set as foreign key which reference to "wp_posts.ID"

### LINKED ISSUE #5272: "form_id" and "donation_id" column of give_revenue should referenced to wp_posts "ID"
## Details
[give_revenue](https://github.com/impress-org/givewp/issues/5257) table added to core without reference to `wp_posts`. `donation_id` and `form_id` can be set as foreign key which reference to `wp_posts.ID`.

## Acceptance Criteria
-   [x] `donation_id` and `form_id` set as foreign key and reference to `wp_posts.ID`

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves #5272

## Description
`donation_id` and `form_id`  set as foreign key which reference to `wp_posts.ID`.

## Affects
- I fixed a PHP error that generates on the system info page because of referencing old class.
- Update logic to prevent migration overwrite if has the same timestamp.

## Visuals
image

## Pre-review Checklist
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions
If you want to rerun Migration then make sure you complete below steps:
- [ ] Remove `wp_give_reveneue` table
- [ ] Remove `give_database_migrations` from `wp_options`.

### CODE REVIEW

**Comment by ravinderk** [comment]
@JasonTheAdams I find out that if migrations have the same timestamp then they will overwrite each other when run migration, so few migrations will not run. I updated pr to prevent migration overwrite: https://github.com/impress-org/givewp/compare/443d4e1a1865...8984d09f23df

But I think better route will make migration id and timestamp unique and throw an error if the code tries to register migration with a duplicate timestamp, what do you think? This will make sure that migration will always run in an order

**Comment by JasonTheAdams** [comment]
@ravinderk The ID is forced to be unique, so just concat the id and timestamp:
```php
$migrations[$migrationClass::timestamp() . '_' . $migrationClass::id()] = $migrationClass;
```

No reason in doing additional constraint checks if we know the combination is guaranteed unique.

**Comment by ravinderk** [comment]
> @ravinderk The ID is forced to be unique, so just concat the id and timestamp:
> 
> $migrations[$migrationClass::timestamp() . '_' . $migrationClass::id()] = $migrationClass;
> No reason in doing additional constraint checks if we know the combination is guaranteed unique.

Above solution is not guaranteed that migration will run in a fixed order.
For example: with the unique key `20190916_Create_Table`, `20190916_Alter_Table` , alter table migration run first because we are using `ksort`.

**Review by JasonTheAdams — APPROVED** [review]
The code looks good to me.

@alaca, you are still the primary reviewer for this, to please do a complete review before this is merged.

**Comment by alaca** [comment]
@ravinderk  I can't review it since you already merged it :laughing:

Anyway, looks good! :+1:

**Pull request merged**
