### PR TITLE
Fix/donation forms trash status

### PR DESCRIPTION
**Pull request by pauloiankoski**
## Description

Fix issues that:
1. prevented users to list trashed donation forms. Our Enum didn't have support for trash status.
2. prevented users to delete a trashed donation form. The JS logic was expecting an old data structure so it was returning the wrong endpoint for the delete action.

## Affects

Donation Forms List Table

## Visuals

image
image

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203757145589078

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@pauloiankoski thanks for this.  Can you look into whats happening here too? this is when you try to use bulk actions like edit and delete:

Screen Shot 2023-01-10 at 4 11 47 PM


Screen Shot 2023-01-10 at 4 24 46 PM

**Comment by jonwaldstein** [comment]
Looks like we need to add more statuses to the form model (Private and Pending Review):

Screen Shot 2023-01-10 at 4 47 32 PM

**Comment by jonwaldstein** [comment]
More thing I just noticed, if you filter by trash and select all columns - it thinks you mean all forms instead of the ones visible:

Screen Shot 2023-01-10 at 4 52 17 PM


Screen Shot 2023-01-10 at 4 52 22 PM

**Comment by jonwaldstein** [comment]
@JoshuaHungDinh can you please help with these front-end bugs?  Let's make sure all the buttons, filters, and bulk actions work as expected and we'll pull in QA again for final check.

**Comment by JoshuaHungDinh** [comment]
> @pauloiankoski thanks for this. Can you look into whats happening here too? this is when you try to use bulk actions like edit and delete:
> 
> Screen Shot 2023-01-10 at 4 11 47 PM
> 
> Screen Shot 2023-01-10 at 4 24 46 PM

Resolved: https://github.com/impress-org/givewp/pull/6666/commits/8b2197fb86b8605a5b8141858467d0653c69970f


https://user-images.githubusercontent.com/75056371/211846086-3743cabe-856d-4dae-af10-44f6ff972a88.mov

**Comment by JasonTheAdams** [comment]
@pauloiankoski I also just noticed the "View" and "Edit" links are missing:
image

**Comment by JasonTheAdams** [comment]
@jonwaldstein Please give this another code review. In addressing the missing row actions, I found further issues with the test mode state being set — in that, customers could/would find themselves in a place where the mode wasn't being recorded properly... and weren't showing up in the Subscriptions table. 😬

**Review by jonwaldstein — APPROVED** [review]
Looking much better!

**Review by rickalday — APPROVED** [review]
Passed QA tests

**Pull request merged**
