### PR TITLE
Enhancement: Consolidate test gateways

### PR DESCRIPTION
**Pull request by JasonTheAdams**
## Description

There are currently three test gateways in 3.0, which is super confusing. Hahah! There were:
- Test Donations (v2 only)
- Test Gateway
- Test Gateway (offsite)

I tested and realized that Test Gateway is a drop-in replacement for the existing Test Donations gateway, so that can be removed entirely. (Which means less code in `includes`, yay!)

The offsite Test Gateway is really only needed for devs specifically testing how offsite donations work, and is more likely to confuse customers than help them. I think we can add a setting or something in the future if testing offsite gateways comes up more, but for now I simply commented it out from being loaded with a note.

Finally, for the sake of reporting and backwards-compatibility, I changed the Test Gateway to Test Donations and changed its ID to `manual`, which is what the old Test Donations gateway id was. That way, when someone updates to 3.0 there are no surprises or migrations needed, and previous donations made with that gateway will still fit within the new gateway as if nothing had changed.

there can be only one

## Affects

The aforementioned gateways.

## Visuals

image

## Testing Instructions

Make sure that the Test Donations gateway works with v2 **and** v3 forms.

Also, make some test donations before updating to this, and then update, make some more donations, and make sure the reporting sees them as exactly the same.

## Pre-review Checklist

-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205444026014417

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@jonwaldstein Since you built the test gateways I'd appreciate it if you could review this.

**Review by jonwaldstein — APPROVED** [review]
Looks good, I updated the gateway ID in `testGateway.tsx` as well.

**Comment by JasonTheAdams** [comment]
Awesome! Can you please shoot this off to QA if the tests pass?

**Review by rickalday — APPROVED** [review]
Passed manual QA tests

**Pull request merged**
