### PR TITLE
Show meaningful error to donor when process donation with PayPal Commerce

### PR DESCRIPTION
**Pull request by ravinderk**
I created this pr in favor of https://github.com/impress-org/givewp/pull/5079#issuecomment-691367061

## Description
After debugging donor donation flow, I find out that error occurs when creating order, so I updated the logic to show error which occurs when created order.

## Visuals

Error notice which displays when the currency will not be supported by PayPal Commerce.

image

Error notice which displays when `null` return from PayPal commerce when creating an error.

image

## Pre-review Checklist
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions
- Run `npm i && npm run dev`
- Set currency to any currency which is not supported by PayPal Commerce. For example `Colombian peso ($)`

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@DevinWalker @ravinderk 

As I'm processing through donation form error messages, I'm finding myself thinking in two different categories of errors:

### Administrative Errors
This category has to do when something went wrong respective to the administrator's actions — likely configuration. For example, the admin is attempting to use a currency not supported by their selected payment gateway. In this case, once things are configured properly donors should no longer see these sorts of messages. It's possible they might, but that is more indicative of the admin missing something when testing.

It would make sense to me that in these cases the error is written more for the admin, to help them resolve the configuration issue quickly.

### Payment Errors

This category has to do when something went wrong respective to the donor's actions. For example, validation errors or there was an issue processing the provided card. There's nothing for the admin to do, so it's best that we provide instructions written from the perspective of the donor — ideally, guiding them to still fulfill the donation.

cc: @kevinwhoffman

**Comment by JasonTheAdams** [comment]
@ravinderk I did some work on this, but it's not quite finished due to this: https://github.com/paypal/paypal-sdk-client/issues/45

Let's touch base in the morning. I'll ping you when I'm on.

**Comment by ravinderk** [comment]
@JasonTheAdams I tested updated pr and the `onError` param for the smart button is not working.

Doc link: https://developer.paypal.com/docs/checkout/integration-features/handle-errors/

**Comment by JasonTheAdams** [comment]
Interesting, thank you for checking, @ravinderk. Are we loading the JS SDK any different than I'm doing in this working codepen? https://codepen.io/JasonTheAdams/pen/gOrKyoG

**Comment by ravinderk** [comment]
@JasonTheAdams I discovered that `onError` conflicting with `onClick`. If we do not pass `onClick` then you can see error prints in Chrome console tab.

image

**Comment by JasonTheAdams** [comment]
@DevinWalker As an update on this, we've ran into a bug on the PayPal JS SDK that we're working with them to figure out: https://github.com/paypal/paypal-sdk-client/issues/45

Basically, when an error occurs during the usage of Smart Buttons, the callback the SDK provides us to handle errors isn't firing. This prevent us from displaying a meaningful error to the user.

**Comment by JasonTheAdams** [comment]
**Update:**

Was finally able to make the issue clear to the PayPal SDK team. They said it will likely take a couple days to look into it and then will work on a fix.

**Comment by JasonTheAdams** [comment]
@ravinderk The `onError` bug fix has been released — https://github.com/paypal/paypal-sdk-client/issues/45#issuecomment-700776685. This is no longer on hold and can be resumed.

**Comment by ravinderk** [comment]
@JasonTheAdams I update this pr:
- update to logic uncatced errors in  advanced card field with `catch` and smart button error  with `onError`
- form with `Multi Step Form` template will auto-scroll to iframe donation form top when error printed on form top.

I did not remove the old errors because that need testing with another addon because we do not want to remove sticky notice like test mode notice or donor currency auto switched.

**Comment by ravinderk** [comment]
New position for terms and condition field:

Logged in Donor:
image

Guest Donor:
image

**Comment by ravinderk** [comment]
Guest Donor:
image
image


Logged In Donor:
image
image

**Comment by JasonTheAdams** [comment]
Otherwise, the errors are looking good to me! The scrolling is working and the messages have improved. 👍

**Comment by ravinderk** [comment]
As per discussion, I will option separate pr to reorder terms and condition field.

**Pull request merged**
