### PR TITLE
Creation of the give_migrations table is not producuing errors anymore

### LINKED ISSUE #5736: Creating the give_migrations table should not produce a fatal error
## User Story

As a site admin, I want the new release `2.10.0` not to produce a fatal error

## Details
The `give_migrations` table cannot be created on some systems because the specified `id` column length ( 255 ) is too long, which produces a fatal error and table creation fails.

```
[18-Mar-2021 12:01:59 UTC] WordPress database error Specified key was too long; max key length is 767 bytes for query CREATE TABLE wp_give_migrations (
  id VARCHAR(255) NOT NULL,
  status VARCHAR(16) NOT NULL,
  error text NULL,
  last_run DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY  (id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
```

## Expected Behavior
Installing GiveWP `2.10.0` should not produce a fatal error and the `give_migrations` table should be created.

## System Information

<details><summary>Details</summary>

</details>

## Acceptance Criteria

-   [ ] Installing GiveWP `2.10.0` should not produce a fatal error
-   [ ] The `give_migrations` table should be created on plugin install

### PR DESCRIPTION
**Pull request by alaca**
Resolves #5736

## Description

This PR resolves the issues with creation of the give_migrations table that was failing on some systems. The problem was in the `id` column key length, which was set to `255`. But on some systems, that key length is causing a fatal error, depending on what MySQL engine and what encoding is being used. The issue is resolved by setting the key length to `180`. 

Additionally, the `MigrationLogRepository::save` method is wrapped up with a try-catch block in order to keep the site functional even if the migration system fails. 

## Affects

Migration system

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by kjohnson** [comment]
I'll add that `180` characters multiplied by a possible `4` bytes per character comes out to `720` bytes, which is below the `767` limit  for MySQL 5.6 (MariaDB 10.0).

**Review by kjohnson — APPROVED** [review]

**Review by ravinderk — CHANGES_REQUESTED** [review]
@alaca
- Can we validate migration id length when register, throw an exception otherwise?
- Can you confirm that this change works fine with currency switcher migration because that addon register a migration id with long length?

**Comment by JasonTheAdams** [comment]
@ravinderk I'm not sure what you mean by this:
> Can we validate migration id length when register, throw an exception otherwise?

**Comment by kjohnson** [comment]
The key length issue has to do with the upper limit, which is based on the column size - as opposed to the value of the id itself. So we don't need to validate the id.

**Comment by ravinderk** [comment]
@JasonTheAdams @kjohnson currency switcher migration was not completing because of the database  was not storing migration id correctly because migration id length was greater than allowed database column length: https://github.com/impress-org/givewp/issues/5696

**Comment by kjohnson** [comment]
@ravinderk the value of the id for the Currency Switcher migration is good, only 65 and 49 characters - well below the new limit of 180.

**Comment by ravinderk** [comment]
> @ravinderk the value of the id for the Currency Switcher migration is good, only 65 and 49 characters - well below the new limit of 180.

It's ok then.

**Review by JasonTheAdams — APPROVED** [review]
@alaca and I took another pass at this and tackled the problem in a couple new ways:
1. The Migration Log model doesn't catch itself. That way implementing code can be aware of issues, and it's now being caught in the Migration Runner.
2. Logging should never throw exceptions, so we're also catching logging failures and storing them to the PHP log file if all else fails.

This should now be much better at preventing fatal errors during migrations and logging. 🎉

**Pull request merged**
