### PR TITLE
Donation Receipt accounts for latency in payment status changes 

### LINKED ISSUE #5513: Donation Receipt should account for latency in payment status changes
## User Story

As a donor, I want changes to my donation payment status to be up-to-date.

## Details

Payment receipts sometimes show a false-positive status of `pending` which does not account for latency in a payment gateway returning an update payment status.

## Expected Behavior

Expected latency in a payment gateway updating a payment status should not affect the display of a donation receipt, under normal circumstances.

## Steps to Reproduce

See https://givewp.canny.io/admin/feedback/bug-reports/p/status-should-not-need-a-refresh-to-be-accurate

## Acceptance Criteria

-   [ ] Donation Receipt Payment Status accounts for latency in updates.

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #5513 

## Description

This clears the cache for the payment post so that the Donation Receipt uses the up-to-date payment status.

## Affects

Adds a check in the AJAX request handler, as this attempts to address a caching issue when rendering the donation receipt immediately following a donation.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

I used the `offline` gateway to simulate a donation that is initially marked as `pending`, then using XDebug updated the post status of the payment mid request cycle.

### CODE REVIEW

**Comment by kjohnson** [comment]
I'll like some help in testing this, as the issue is intermittent and not consistently reproducible.

/cc @lflorent

**Comment by ravinderk** [comment]
@kjohnson this issue only happens if payment completion confirmation happens on webhook like Stripe. We can not be sure when webhook will confirm payment on the website. This issue does not occur because of the website cache. Changes in this pr will increase in getting the latest donation status when donors see donation receipt but it will not resolve it completely.

We have to think about the donor experience for the Multi-step form receipt template.

cc: @JasonTheAdams @DevinWalker

**Comment by JasonTheAdams** [comment]
Right, I believe what's happening here is a race condition between the multi-step form switching to the Thank You screen and Stripe's webhook reaching the server and being resolved. What I'm curious if is _why_ the webhook is necessary for the Thank You screen — that is, what information is it providing which we otherwise don't have?

**Comment by ravinderk** [comment]
@JasonTheAdams There lot of scenarios on the basis of that payment can be set to fail by payment gateway on their server. That why we wait for webhook to confirm payment status and send the receipt to the donor.

In addition to that webhook provide us payment transaction id (important) which we use to link donation with payment. Admin can show the transaction on thank you page or with email tag to send this information in donation receipt

**Comment by JasonTheAdams** [comment]
I see, thank you for the explanation, @ravinderk.

We should think through what is truly necessary for a payment to be confirmed, and try to keep that bar low enough that it can be done immediately. If there's information that we can't know until after a webhook comes in, then don't make that available on the thank you page/section — or don't show it until it does come in if the user is meant to go back to that page like a receipt. The purpose of the Thank You is to confirm that the donor's payment went through and is appreciated — that's the core of it — and that should be as immediate and reliable as possible.

**Comment by ravinderk** [comment]
@Jason Adams that what I said in my initial comment. We can rethink about thank you page to remove confusion.
Do you think we need a UI designer to look into this?

cc: @Kyle B. Johnson

**Comment by kjohnson** [comment]
In my testing, I found that there is a possible race condition, by a matter of milliseconds, in which the status is updated mid-request on the donation post object, but WordPress isn't re-hitting the database. Therefor I called a cache clear on that specific post ID to resolve a simple race condition. What I'm solving here is the mis-reporting of a successful payment. There may be cases where the webhook has not updated, but in such a case the payment is actually not completed.

**Comment by ravinderk** [comment]
> In my testing, I found that there is a possible race condition, by a matter of milliseconds, in which the status is updated mid-request on the donation post object, but WordPress isn't re-hitting the database. Therefor I called a cache clear on that specific post ID to resolve a simple race condition. What I'm solving here is the mis-reporting of a successful payment. There may be cases where the webhook has not updated, but in such a case the payment is actually not completed.

You are correct. I will not recommand to flush cache because each host has there own integration logic. 
Main limitation of thank you page (multi step form template) is donor can not refresh it as donor can do with confirmation page (legagy form template). We can give an option on thank you page to reload it and in addition to that we can a javascript logic to reload page after each 5 seconds.

**Comment by kjohnson** [comment]
> We can give an option on thank you page to reload it and in addition to that we can a javascript logic to reload page after each 5 seconds.

I considered this approach, but came to the conclusion that the effort and increased complexity was not worth it. I believe that the cache flush resolves the issue without introducing or changing any other functionality of the donation process.

> I will not recommend to flush cache because each host has there own integration logic.

In this case, we are flushing the cache for a specific post ID. Does this present any specific problem that I can address?

**Comment by ravinderk** [comment]
@kjohnson 
> In this case, we are flushing the cache for a specific post ID. Does this present any specific problem that I can address?

It does not see any problem right now, but my thought was motivated by previous experience with the system cache. Will this also flush group queries because [we have our own logic to store donation, form, and donor](https://github.com/impress-org/givewp/blob/a2cf1ccf657c3ee13bc7491e0e7bf715b3e01329/includes/class-give-cache.php#L76). 
I do not see that it will address all issues but definitely a few rare race conditions. My suggestion will increase complexity but it will benefit the donor. I also read the canny comment and few comments were looking for the receipt refresh feature. I am open to merge this pull request for now and continue the development of the new issue.

**Comment by kjohnson** [comment]
> I also read the canny comment and few comments were looking for the receipt refresh feature.

Fair point. I think the refresh feature would be helpful, but that is secondary to getting the receipt accurate the first time, which this change seeks to address.

@ravinderk could you open a new issue for the refresh feature?

**Comment by ravinderk** [comment]
> Fair point. I think the refresh feature would be helpful, but that is secondary to getting the receipt accurate the first time, which this change seeks to address.
> 
> @ravinderk could you open a new issue for the refresh feature?

Issue create and added to the canny post. https://github.com/impress-org/givewp/issues/5553

**Review by ravinderk — APPROVED** [review]

**Comment by JasonTheAdams** [comment]
@kjohnson @ravinderk Please make sure to do some testing when reviewing and merging a PR. I'm doing some testing before sending out the next release, and I found that donations were _completely_ broken on the multi-step form. After a little digging I found that this PR forgot to add this to the `LoadTemplate` file:
```
use Give\Session\SessionDonation\DonationAccessor;
```
So let's make sure we test what's affected by a PR _before_ merging. 😉

**Comment by kjohnson** [comment]
I could have sworn that I had added that... It would have broken when testing locally. Sorry it got left out.

**Pull request merged**
