### PR TITLE
Chore: Expand highlighted area of the canvas during onboarding

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves [GIVE-849]

## Description

This PR expands the highlighted area for the canvas step of the onboarding tour in the visual builder.

## Affects

Updates a selector in the schema steps configuration.

## Visuals

image

## Testing Instructions

Edit a form in the visual builder
Navigate to the "Build" section
Open the "Options" dropdown in the header
Click "Show Guided Tour" to launch onboarding

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-849]: https://stellarwp.atlassian.net/browse/GIVE-849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by kjohnson** [comment]
Build for QA: https://github.com/impress-org/givewp/actions/runs/10184693651

**Comment by kjohnson** [comment]
@jdghinson can you review the design related changes?

**Review by jdghinson — APPROVED** [review]
Looks good!

**Review by JoshuaHungDinh — APPROVED** [review]
Beautiful! 🎨

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
