### PR TITLE
Refactor: add HeaderImage to classic template

### PR DESCRIPTION
**Pull request by JoshuaHungDinh**
Resolves [GIVE-333]

## Description

This PR reintroduces the HeaderImage to the visual form builder for the Classic template and removes both the headerTextWrapper and the previous logo stylesheets. In the previous implementation the HeaderImage was being constructed with pseudo-elements and css variables to capture the image url. This was difficult to maintain between various layouts. After working through multiple scenarios the decision was made to allow the Header to control its element structure based on the style setting. 

Some of the HeaderImage styles require changes to the title and description color, as well as the overall padding of the header. To accommodate this Ive removed the color and padding from the ClassicFormDesign stylesheet so that It can be updated by the HeaderImage styling. And have reintroduced styling to the MultiStepFormDesign stylesheet so that its layout remains intact.

The 3 HeaderImage styles are:
- Background 
- Center
- Above

## Affects
Classic template Header

## Visuals

https://github.com/impress-org/givewp/assets/75056371/fd6d7c32-5451-4f1e-ae1a-e5c517993e8a

https://github.com/impress-org/givewp/assets/75056371/fe75eab2-2361-48f3-a97d-2b50f0e6346b

## Testing Instructions
- Using the Classic template go to the form builder and add an image.
- Test all 3 styles and test that that the other header settings do not break the layout.
- Delete the image & also try changing the image.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-333]: https://stellarwp.atlassian.net/browse/GIVE-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jonwaldstein — APPROVED** [review]
Great job man!

**Comment by JasonTheAdams** [comment]
@JoshuaHungDinh Asking just because I can't tell from the videos: Is it possible for someone to remove an image without swapping it with another one?

**Comment by JoshuaHungDinh** [comment]
> @JoshuaHungDinh Asking just because I can't tell from the videos: Is it possible for someone to remove an image without swapping it with another one?

Yes! The upload button is switched out for a preview of the selected image. On hover a delete icon becomes visible & clicking anywhere on the element removes the image and the updated styles/structure.

https://github.com/impress-org/givewp/assets/75056371/bdc15d45-d579-46ec-970c-73da8abbc5fb

**Comment by JasonTheAdams** [comment]
Boom! Thanks, @JoshuaHungDinh! Looks great! 🎉

**Comment by JoshuaHungDinh** [comment]
@jonwaldstein "GOOD" b0dd88b13322767d7c6f83dfe8d5a36736386253

**Pull request merged**
