### PR TITLE
Refactor: update html field template to use interweave

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

This updates our html field template to use interweave instead of `dangerouslySetInnerHTML`

## Affects

- html fields

## Visuals

N/A

## Testing Instructions

Make sure the html field works as epected

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by jonwaldstein** [comment]
I realized this might not what people want for our html field as it strips out html like script tags 🤔

**Comment by jonwaldstein** [comment]
Closing for now due to my last comment 😏

**Comment by JasonTheAdams** [comment]
@jonwaldstein One consideration would be to adjust the safety defaults. A couple ideas:
1. Add a separate Scripts block that takes in options — src, defer, async — and generates the tags
2. Add an "Allow Scripts tags" option to the HTML block that's disabled by default, so someone has to knowingly open up the block in such a way.

**Comment by jonwaldstein** [comment]
@JasonTheAdams I like those ideas!  This makes me curious about how customers are actually using this block.  I'm going to poke around CX and support 🤓

**Pull request closed without merging**
