### PR TITLE
Refactor: Reduce spacing between form inputs and error messages

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves [GIVE-824]

## Description

This PR reduces the spacing between the donation form inputs and their related error messages.

## Affects

The bottom margin has been removed from the text and select inputs on the donation form.

## Visuals

| Before | After |
| --- | --- |
| Screen Shot 2024-07-31 at 12 59 36 | Screen Shot 2024-07-31 at 12 58 39 |

| Donor Name Field |
| --- |
| Screen Shot 2024-07-31 at 13 00 42 |
| Screen Shot 2024-07-31 at 12 53 24 |

| Select Input |
| --- |
| Screen Shot 2024-07-31 at 13 01 41 |
| Screen Shot 2024-07-31 at 12 53 49 |

## Testing Instructions

Empty a required field and submit the form.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-824]: https://stellarwp.atlassian.net/browse/GIVE-824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by kjohnson** [comment]
@jdghinson can you take a look at this design related change?

**Comment by kjohnson** [comment]
Build for QA: https://github.com/impress-org/givewp/actions/runs/10184528546

**Review by jdghinson — APPROVED** [review]
All good!

**Review by JoshuaHungDinh — CHANGES_REQUESTED** [review]
@kjohnson This is great, one minor thing I noticed is the Phone field is using flex-gap so its slightly off. It looks like it might be targeting a generic label element so i'm not sure what else might get affected if you change it. I'l let you decide.

Screen Shot 2024-07-31 at 11 52 44 AM

**Comment by kjohnson** [comment]
@JoshuaHungDinh good catch.

It looks like there are a few issues with the phone field, such as the spacing between the label and the custom element. I think the flex gap is actually targeting all givewp fields, but something else is going on with the phone field.

That said, I would suggest creating a separate ticket for the phone field layout.

**Review by JoshuaHungDinh — APPROVED** [review]
@kjohnson Sounds good!

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
