### PR TITLE
Formatting button display correctly when decimals enabled in Multi-Step Form

### LINKED ISSUE #5956: Formatting Display issue with Decimals & Multi-Step Form
## Description

When the Multi-Step Form has decimals enabled, the display adds an extra "$" and breaks the proper formatting for decimal donation levels.

## Step to reproduce

1) Create a multi-step form
2) Enable decimal amounts in step 2 of the form payment section
image
3) Add multiple donation levels under donation options - make sure some, but not all use decimal ie: 23.44
4) load the form and see a display issue with the decimal display.

image

## Acceptance Criteria
- [x]  Decimal does not break donation form levels diaply.

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves #5956

## Description

I find out that a javascript logic was adding additional currency symbol in button title when decimal enabled in multi-step form template.

## Visuals

image

## Testing Instructions

Try to reproduce the issue as direction given in issue.
Note: run `npm run dev` before testing.

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by zjimpress — APPROVED** [review]

**Comment by JasonTheAdams** [comment]
@ravinderk Can you pease give a little more context around this? You're removing a chunk of code that looks like it was introduced for a rather specific reason. Why is that no longer necessary?

**Comment by ravinderk** [comment]
> @ravinderk Can you please give a little more context around this? You're removing a chunk of code that looks like it was introduced for a rather specific reason. Why is that no longer necessary?


`updateFormDonationLevelsLabels` function is an old function in a multi-step form template that was used to update the donation level button title. I think this function was added initially and later we introduce steps in which we also have logic to set up donation level button title. We did not catch this earlier because this function runs conditionally ( only when decimal enabled for template). This logic takes care of decimal and non-decimal button level title, so we do not need this function.

**Comment by JasonTheAdams** [comment]
Excellent explanation! In the future, that's great information to include in a PR description. The goal of a PR description to cover what the solution is, how the solution resolves the problem, and _why_ it's the right solution. Especially in a case like this with refactoring, it's good to explain why old code is no longer necessary.

**Comment by JasonTheAdams** [comment]
@zjimpress Can you please test this again? Ravinder made a change since you last tested.

**Pull request merged**
