### PR TITLE
Refactor: Move feedback link to "more" menu

### PR DESCRIPTION
**Pull request by kjohnson**
## Description

This PR removes the fixed feedback button and adds a new "more" menu item to submit feedback.

## Affects

This removes the fixed feedback button on the bottom right.

## Visuals

image

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204001916754039
  - https://app.asana.com/0/0/1205740299440074

### CODE REVIEW

**Review by alaca — APPROVED** [review]
Awesome cleanup :+1:

**Comment by jdghinson** [comment]
@kjohnson Just make some UI change with the position of the new window icon. Below is a screenshot of how its supposed to look like.

Screenshot 2023-10-17 at 2 26 25 PM

**Comment by jdghinson** [comment]
> @jdghinson updated.
> 
> Screen Shot 2023-10-17 at 11 16 52

Looks good

**Comment by kjohnson** [comment]
Build for QA, see https://github.com/impress-org/givewp/actions/runs/6551142321.

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
