### PR TITLE
Fix: Strauss directory permissions

### PR DESCRIPTION
**Pull request by defunctl**
## Description

I have A PR into Strauss to fix the permissions here: https://github.com/BrianHenryIE/strauss/pull/130

Until that's merged and released, this should work to fix things in your workflows.

Successful Job Here: https://github.com/impress-org/givewp/actions/runs/12285568512

### CODE REVIEW

**Review by JasonTheAdams — APPROVED** [review]
Appreciate the workaround, @defunctl!

Let's hold on merging this for a day or two to see if Brian accepts and merges your fix in Strauss. If it's looking like it may take some time, we'll merge.

**Comment by defunctl** [comment]
@JasonTheAdams no worries, you'll definitely want to add this to your PR if you don't merged this one: https://github.com/impress-org/givewp/pull/7647/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R54

**Comment by jonwaldstein** [comment]
@defunctl thank you!!! 😭

**Comment by jonwaldstein** [comment]
oh wait it was already merged and released in [0.20.1](https://github.com/BrianHenryIE/strauss/releases/tag/0.20.1) 🙌 

@defunctl does this mean we can just use that version and add the dump-autoload line without this PR?

**Comment by defunctl** [comment]
> oh wait it was already merged and released in [0.20.1](https://github.com/BrianHenryIE/strauss/releases/tag/0.20.1) 🙌
> 
> @defunctl does this mean we can just use that version and add the dump-autoload line without this PR?

@jonwaldstein exactly!

**Comment by JasonTheAdams** [comment]
Excited for the quick turnaround! Thanks for submitting the Strauss fix, @defunctl! 🌮 

Closing in favor of the new fix direction.

**Pull request closed without merging**
