### PR TITLE
Include polyfill functions for missing ctype extension

### LINKED ISSUE #6702: Missing ctype extension causes critical error
Many large hosting companies don't have the ctype extension enabled for PHP 7.4 

The fix is to add: "extension=ctype.so" to the bottom of PHP.ini file. The code that appears in line 652 of Str.php – this line:

if (! ctype_lower($value)) {

$value = preg_replace(‘/\s+/u’, ”, ucwords($value));

Additional Information:

https://www.ipage.com/help/article/how-to-enable-ctype-so-extensions-in-php-ini

https://givewp.canny.io/admin/board/bug-reports/p/missing-ctype-extension-causes-critical-error-for-paypal-standard-donations

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #6702

## Description

This PR adds the Symfony [Polyfill Ctype Component](https://symfony.com/components/Polyfill%20Ctype).

## Testing Instructions

- Disable the ctype extension in `php.ini`.
- Make a donation using PayPal Standard.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204035047465899

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@kjohnson do we need / should we use strauss for this?  I am just concerned if an other plugin is using this - there is potential for a conflict.

cc: @JasonTheAdams

**Comment by kjohnson** [comment]
@jonwaldstein Yes, we should use Strauss for this, which I _think_ we are already using in Give core. @JasonTheAdams can you confirm or is there another step to include this in that process?

**Comment by JasonTheAdams** [comment]
@kjohnson Yup! Just add it to the Strauss section in the `composer.json` file, then update its usage to account for the prefixed namespaces, classes, etc.

**Comment by kjohnson** [comment]
@jonwaldstein @JasonTheAdams I've added the `symfony/polyfill-ctype` package to the Strauss extra configuration in `composer.json`, see https://github.com/impress-org/givewp/pull/6703/commits/7b2e6eb14b00dc182944fda6ac30e146081a09e4.

**Comment by kjohnson** [comment]
@JasonTheAdams it looks like the "autoload" in the package's `composer.json` is not updated by Strauss, which throws an error for a missing file.

image

**Comment by kjohnson** [comment]
I added the `symfony/polyfill-ctype` package to the `override_autoload` in Strauss and that seems to have resolved the issue in the automated pipeline.

```
"strauss": {
    "override_autoload": {
        "symfony/polyfill-ctype": {}
    }
}
```

**Review by jonwaldstein — APPROVED** [review]
@kjohnson nice looks good to me, and seems to be working locally. Let's send this off to QA to make sure as well.

**Pull request merged**
