### PR TITLE
Hot Fix: Restore ability to change subscriptions via legacy subscription shortcode

### PR DESCRIPTION
**Pull request by jonwaldstein**
Resolves:
https://feedback.givewp.com/admin/feedback/bug-reports/p/editing-stripe-credit-card-for-recurring-subscriptions-should-work-properly-usin?boards=bug-reports

## Description

While recently updating the Stripe gateway to use the new gateway api, some legacy files were removed.  One of those being `Give_Stripe_Card` which was still being used by give-recurring.  This was preventing subscription updates on the legacy donor dashboard.  This PR adds back the necessary file with just what is currently needed.

## Affects

- Stripe give-recurring subscription updates

## Testing Instructions

- Create a page with the [give_subscriptions] shortcode at [example.com/legacy-subs](http://example.com/legacy-subs)
- Create a form that creates a WP user for all donors (disable guest donations and add registration/login fields
- Disable email access (Settings > General > Access control)
- Create a Stripe CC subscription in an incognito browser
- Navigate after the donation to the [example.com/legacy-subs](http://example.com/legacy-subs) page you created earlier
- Click the "update Payment Info" link.
- You should NOT see a fatal error.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit and/or end-to-end tests
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@kjohnson can you please review this?

@Benunc can you please QA this?

**Comment by Benunc** [comment]
@jonwaldstein The functionality works again, but after updating, it redirects to the donor dashboard, which presumably the users affected by this are not using. Can you have it redirect back to the previous page?

**Comment by jonwaldstein** [comment]
My theory was correct. The page will only redirect to the donor dashboard if it essentially exists.

Screen Shot 2022-06-06 at 3 36 52 PM

**Review by kjohnson — APPROVED** [review]
Looks good, aside from some indentation issues. Too bad that we have to add this back, but that is how it goes sometimes with legacy code.

**Comment by JasonTheAdams** [comment]
@jonwaldstein If possible, can we figure out how to make this work if Donor Dashboard is installed?

**Comment by jonwaldstein** [comment]
> @jonwaldstein If possible, can we figure out how to make this work if Donor Dashboard is installed?

I would imagine we could have some sort of conditional if donor dashboard exists but would have to ask @ravinderk what he thinks. This functionality is inside the legacy parent recurring class so i'm not sure what side effects will occur outside of this context.

**Comment by ravinderk** [comment]
> > @jonwaldstein If possible, can we figure out how to make this work if Donor Dashboard is installed?
> 
> I would imagine we could have some sort of conditional if a donor dashboard exists but would have to ask @ravinderk what he thinks. This functionality is inside the legacy parent recurring class so I'm not sure what side effects will occur outside of this context.

@jonwaldstein this has been already resolved in the Recurring donations addon. Fix merged in `develop` and waiting for release: https://github.com/impress-org/give-recurring/issues/1121

cc: @JasonTheAdams

**Comment by ravinderk** [comment]
> @ravinderk this use case is a little different than what you're referring to (view receipt link). This issue is from updating the subscription inside the `[give_subscriptions]` shortcode.
> 
> Please look at this:
> 
> https://github.com/impress-org/give-recurring/pull/999/files#diff-73d066775aa779770de177431d83ffa4369b5f608ddfb98f90dee4c247a2553b
> 
> You'll see `give_get_subscriptions_page_uri()` is being used as the base url.

@jonwaldstein I agree with you. Redirect works fine when you do not `Override Legacy Donation Management Pages`. That means it is not advisable to use the donor dashboard and legacy subscription list page at the same time

**Comment by Benunc** [comment]
This has passed automated QA and is ready to merge

**Review by Benunc — APPROVED** [review]

**Pull request merged**
