### PR TITLE
Refactor: Update Email template settings in the form builder

### PR DESCRIPTION
**Pull request by JoshuaHungDinh**
## Description

Reference: slack conversation about the cancel option: https://lw.slack.com/archives/C04SLRDD9CK/p1692899169132059

~~This PR includes several changes revolving around the Email Notification Settings. The major change involves the option that allows users to either set the email template fields or cancel the field values~~. 

~~This was done including by including  local state within the email template component to capture all the field changes {```emailTemplateFieldValues``` } and dispatching the actual Form Setting changes when the Set button is clicked.  The original option config is used to update the local state when the Cancel button is clicked to revert the field values~~.

~~Both action buttons "Set and close" & "Cancel" were moved down from the parent container to the EmailTemplateSettings component. I Initially I had looked into raising the state up to the parent in order the Submit the changes. Doing so required moving most the config logic from within the EmailTemplateSettings to the parent also. This made it harder to follow and maintain. Because of this I opted to move the action buttons down and absolutely position them to achieve an identical layout~~. 

The changes reflect the QA tasks below, along with style, typescript type & text changes.

QA Tasks completed within PR: 
- [Email preview has fatal error](https://app.asana.com/0/1203547864809090/1205076251265810)
- [Email Template: Change "save and close" button on modal to "close"](https://app.asana.com/0/1203547864809090/1204927308757485)
- [ Increase spacing between radio buttons under Notification](https://app.asana.com/0/1203547864809090/1204927308757439)
- [ Populate email address field](https://app.asana.com/0/1203547864809090/1204927308757453)

## Visuals

Screen Shot 2023-08-24 at 1 00 20 PM
Screen Shot 2023-08-24 at 1 00 13 PM

## Testing Instructions 
Please note this PR no longer contains logic to cancel the selected email options. As the logic was included than removed in favor of a possible undo feature with gutenberg. 

Please test that the email fields are working as they previously did.
Verify no fatal errors occur on email preview.
Verify default email address is populated in the send test email input.

https://www.loom.com/share/580ee957a673491ea21e01a127ed74f4?sid=93eed98b-fc59-4ed3-836f-aa7064892085

## Pre-review Checklist

-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [x] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205360468064600

### CODE REVIEW

**Review by kjohnson — COMMENTED** [review]
I don't recall seeing the feature to "cancel" changes in the related tasks. Did we decide on this somewhere? I remember voting against adding a "cancel" feature, as this would be a major break from convention of other settings.

**Comment by JoshuaHungDinh** [comment]
@kjohnson, At one point the task was set and close & high priority. I had spoken to @jdghinson and briefly with @pauloiankoski about it during the cycle. Im not sure when it updated to just close. We have been going back and forth mainly working from the Design doc. Nonetheless,  we can remove it if it's that unconventional. Personally I thought the experience did not seem out of the ordinary, but Im biased haha. Would changing the context to reset and keeping it open be viable?

**Comment by kjohnson** [comment]
@JoshuaHungDinh I'm seeing the "Back to template settings" button below the preview, but shouldn't it be in the header?
image

**Review by kjohnson — COMMENTED** [review]
The "Back to template settings" button should be in the modal header, but it is showing below the rendered email preview.

**Comment by JoshuaHungDinh** [comment]
Ah very odd. It should be in the header. Let me take a look.

**Comment by JoshuaHungDinh** [comment]
@kjohnson Looks like I had updated a className but not the style sheet. a27e7fa5d60b8349291effb81ce6bf315c1d6f0e

**Review by kjohnson — APPROVED** [review]
Thanks for updating that button position. To QA!

**Comment by JoshuaHungDinh** [comment]
@kjohnson, Im just leaving a comment here as a reference to some additional changes.

During QA they tested the send email test function. It seemed to be failing when P2P was installed & I was having some difficulties sending the html emails. I have expanded the scope of this PR to address this as well.  Below is a screenshot of the error while P2P was installed.

Screen Shot 2023-08-29 at 4 37 19 PM

Resolved: 69bc2cc4c76caa1b06019f1b6f08a7d123a86dd4
Resolved: 69e849183495634da27ee5b935a6a74fec6b5447

**Review by rickalday — APPROVED** [review]
Passed manual QA tests

**Pull request merged**
