### PR TITLE
Stripe Modal renders without any issue across all screens

### LINKED ISSUE #5422: Stripe Modal should render without any issue across all screens
## User Story

As an admin, I want Stripe Modal to render across all screens without any issue so that I can raise donations.

## Details
I find out the following issue with Stripe Modal:

1. Stripe Modal takes `90%` of any screen, so modal size will be the width on a bigger screen.
image

2. Close modal button does not appear on the small screen when the form has the `Legacy` form template.
3. Modal width varies if Stripe credit card field format changes.
image

4. @Benunc mentioned that image size suggestion in field description creates confusion
ref: https://feedback.givewp.com/bug-reports/p/stripe-modal-should-be-more-predictable-and-the-image-recommendation-clearer
image

## Acceptance Criteria

-   [x] Donor can see a close button on a modal on the small screen when form template set to `Legacy`.
-   [x] Stripe Modal render consistently across screens.
-   [ ] <s>Stripe Modal background image description has been updated.</s> [discussion link](https://givewp.slack.com/archives/C0FAGC83C/p1604324326004700?thread_ts=1604302482.002000&cid=C0FAGC83C)
-   [x] Stripe Mpdal render fine when language set to `Dutch (Nederlands)`
-   [x] Stripe Mpdal render fine when language set to `German`

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves #5422

## Description
In PR https://github.com/impress-org/givewp/pull/5209, we updated tripe modal width logic to fix an issue that causes most of rendering related issues across devices. I updated logic to use `flex` to centralize modal which fixes most of the issues.

## Affects
- I updated modal `max-width` with to `500px` which makes it compatible with most of the language. You can read more about this issue: https://github.com/impress-org/givewp/issues/5206
- In PR https://github.com/impress-org/givewp/pull/5419, to resolve the Stripe issue I added a hidden input field to the donation form to know which type of stripe checkout active and we are using this only on the frontend. I find out that the best way is to add a data attribute to the donation form, so I added a minor fix in this PR.

## Visuals
image
image
image
image
image
image
Screen Recording 2020-10-29 at 11 54 57 PM

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

- Run `num run dev` to review pr with latest scss changes
- Read the issue in details because this pr resolves multiple styling issues
- Test and confirm that this pr pass all test listed under `Acceptance Criteria ` with legacy and multi-step form template

### CODE REVIEW

**Comment by ravinderk** [comment]
@kevinwhoffman Can you guide me on how we can resolve the `4th` point mentioned in issue `Details` section about Stripe Checkout `Background Image` field description (Image size confution).

**Review by henryholtgeerts — APPROVED** [review]
Tested this out locally in various languages, changes all look good! @kevinwhoffman should speak to changes regarding background image description, but the styling changes here work well for me. 👍

**Comment by kevinwhoffman** [comment]
> Can you guide me on how we can resolve the [`4th`](https://github.com/impress-org/givewp/issues/5422) point mentioned in issue `Details` section about Stripe Checkout `Background Image` field description (Image size confusion).

Since @Benunc initially reported the confusion about the image sizes, I am requesting his review of this PR and asking him to provide direction on the contextual documentation that he thinks will clarify the image requirements.

**Comment by ravinderk** [comment]
@Benunc says:

> When I pull down that PR, and npm run dev on it, I can’t get the stripe modal to pop up at all, I’m getting a Error: Error creating payment intent with Stripe. Please try again.
> This may be related to my specific stripe account, or something. The verbiage on the image looks great, though, and as long as someone has tested with an actual image (I don’t see that in any screenshots) This gets my thumbs up.

**Pull request merged**
