### PR TITLE
Fix: illegal offset

### PR DESCRIPTION
**Pull request by pulsovi**
Replaces #6953

## Description

FIX : If neither `$formId` nor the Utils\Frontend allows getting a form ID, the return value of `Template->getActiveID` becomes unpredictable and error-prone.

HOW : The PR bailout before call of get_meta, returning `''` if no ID found.

WHY : `null` is the most intuitive value to retrieve in such a situation, but to avoid breaking change, use empty string as a falsy value which will be correctly handled by `Form\LoadTemplate@setUpTemplate`.

## Affects

It's a fix, it not affects any feature, only bugs.

## Testing Instructions

In a context situation where `Frontend::getFormId()` returns `null`.
Call `Give()->form_meta->__add_meta()` with an improbable value (such "I'm not a template") as the only parameter.
Then call `Template::getActiveID()` without any parameters, the return value is the improbable value you provide to `__add_meta`, which should not be the case.

The PR make it returning `null` instead.

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@pulsovi thanks for the PR!

@ravinderk can you please review this when you get a chance?

**Comment by ravinderk** [comment]
@pulsovi Thank you for your valuable time to fix this issue. Donation form template functions should be called in a specific environment. These functions can return unexpected results if used outside of context. Can you explain how did you catch this issue? Do you have steps to reproduce this issue?

**Comment by jonwaldstein** [comment]
@pulsovi circling back here, do you remember how you encountered this issue?  It seems as @ravinderk has pointed out that these functions need to be called inside the context of a form.  We appreciate you taking the time to create this PR but are just having trouble reproducing the issue.

**Comment by jonwaldstein** [comment]
@pulsovi hey again! no problem, we appreciate you taking the time to submit this PR.  We will close this for now as we can not replicate - but please feel free to re-open if the problem comes up again. Thanks!

**Pull request closed without merging**
