### PR TITLE
SEPA Payment Method

### PR DESCRIPTION
**Pull request by flobbie**
## Description
Integration of SEPA payment method from Stripe: https://stripe.com/docs/payments/sepa-debit
This is a widely used payment method in Europe.

## How Has This Been Tested?
In a testing environment I processed production SEPA payments. For this SEPA needs to be activated in Stripe which can only be activated after processing credit card payments and with a European address.

## Screenshots (jpeg or gifs if applicable):
Screenshot from 2019-12-01 20-07-03

## Types of changes
New feature (non-breaking change which adds functionality) of adding SEPA fields and configuration to GiveWP.
As this is a bigger feature, I am open for advice and support on better integration into GiveWP.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
Great looking PR @flobbie 👍 

We really appreciate the contribution. We're going to review this in depth and provide some feedback.

**Comment by flobbie** [comment]
@DevinWalker: Do you have any feedback or remarks?

This feature is used in production by us since a few days and already processed a few donations.
If you have any questions, don't hesitate to contact me.

**Comment by DevinWalker** [comment]
Hey @flobbie the biggest hurdle we're having is that our Stripe account doesn't have access to test SEPA payments. We've tried to get Stripe to enable that for us but no luck thus far. We're going to take a look again at this within the next couple weeks. Thanks for checking back! Follow along on the issue we created #4313

**Comment by flobbie** [comment]
Hello @DevinWalker, are there any news yet? There is also no update on the issue you created.

Maybe I can support you as an European citizen with access to Stripe SEPA? We can also talk about other ways of integrating it e.g. as a plugin.
You can also directly contact me via email: info@florianbackmeier.de

**Comment by DevinWalker** [comment]
Hey @flobbie - I just emailed you 👍

**Comment by sagararyal** [comment]
@DevinWalker @flobbie any updates on this?

I can also help provide stipe account with SEPA for testing.

**Comment by Benunc** [comment]
Hi folks, can you invite ben@benandjacq.com to the stripe account that has SEPA access so that I can test it? (I'm the head of Support for GiveWP)

**Comment by DevinWalker** [comment]
@flobbie thanks for this PR - I'm closing it now as we're just about complete with our integration. I appreciate the help!

**Comment by flobbie** [comment]
@Benunc I invited you to my stripe account with SEPA activated.

**Pull request closed without merging**
