### PR TITLE
Add support for 3D Secure create card when process donation with PayPal Donations

### LINKED ISSUE #4983: Donor should able to process donation with 3D secure card with PayPal commerce advanced card fields
## User Story

As a donor, I want advanced card fields to support a 3D card so that I can donate.

## Details
Advanced card fields already added in core with https://github.com/impress-org/givewp/pull/4977 PR, but it does not work with a 3D card. We can follow this [PayPal doc](https://developer.paypal.com/docs/business/checkout/add-capabilities/3d-secure/) to added support.

## Acceptance Criteria
-   [x] Donor can process donations with a 3D secure card.

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves #4983 

## Description
This PR adds 3DS support for credit cards.

Note: According to my understanding seems to resolve the issue but I left a few questions for PayPal team:
- https://givewp.slack.com/archives/C015XD31J5S/p1596751233004400
- https://givewp.slack.com/archives/C015XD31J5S/p1596809998002100

## Affects
This does not affect existing features.

## Visuals
image
image

## Pre-review Checklist
-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions
You can use the following 3DS credit cards to test this pr with advanced card fields:https://cardinaldocs.atlassian.net/wiki/spaces/CCen/pages/400654355/3DS+1.0+Test+Cases

Few other non 3DS credit cards you can use: 
`4242424242424242`,
`5020047464951918`: `not supported by advanced card fields`. you will get an error when you use this card.

image

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
@ravinderk I may be doing something wrong, but I tried using the `4000000000000002` card from [the link you provided](https://cardinaldocs.atlassian.net/wiki/spaces/CCen/pages/400654355/3DS+1.0+Test+Cases) and just got an error in the console: 
image

**Comment by ravinderk** [comment]
@JasonTheAdams I got update from the PayPal team and Please hold on review. I will update this pr.

ref: https://givewp.slack.com/archives/C015XD31J5S/p1596809998002100

> PayPal team says: it's up to your business logic if you want to process the transaction when the liability is still with the Merchant

@JasonTheAdams What we can do above situation. Currently, I am showing donor an error notice if liability is on the merchant and does not allow him to process the donation.

**Comment by JasonTheAdams** [comment]
Yeah, if 3DS doesn't succeed, then it's likely to do with the donor's bank. The best we can do is inform the donor that either we were not able to authenticate their bank, or their authentication failed. Not much more to be done at that point.

**Comment by ravinderk** [comment]
@JasonTheAdams can you give me a text for notice, I will replace exiting failed donation notice with this.

**Comment by JasonTheAdams** [comment]
If we can separate a failure to authenticate with authentication failure, then:

**Failed to Authenticate:**
```
There was a problem authenticating your payment method. Please try again. If the problem persists, please try another payment method.
```

**Authentication Failure**
```
Your payment method failed to authentication with the issuer. Please try again. If the problem persists, please try another payment method.
```

If you can't differentiate the two scenarios, then go with the first message.

**Comment by ravinderk** [comment]
@JasonTheAdams I implemented `Failed to Authenticate` notice and code recommendation from the PayPal team.

this pr is ready to review.

**Comment by ravinderk** [comment]
@JasonTheAdams I am facing issues with `Multi Step Form` template. I will update you once this pr ready to review.

**Comment by ravinderk** [comment]
@JasonTheAdams I confirm that this pr is working fine with `Multi Step Form` template

**Pull request merged**
