### PR TITLE
fix: Sequoia form template now matches Figma designs

### LINKED ISSUE #4789: fix: Sequoia form template should match Figma designs
# Bug Report

## User Story
As a user, I want the Sequoia form template to match Figma designs so that I have a polished, cohesive checkout process that meets rudimentary accessibility needs. 

## Details
Currently, the Sequoia form tempalte is largely ready for testing, however certain styles do not exactly match the Figma designs. Some of these include spacing/padding and font sizes, as well as hover and focus states. By ensuring that these states are supported, we're also making significant progress toward improving the accessibility of the Sequoia form template.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Visuals
Screen Shot 2020-06-03 at 11 53 11 AM

## Acceptance Criteria
- [x] Add chevron icon to advance buttons
- [x] Reduce padding below form title
- [x] Reduce border width between goal stats
- [x] Decrease top/bottom padding of prominent checkboxes (fee recover, newsletter, etc)
- [x] Only display "Secure Donation" notice on SSL encrypted sites
- [x] Add focus state for advance/donate now button
- [x] Add focus state for amount buttons
- [x] Add focus state for amount input area
- [x] Add focus states for payment information fields
- [x] Add focus states for payment gateway tabs
- [x] Improve/define tab order of elements
- [x] Improve offline donation styles
- [x] Amount input font should match Figma

### PR DESCRIPTION
**Pull request by henryholtgeerts**
## Description
Resolves #4789
This PR introduces minor style and JS improvements to the Sequoia form template so that it more closely matches original designs proposed in the Figma boards. Previously, when a donor viewed forms using the Sequoia form template it was largely consistent with designs laid out in the Figma boards. This PR improves fonts, spacing and focus states to polish off the Sequoia form template's desktop appearance.

## Affects
This PR primarily impacts the Sequoia form template assets and the Sequoia template class.

## What to test
Try enabling and disabling various setting for the Sequoia form template and it's addons. With each different configuration, is the form's frontend appearance matched to designs originally proposed in the Figma boards (see: https://www.figma.com/file/jaVXDA4wjQD9OqTi0l9KQe/Form-Templates?node-id=2510%3A113&viewport=-259%2C1586%2C0.5).

When using keyboard navigation, do inputs have useful focus states? When selecting a text input, textarea, select or multiselect field does is the border highlighted using the form's primary color setting?

## Screenshots:
DesktopDemo

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by henryholtgeerts** [comment]
> @henryholtgeerts can you fix the merge conflict here?

Done! Ref: https://github.com/impress-org/givewp/pull/4790/commits/fe5fd3ad7b2d3768b86b17dc29f1b39a1ccc4d10

**Comment by ravinderk** [comment]
> Ravinder please look into why I'm seeing the email access prompt instead of my donation receipt. As well, please review why I'm unable to download the PDF receipt using the mobile preview in Chrome.

@DevinWalker receipt issue (email access prompt) has been resolved. I noticed that the download receipt pdf issue can be reproduced with legacy receipts also. I am looking into this and I will update you soon.

**Comment by ravinderk** [comment]
@henryholtgeerts I find out following issue:

- [ ] Error notice hide behind header.
image

- [ ] Lable in the screenshot does not appear after a page redirects back to a donation form on error.
image

- [ ] Long notice string breaks donation form style.
image


Steps to reproduce.
```
<?php
give_set_error( 'customError', 'Lorem ipsum dolor sit amet, id duoerroradmodumhonestatis,utroquetheophrastusmeaex.Hastollitoportereaccusamusat,idetiamsaepescripta vel, omittam praesent ex usu. Cu nam error ridens adversarium. Et meis tempor his. Quo ferri prompta constituto id, eum cu affert ornatus cotidieque.');
	give_send_back_to_checkout();
```

To reproduce the above issues you can add this test code before: https://github.com/impress-org/givewp/blob/bf4c43da8d2c1ba360ad7c3502e6c3dc3574543d/includes/process-donation.php#L206

**Comment by henryholtgeerts** [comment]
> @henryholtgeerts I find out following issue:
> 
> * [ ]  Error notice hide behind header.
>   image
> * [ ]  Lable in the screenshot does not appear after a page redirects back to a donation form on error.
>   image
> * [ ]  Long notice string breaks donation form style.
>   image
> 
> Steps to reproduce.
> 
> ```
> <?php
> give_set_error( 'customError', 'Lorem ipsum dolor sit amet, id duoerroradmodumhonestatis,utroquetheophrastusmeaex.Hastollitoportereaccusamusat,idetiamsaepescripta vel, omittam praesent ex usu. Cu nam error ridens adversarium. Et meis tempor his. Quo ferri prompta constituto id, eum cu affert ornatus cotidieque.');
> 	give_send_back_to_checkout();
> ```
> 
> To reproduce the above issues you can add this test code before:
> 
> https://github.com/impress-org/givewp/blob/bf4c43da8d2c1ba360ad7c3502e6c3dc3574543d/includes/process-donation.php#L206

Error notice position and styles have been improved, ref: https://github.com/impress-org/givewp/pull/4790/commits/3db96b0e9df620b0040d36a2086c8a6c7946a01a and https://github.com/impress-org/givewp/pull/4790/commits/41f18f994a2cf8bab9c6b4f7f4398e614dda83f1

Screen Shot 2020-06-15 at 11 26 57 AM

**Comment by DevinWalker** [comment]
Looks really great now. 👍 

I'm going to update the "Take the Survey" to a link to our upcoming "Form Template" documentation.

**Pull request merged**
