### PR TITLE
Donor Dashboard history now includes pending donations

### LINKED ISSUE #5714: Donor Dashboard history should include pending donations
## User Story

As a donor, I want the donation history tab of my Donor Dashboard to include pending donations so that there is no difference between my experience in the Donor Dashboard compared with the Donation History shortcode.

## Details

From Canny:
On history page donor can see completed and pending donations but not on donor dashboard.

## Expected Behavior

Donation History tab should include pending donations.

## Steps to Reproduce

1. Go to Donor Dashboard
2. Select Donation History tab
3. Notice that donations marked pending do not appear

## Visuals

922c0127692136ea068395cbc151076d

ac2c80bf0e211e21ce732601188ae021

## Acceptance Criteria

-   [x] Donation History tab includes Pending Donations

### PR DESCRIPTION
**Pull request by henryholtgeerts**
Resolves #5714 

## Description

This PR introduces logic to ensure that all donation statuses are included in querying for the Donation History tab of Donor Dashboard. Along the way, another bug was resolved which sometimes lead to formatting issues in the Giving Stats section when no completed donations where found.

## Affects

This PR affects backend logic for the Donation History tab and dashboard content of the Donor Dashboard.

## Visuals

Screen Shot 2021-03-15 at 6 00 09 PM

## Testing Instructions

1. Go to Donor Dashboard
2. Select Donation History tab
3. Notice that donations of all donation statuses appear
4. 
## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by JasonTheAdams — CHANGES_REQUESTED** [review]
Great work, @henryholtgeerts! I'd like to tweak the colors to match how they show up in the admin-side:

Status colors gif

**Comment by henryholtgeerts** [comment]
@JasonTheAdams Good thinking! Done, ref: https://github.com/impress-org/givewp/pull/5721/commits/6b3a8750098b89e3a657fe885165ff11d1e1ed61

**Comment by JasonTheAdams** [comment]
@henryholtgeerts Pending is showing up as gray instead of yellow.

**Comment by henryholtgeerts** [comment]
@JasonTheAdams  Ah! Good catch -- done, ref: https://github.com/impress-org/givewp/pull/5721/commits/d74f331eb3ece2750d06c8d14a1f42b380416186

**Review by JasonTheAdams — APPROVED** [review]
Looking good! ✨

**Pull request merged**
