### PR TITLE
Refactor: Allow blocks to move freely about the form builder

### PR DESCRIPTION
**Pull request by kjohnson**
## Description

This PR enables field and element blocks to be inserted between sections - in which case the block will be wrapped in a new section. This supports the quick inserter, drag-and-drop, and moving blocks.

## Affects

 The `dispatchFormBlocks` callback now modifies block data to enforce the `form > section > field/element` hierarchy.

## Visuals

Peek 2023-09-20 16-18

Peek 2023-09-20 16-15

## Testing Instructions

Insert blocks all over the place - no restrictions :sunglasses:

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203980971550726
  - https://app.asana.com/0/0/1205550233964873

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@kjohnson this is amazing! 😭 

One tiny thing we need to update here is the "ADDITIONAL FIELDS" promo for ffm.  It has some conditional to display which I think can be removed now since all blocks display

**Comment by JasonTheAdams** [comment]
I can't believe how few lines of code @kjohnson accomplished this in. 😭 🔥

**Comment by jonwaldstein** [comment]
> I can't believe how few lines of code @kjohnson accomplished this in. 😭 🔥

It defies logic 🪄

**Comment by kjohnson** [comment]
@jonwaldstein I update the FFM Additional Fields promo, see https://github.com/impress-org/givewp/pull/6958/commits/e739823393a692a97a564237f8868972e1c0f77a.

**Review by jonwaldstein — APPROVED** [review]
I'm so happy about this 😭

**Review by rickalday — APPROVED** [review]
Passed manual tests.

**Pull request merged**
