### PR TITLE
Tests: add autoloading and namespaces

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

This updates our Test suite to include namespacing with autoloading. The new testing namespace will be 
`namespace GiveTests` and point to the `tests` folder.  This now gives us the ability to use Traits in our tests like the new `RefreshDatabase`.

Extending the new `\GiveTests\TestCase` and adding `RefreshDatabase` as trait to your test will do some database cleanup on tearDown.

There was also some new organization done regarding the folder structure of tests to make things flatter.

The main bootstrap file was also cleaned up to reduce the amount of duplicated code.

Screen Shot 2022-08-18 at 9 21 32 AM

## Affects

- Refactored the main bootstrap file & location (**Note:** this path will need to be updated for add-ons with unit tests)
- Added a new main `TestCase` forked from `Give_Unit_Test_Case`
- Updated the location of tests
- Updated unit tests with namespaces
- Used the new `RefreshDatabase` trait for some tests

## Testing Instructions

Run the unit tests

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@unreleased` tags included in DocBlocks
-   [x] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by kjohnson** [comment]
Reminder that developers will need to run `composer dumpautoload` after pulling in this change.

**Review by kjohnson — COMMENTED** [review]
@JasonTheAdams @jonwaldstein @ravinderk is it safe to delete these "incomplete" tests? For example:

```php
public function testSubscriptionShouldCancel()
{
    $this->markTestIncomplete();
}
```

**Comment by jonwaldstein** [comment]
> @JasonTheAdams @jonwaldstein @ravinderk is it safe to delete these "incomplete" tests? For example:
> 
> ```
> public function testSubscriptionShouldCancel()
> {
>     $this->markTestIncomplete();
> }
> ```

Those are typically added when a developer is working on something and knows they need to write a test for it - but for whatever reason hasn't written it yet. I'm inclined to keep them as a reminder to go back and finish writing the test that's currently incomplete.

**Review by kjohnson — APPROVED** [review]
Looks good to me! Tests run locally. I like the config contract 🦾

**Pull request merged**
