### PR TITLE
Create account checkbox is hidden when guest registration is disabled.

### LINKED ISSUE #5515: Create an account checkbox should only display when Guest Checkout is enabled.
## User Story

As a donor, I want to only see the "Create Account" checkbox if registration is optional.

## Details

Currently, when Guest Checkout is disabled, the Create Account checkbox is disabled - as registration is required. The input itself is checked by default, but the rendering with the label does not reflect a checked state because it is disabled. This create the illusion that registration is optional and no checked by default.

## Expected Behavior

The "Create Account" checkbox should only be visible if registration is optional, ie Guest Checkout is enabled. Otherwise, the input should be hidden from the user when registration is required.

## Steps to Reproduce

1. Sequoia / Multi-Step Form
1. Disable Guest Checkout
1. Enable Registration + Login

## Acceptance Criteria

-   [ ] When Guest Checkout is `enabled`, the Create Account checkbox is displayed.
-   [ ] When Guest Checkout is `disabled`, the Create Account checkbox is not displayed.

### PR DESCRIPTION
**Pull request by kjohnson**
Resolves #5515

## Description

With Guest Donations disabled and register + login fields selected, hide the create account checkbox and label.

## Affects

This hides the input, which is checked by default - since guest registration is disabled and an account is required (so we are creating an account).

### Sequoia

| Before | After |
| --- | --- |
| Screen Shot 2021-01-14 at 15 14 49 | Screen Shot 2021-01-14 at 15 12 36 |

### Legacy

| Before | After |
| --- | --- |
| Screen Shot 2021-01-14 at 15 14 16 | Screen Shot 2021-01-14 at 15 13 40 |

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

1. Create a form with guest donations disabled, and registration + login fields selected
1. From a logged-out browser, view the form
1. The create an account box is not visible
1. Submitting the form creates an account

### CODE REVIEW

**Comment by DevinWalker** [comment]
@kjohnson I have a few questions about this PR. I created this short video to explain myself: https://www.loom.com/share/4e06b8eb2eb04a0c8f9ef21e05d1725b

Please let me know what your thoughts are on my inquiries. cc: @JasonTheAdams

**Comment by JasonTheAdams** [comment]
Creating a login as the user donates is exactly what is done on GiveIO. It's done on GiveIO without any indication to the user. Since the user is providing their email for a donation anyway, I don't think this crosses any GDPR lines as we're not doing anything with their information we otherwise wouldn't (store it in the database and tie it to the donation).

I think the question becomes whether we want the user to be aware that an account is being created for them. I would need more context as to _why_ folks are creating logins to give the best answer on that. On GiveIO it's so the user can manage their subscriptions and such, but they don't even need to be made aware.

Since we currently have one customer asking for this to be cleared up in the form of the checkbox being removed, I don't think we need to dig any deeper for now. Certainly having the checkbox removed clears up any confusion. Later, if we get requests to be able to provide the user with some message, we can make that optional and editable at that time.

**Comment by DevinWalker** [comment]
@JasonTheAdams that makes sense to me.

**Comment by ravinderk** [comment]
@JasonTheAdams Do we want to make this change to both forms template. Previously I noticed that it was affecting legacy for template: https://github.com/impress-org/givewp/pull/5516#pullrequestreview-556564591

**Comment by JasonTheAdams** [comment]
Yes, ideally this should adjust both legacy and multi-step templates.

**Comment by kjohnson** [comment]
@DevinWalker @JasonTheAdams recap on the above conversation:

With "Guest Donations" disabled, and the "register + login" fields selected, the "Create account" checkbox is checked and hidden which will create an account when the form is submitted.

**Comment by kjohnson** [comment]
@JasonTheAdams just waiting on your approval as a reviewer. As far as I understand @DevinWalker is on board with this direction.

**Review by JasonTheAdams — APPROVED** [review]
I found one issue while testing, but it's not in the scope of this PR. I made a [Canny post](https://feedback.givewp.com/bug-reports/p/user-login-on-multi-step-form-should-not-duplicate-the-name-and-email-fields) to track user feedback.

This is good to go! 👍

**Pull request merged**
