### PR TITLE
Update warning message for unsuccessful PayPal account onboarding 

### LINKED ISSUE #5517: Log should be created on unsuccessfully PayPal account onboarding
## User Story

As an admin, I want to review what went wrong when PayPal onboarding.

## Details

Few plugin users are facing issues with PayPal onboarding and issues are not easily reproducible. Response from PayPal c can tell us more about why onboarding fails.

## Acceptance Criteria

-   [ ] <s>A log generates on onboarding error.</s>
-   [x] Add merchant status check API response to warning message review list.

### PR DESCRIPTION
**Pull request by ravinderk**
Resolves #5517 #5518 

## Description

We do not have a step to reproduce this step. We need more information to catch the cause of this issue. As per the initial finding, it seems that the cause of the error is on the PayPal server which we can not control. We are actively working with the PayPal team to resolve this issue. I added merchant status check API response in the warning message review list. I also added an action step to resolve the on-boarding issue. 

## Affects

I refactor code to take benefit of DI which does not break the existing features.

## Visuals

Error message sample for invalid merchant id:
image

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in a related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

- Except `merchant status` check all PayPal error consider as unknow that means error message will be different (a little bit ).
- PayPal error message display on basis of country region ( North America vs all ).  An error message will modify on the basis of the PayPal account country.

image

- **Notice on PayPal Modal close:**
A notice will display when the admin closes the PayPal modal without completing onboarding steps.

- **Notice on missing merchant id:**
You will get notice an `$errors array in `onBoardingRedirectHandler::savePayPalMerchantDetails` under `if` condition. set `if` condition to `true ` to force this error.

- **Notice on invalid client id and secret:**
You will get notice an `$errors array in `onBoardingRedirectHandler::didWeGetValidSellerRestApiCredentials` under `if` condition. set `if` condition to `true ` to force this error.

- **Notice on failed to create webhook:**
You will get notice an `$errors array in `onBoardingRedirectHandler::setUpWebhook` under `catch` condition. Throw exception from `try` to execute  code in `catch`.

- **Notice on failing merchant status check:**
To generate error you can unset `primary_email_confirmed` array key from `$onBoardedData` array in `onBoardingRedirectHandler::isAdminSuccessfullyOnBoarded` function. You must see updated notice as shown in above screenshots.

- **Hide PayPal gateway option on frontend**
Admin will be connected successfully even he failed on `merchant status check` that means PayPal gateway is not ready to accept payment, so it will be from the frontend. To generate error you can unset `primary_email_confirmed` array key from `$onBoardedData` array in `onBoardingRedirectHandler::isAdminSuccessfullyOnBoarded` function. You must see updated notice as shown in the above screenshots.

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
Here are the instructions for users as I think of them:

In the following, depending on the country, I will refer to _[contact paypal]_ which means to display one of the following two depending on whether the account is in North America or not.
- North America: "Please call a PayPal support representative at 1-855-456-1330 and relay the following message:"
- Everywhere Else: "Please reach out to PayPal support from your PayPal account Resolution Center, and relay the following message:"

Due to the fact that some onboarding errors are completely invisible to GiveWP (e.g. they get an error page during the onboarding popup flow), please display the following message in a calm and friendly design. If an error does occur, though, _replace_ it with the new instructions.

### Standard Message
Having trouble connecting to PayPal?

_[contact paypal — but do not include the "and relay the following..." part]_

### Failure due to account not being fully set up in some way
Warning, your account is not ready to accept donations.

Something is not quite ready with your PayPal account to accept online donations. _[contact paypal]_
```
Greetings!

I am trying to connect my PayPal account to the GiveWP plugin for WordPress. I have gone through the onboarding process to connect my account, but when I finish I'm given the following message from GiveWP:
[Insert flag list here]

Please help me resolve these account errors so I can begin accepting payments via PayPal on GiveWP.
```

When you have resolved the issues with your account, please click the "Re-Check Account Status" below to have GiveWP check with PayPal to see if everything is ready.

### Unknown Onboarding Error
Warning, your account is not ready to accept donations.

There was a problem connecting your account to PayPal. We're not entirely sure what went wrong, but we want to help you figure out what happened. _[contact paypal]_
```
Greetings!

I am trying to connect my PayPal account to the GiveWP plugin for WordPress. I have gone through the onboarding process to connect my account, but when I received the following error from PayPal:
[Show error here]

Please help me resolve these account errors so I can begin accepting payments via PayPal on GiveWP.
```

I would love some input from @DevinWalker, @Benunc, and @mathetos on this. Devin if you have any design ideas please pitch in.

**Comment by ravinderk** [comment]
@JasonTheAdams As pe suggestion implemented the following changes to this pr:
- I implement a few errors checkpoint which can help to find out PayPal onboarding errors.
     - Added PayPal merchant id validation which we get from return URL from returning from PayPal modal.
     - Added PayPal client rest API credential validation which we request from PayPal after saving the merchant details.
     - Added exception handler when creating PayPal webhook.
     
- As you mentioned in your comment I implemented the `Failure due to account not being fully set up in some way`  and `Unknown Onboarding Error` error template.

- Added logic to stop loading payment gateway option and frontend asset till PayPal account is not ready to accept payments.

Error message sample for invalid merchant id:
image


Remaining:

- Implication of `Standard Message` error template on close PayPal onboarding modal.
- I need to test the above change with a legacy and multi-step form template.

**Review by JasonTheAdams — CHANGES_REQUESTED** [review]
I did the following and started getting this notice:
```
Notice: Trying to access array offset on value of type null in /Users/jasonadams/Local Sites/givewp/app/public/wp-content/plugins/give/src/PaymentGateways/PayPalCommerce/Models/MerchantDetail.php on line 156
```
1. In the `onBoardingRedirectHandler` on line 106 I forced the condition to true to create the error
2. Connect an account and trigger an error (which looks great)
3. Reset the last condition to work as normal 
4. In the same file on line 241 force the condition to pass to prompt failure
5. Click the "Re-Check Account Status"

I then successfully connected an account, but it took me to a page with nothing but the same error. After going to `/wp-admin`, though and and going back to settings the error stopped showing up.

**Comment by ravinderk** [comment]
@JasonTheAdams I reviewed your step and I find out that you were not connected to PayPal. I updated logic to show the `Re-Check Account Status` link only if the account connected. Admin will also see the access token information in the error list because that will help admin to understand why he did not get client credentials.

Commit: https://github.com/impress-org/givewp/commit/eece79d5a6dd74e5f5a5a05ec7b79664699830a5

**`Re-Check Account Status` will not show up on the screen if an account is not connected**
image


Commit: https://github.com/impress-org/givewp/commit/c28d204f34007843db6e36301172e4112aad3624
**Access token information in error list**
image

**Comment by ravinderk** [comment]
@JasonTheAdams I noticed a few PHP notices because of the missing merchant details in the database. Please keep eye on `debug.log` when testing.

**Comment by JasonTheAdams** [comment]
@ravinderk I made a couple of minor tweaks, but I'm going to hold off on releasing this today so we can hammer out two things:
1. Why are those merchant detail errors happening? I found that sometimes the errors happened and sometimes they didn't. I noticed one time that the reason was the Gateway server request timed out. I tried extending the timeout to 10 seconds, but still saw it. I tried again and it worked. So I'm not sure what's going on there.
2. I noticed this time that you set up the mutation observer per PayPal's suggestion. I didn't actually intend that to be in the scope of this PR. Since it's there, is it attempting to check the status of the account? Or does it just assume there was a problem if the user closes the tab? Right now it seems to just throw the prompt to contact PayPal if the user is having trouble, but I don't want to assume this is the case; they could be connected and just didn't click the last button.

Let's touch base first thing in the morning to see if we can wrap this up. If it looks like it's going to take longer, then we'll release tomorrow anyways and plan to put out a hotfix with this as soon as we wrap it up.

**Comment by ravinderk** [comment]
@JasonTheAdams These are following answers to your questions:

> Why are those merchant detail errors happening? I found that sometimes the errors happened and sometimes they didn't. I noticed one time that the reason was the Gateway server request timed out. I tried extending the timeout to 10 seconds, but still saw it. I tried again and it worked. So I'm not sure what's going on there.

I was not able to reproduce merchant details php notices. I made few tweak to code to prevent other php notices: 
 - https://github.com/impress-org/givewp/pull/5522/commits/c7e4073341c9a655c98c2a166622728afc7a4d01 : This will prevent `PHP Notice:  Undefined index: expiresIn`
 - https://github.com/impress-org/givewp/pull/5522/commits/1c2c8d5a8482f8ccb648c41e4023949084589feb: This will prevent `PHP Notice:  Undefined index: client_id` `PHP Notice:  Undefined index: client_secret`



> I noticed this time that you set up the mutation observer per PayPal's suggestion. I didn't actually intend that to be in the scope of this PR. Since it's there, is it attempting to check the status of the account? Or does it just assume there was a problem if the user closes the tab? Right now it seems to just throw the prompt to contact PayPal if the user is having trouble, but I don't want to assume this is the case; they could be connected and just didn't click the last button.

Yes, you are correct. Currently if some close Paypal onboarding window then assume that they are facing trouble to complete process. We do not have any way to complete onboarding process if Paypal user onboarded in window and does not click on last button which redirect him to same site with merchant details which help us to complete process. In that case we can edit prompt message to provide guidance to this user flow also. Lets discuss this today.

**Comment by ravinderk** [comment]
@JasonTheAdams Onboarding troubleshooting message has been updated as we discussed: https://github.com/impress-org/givewp/compare/854b5d2d9d9a...c4bb99400d39

image


image

**Review by JasonTheAdams — APPROVED** [review]
Great work on this, @ravinderk! I really hope this helps many folks out with PayPal onboarding!

**Pull request merged**
