### PR TITLE
Currency Switcher input and message area are styled in Multi-Step forms

### LINKED ISSUE #5217: Currency Switcher input and message area should styled in Multi-Step forms
## User Story
As a user, I want the Currency Switcher input and message area to my styled consistently with the Multi-Step form so that I have a cohesive donation experience on sites using the Currency Switcher addon.

## Details
There is a PR open in the Currency Switcher which makes it possible for the required select field and message area to load and work as expected. Before that PR can be merged, the Multi-Step form needs to be ready for these new elements, with styles than can handle them to ensure they conform to the Multi-Step form's aesthetic as a whole.

## Additional Context
This is the associated PR in Currency Switcher: https://github.com/impress-org/give-currency-switcher/pull/278

## Acceptance Criteria
-   [ ] Currency Switcher input is minimal and works within the existing Donation Amount input area
-   [ ] Currency switcher message is styled consistently with other similar messages in the Multi-Step form (like Fee Recovery message)
-   [ ] Currency Switcher input is keyboard accessible

### PR DESCRIPTION
**Pull request by henryholtgeerts**
**_NOTE: This PR is dependent upon changes to the Currency Switcher in an associated PR. See that PR here: https://github.com/impress-org/give-currency-switcher/pull/278, and setup locally before testing this PR._**

Resolves #5217 

## Description
This PR introduces styles for the Mutli-Step form which improve compatibility with the Currency Switcher addon. In order to see these improvements you'll need have Currency Switcher setup in a form, and using this PR related to currency switcher: https://github.com/impress-org/give-currency-switcher/pull/278

## Affects
This PR affects Multi-Step form styles, specifically regarding presentation of the Currency Switcher input and message area.

## Visuals
Currency Switcher in action:
Aug-28-2020 13-33-32

With currency acronym enabled:
Screen Shot 2020-08-28 at 1 34 36 PM

With currency acronym enabled and currency position set to `after`:
Screen Shot 2020-08-28 at 1 36 38 PM

## Pre-review Checklist
-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Keyboard accessible
-   [x] Changelog updated
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions
1. Activate the Currency Switcher add-on (using this PR: https://github.com/impress-org/give-currency-switcher/pull/278)
2. Add multiple global currencies
3. Add new donation form
4. Select Multi-Step Donation Form template
5. Try to make a donation in different currencies

### CODE REVIEW

**Comment by kevinwhoffman** [comment]
I'm setting the base branch back to `develop` since this change is not ready for GiveWP 2.8.0. See the requested changes in the related Currency Switcher PR: https://github.com/impress-org/give-currency-switcher/pull/278#pullrequestreview-479046225

**Comment by JasonTheAdams** [comment]
This looks great, @henryholtgeerts! The only thing that looked a bit strange to me was the double focus ring:
image
Is it necessary to have the focus ring on the currency dropdown?

**Comment by JasonTheAdams** [comment]
@kevinwhoffman I noticed in the other PR that you brought up the focus ring, but only to have it not peek out the right side of the amount. Do you think we should leave the focus ring? It just looks strange to me.

**Comment by henryholtgeerts** [comment]
After a brief call last Friday, and some improvements to the currency switcher focus state introduced in this PR, it was decided that these changes are approved for merge.

**Pull request merged**
