### PR TITLE
Fix: `give_multi_form_goal` shortcode escapes rendering properly

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

It was brought to our attention that the `give_multi_form_goal` shortcode was missing proper data esacping for it's attributes during render.  This PR updates the view and related progress view to escape all dynamic content.

## Affects

The `give_multi_form_goal` shortcode

## Visuals

N/A

## Testing Instructions

**Vulnerability**

Pull the branch and make sure this doesn't trigger an alert: `[give_multi_form_goal image='" onerror="alert(/XSS/)"']`

**General**

Make sure the shortcode and block still work properly

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203717822928716

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@JasonTheAdams this is ready for review.

**Review by JasonTheAdams — APPROVED** [review]
This looks good to me, @jonwaldstein! Please send this off to QA asap.

**Review by rickalday — APPROVED** [review]
Passed manual tests

**Review by Benunc — APPROVED** [review]
also passes automated tests, and I am working on an E2E regression test that will fail if this ever shows back up.

**Pull request merged**
