### PR TITLE
Refactor: create responsive previews in the form builder

### PR DESCRIPTION
**Pull request by JoshuaHungDinh**
Resolves [GIVE-268]

## Description
This pull request (PR) introduces enhancements to achieve a width-responsive preview in the form builder by removing the sidebars from their fixed positioning. This creates a more similar experience as the WP block editor.

Changes include:
`interface-interface-skeleton__content`
- Set height to allow content to be scrolled
- Set overflow-y to allow content to scroll

`.interface-interface-skeleton__body`
- Hide overflow so entire body does not scroll

`.givewp-next-gen-sidebar`
- remove fixed positioning

## Affects
The visual form builder sidebars

## Visuals

https://github.com/impress-org/givewp/assets/75056371/e9903e49-b03f-4da5-a965-738c5cd7838a

## Testing Instructions
- Toggle the sidebars on each form builder section'Build', 'Design' & 'Settings', the content section should expand and retract accordingly.
- Each sidebar should be scrollable.
- The preview content should be scrollable.

## Pre-review Checklist
-   [x] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-268]: https://stellarwp.atlassian.net/browse/GIVE-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by pauloiankoski — CHANGES_REQUESTED** [review]
@JoshuaHungDinh Nice job on making this finally work! I have only very tiny suggestions for you. On `.interface-interface-skeleton__content`, set the height to be `calc(100vh - 60px)`, discounting the heading bar so that the scrollbar doesn't go over the end of the page. After that, you may need to reduce the lower padding a little bit to make it look nicer.

**Comment by JoshuaHungDinh** [comment]
@pauloiankoski Resolved: da26bdb428addaf1ac5e152e3e72bffc7324adb4

**Review by pauloiankoski — APPROVED** [review]
Good to go! 👏🏻 👏🏻 👏🏻

**Review by rickalday — APPROVED** [review]
Passed manual QA tests.

**Pull request merged**
