### PR TITLE
Add TestData as part of the GiveWp core

### LINKED ISSUE #5506: 'wp-cli' commands for generating test data should work in core
## User Story

As a developer, I want 'wp-cli' commands for generating test data to work in GiveWP core so that I can generate consistent test data without needing to install the Test Data addon.

## Details
The Test Data addon includes powerful logic for programmatically populating the database with test data. As we start developing improved e2e testing, it has become clear that this functionality should be available in GiveWP core, without requiring the Test Data addon to be installed. Specifically, 'wp-cli' commands for generating test data should be available on any GiveWP install. 

The admin UI associated with generating test data should remain in the test data addon, and not be introduced to GiveWP core.

## Additional Context
One critical component to this is ensuring that test data can be generated multiple times consistently, if desired. More on implementing that behavior can be found here: https://fakerphp.github.io/#seeding-the-generator

## Acceptance Criteria
-   [x] `wp-cli` commands work in GiveWP core
-   [x] No additional admin UI is introduced, the test data admin UI is not added to GiveWP core
-   [x] Optionally, test data can be generated multiple times consistently (for use with e2e testing)

### PR DESCRIPTION
**Pull request by alaca**
Resolves #5506

## Description

This PR adds TestData add-on functionality into the GiveWP core. 

## Affects

GiveWP core

## Visuals

image

## Pre-review Checklist

-   [x] Acceptance criteria satisfied and marked in related issue
-   [x] Relevant `@since` tags included in DocBlocks
-   [x] Changes logged to the `Unreleased` section of `CHANGELOG.md`
-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

## Testing Instructions

1. Use `wp help give` to get a list of available commands
2. Use `wp help give COMMAND_NAME` for help on how to use the specific command

A complete list of available CLI commands is also documented in the README.md file

### CODE REVIEW

**Review by henryholtgeerts — COMMENTED** [review]
Hmm...I'm having trouble getting your changes to work for me locally. For context: I do not have the WP Test Data addon installed or enabled. When I run `wp help give` these are the commands I see listed:

Screen Shot 2020-12-14 at 1 32 24 PM

We'll see if @kjohnson experiences the same issue.

**Comment by kjohnson** [comment]
```wp help give```

Looks good to me.

image

**Comment by kjohnson** [comment]
@alaca I am getting the following error:

```Error: Too few arguments to function Give\TestData\Addons\FeeRecovery\FeeRecovery::addFee(), 2 passed and exactly 3 expected```

Command: `wp give test-donations --count=100`

**Review by henryholtgeerts — APPROVED** [review]
After running composer update, resolved the issue I was facing earlier! Tested out various commands, found that they worked as expected on vanilla install of GiveWP. For purposes of helping generate test data, this PR looks good to me.

**Comment by alaca** [comment]
@kjohnson that's strange because the 3rd parameter is being passed [here](https://github.com/impress-org/givewp/blob/db63d8afaa98104ea6d4b3a3f923f32e76bb0b02/src/TestData/Repositories/DonationRepository.php#L87) and the default value is set [here](https://github.com/impress-org/givewp/blob/db63d8afaa98104ea6d4b3a3f923f32e76bb0b02/src/TestData/Commands/DonationSeedCommand.php#L90). 
 
I wasn't able to reproduce this issue. What about you @henryholtgeerts?

**Comment by kjohnson** [comment]
@alaca Ok, I'm seeing that now. Not sure why I wasn't seeing that before.

**Comment by kjohnson** [comment]
@alaca Looks like I still had the Test Data add-on running, so it was hooking into `GiveTestData\TestData\Repositories` :facepalm:

**Review by kjohnson — APPROVED** [review]

**Pull request merged**
