### PR TITLE
add Request class and group related function

### LINKED ISSUE #4619: feat: group request related helper functions into a class
# Feature Request

## Developer Story

As a developer, I want to group request related helper function so that it will not look like the global `REQUEST/GET/POST` variable scatter all over code.

## Details
ref: https://github.com/impress-org/givewp/pull/4589#pullrequestreview-386765788

@JasonTheAdams quote:
> A lot of these functions, however, reach out to global and superglobals such as $_REQUEST, $_GET, and so on. This... is less great and creates a lot of spaghetti code. How many things depend on the shape of the $_REQUEST for example? A lot.
> 
> So how do we group together these sorts of things? Well, let's take the functions that are trying to determine some condition based on the shape of the $_REQUEST, for example (or any request superglobal). Wouldn't it be cool if we could do something like $request->isProcessingActionOnAjax()? Yup, that would be cool.

## Possible Solution

Create a `Request` class and handle all conditional checks internally without need of passing param to function. `$request->isProcessingActionOnAjax()`

## Related

ref: https://github.com/impress-org/givewp/pull/4589

## Acceptance Criteria

- [ ] Code is organized  with `Request` class.
- [ ] Request is accessible from service container

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

Resolves #4619

Previously we were using the helper function in which using global parameters `$_GET, $_POST, $_REQUEST` to figure out the state of the request but as per @JasonTheAdams suggestion, we group this method or request related function to `Request` and use this class function to get state instead of worrying about vale in the global parameter.
This PR adds `Request` class and refactor code to use methods in this class.

## Affects

Mostly it will affect code in `src` directory.

## What to test

Donate from the donation form.

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
For reference, here's Symfony's Request class: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpFoundation/Request.php

**Comment by JasonTheAdams** [comment]
As a note, I'm seriously considering whether it would be possible to safely use Symfony in conjunction with https://github.com/coenjacobs/mozart. If we don't have to reinvent the wheel, that would be very cool.

**Comment by ravinderk** [comment]
@JasonTheAdams FYI, I implemented `symfony/http-foundation` `4.*` [PHP < 7 compatible ] with `mozart`: https://github.com/impress-org/givewp/compare/8eca3aff3666...3783829bf725

As per `mozart` configuration `symfony/http-foundation` with be moved to `src/Request/Symfony` and I added this to `.gitignore` because it is not necessary to add this to code. It will automatically add we somebody install composer.

**Comment by ravinderk** [comment]
As per discussion with @JasonTheAdams we will not able to use `mozart` because of PHP 7+ compatibility. We decided to copy with necessary files from `symfony/http-foundation` to `src/Vendor` directory and use it. `Give\Request\Request` will extend `Give\Request\WPRequest` which will extend `symfony/http-foundation` `Request` class.

**Comment by ravinderk** [comment]
@JasonTheAdams I reviewed this directory code (https://github.com/symfony/symfony/tree/master/src/Symfony/Component/HttpFoundation).  Extracting few files will not enough and code also depends upon `7.0+`:

**Comment by JasonTheAdams** [comment]
At least in that link you're looking at 5.x, which is probably PHP 7.x focused. What if you use the latest 4.x series? https://github.com/symfony/symfony/tree/v4.4.9/src/Symfony/Component/HttpFoundation

**Comment by ravinderk** [comment]
> At least in that link you're looking at 5.x, which is probably PHP 7.x focused. What if you use the latest 4.x series? https://github.com/symfony/symfony/tree/v4.4.9/src/Symfony/Component/HttpFoundation

@JasonTheAdams Still the same. Check screenshot.
image


We have to use `v3.4.40` to get `PHP 5.6` compatibility https://packagist.org/packages/symfony/http-foundation#v3.4.40

**Comment by JasonTheAdams** [comment]
@ravinderk Gotcha. Well, either we use the latest and have to make tweaks ourselves to make it PHP 5.x compatible, or we use the 3.x series — which isn't necessarily a bad thing. Would you mind doing a quick comparison of 5.x to 3.x (only specific to what we'd use) and see if there are any fundamental differences you feel like we'd miss? I don't think making 5.x PHP 5.x compatible would be too hard, so I'm open to either route.

**Comment by ravinderk** [comment]
I will reopen this pr when ready.

**Pull request closed without merging**
